### PR TITLE
Fix escaping issues when parsing and serializing points

### LINKED ISSUE #3704: [0.9.2] cluster replication issue for measurement name containing backslash
From a note sent to the support team, recreating it here: 

--------------

I am running on 3 nodes CENTOS 6.6 and i have created InfluxDB Cluster Configuration as very well exaplined in docs section. (i have installed InfluxDB 0.9.2 on all 3 nodes).

On the first node i created a database with: `create database mydb` which appeared on the other 3 nodes. I have inserted a measurement called cpu_load which also appeared on the other 3 nodes. All good and working as expected until now.

I have inserted another measurement called "cpu time" using the following line command: `insert cpu\ time,hostname=server01 value=100`. On this node i could succesfully query it and i had the following results:

```
> show series
name: cpu time
--------------
_key hostname
cpu\ time,hostname=server01 server01
```

Now when i tried to query it on the other nodes, i got a slightly different result:(pay attention to _key):

#On 2nd and 3rd node:

```
> show series
name: cpu time
--------------
_key hostname
cpu\\ time,hostname=server01 server01

```

So my guess is that when we insert measurements containing spaces, the replication is not working very well - it seems to add one more backslash to measurement _key on the other nodes.

-----------

There are two bugs here: one is that the backslash gets duplicated when copied to the other nodes. The second is that the insert statement should never have created a measurement name with a backslash, it should have preserved the space. The second bug is fixed in 0.9.3 I believe, but the first is likely still valid.

### PR DESCRIPTION
**Pull request by jwilder**
Fixes three issues related to quoted and escaped measurement and tags. 
* Escaped measurement were being double-escaped during replication.  This could cause inconsistent query results in a cluster.
* Quoted measurement and tags could cause a panic when parsed.  
* Measurement and tags were escaped quotes when they should not be.

Fixes #3704 #3708 #3681

### CODE REVIEW

File: tsdb/points_test.go [hunk 1]
```diff
@@ -740,7 +740,37 @@ func TestParsePointWithStringWithCommas(t *testing.T) {
 			},
 			time.Unix(1, 0)),
 	)
+}
 
+func TestParsePointQuotedMeasurement(t *testing.T) {
+	// non-escaped comma
+	test(t, `"cpu",host=serverA,region=us-east value=1.0 1000000000`,
+		tsdb.NewPoint(
+			`"cpu"`,
```
Comment (otoolep) [inline tsdb/points_test.go]: Does this mean that the actual measurement name is `"cpu"`?

File: tsdb/points_test.go [hunk 2]
```diff
@@ -1193,7 +1222,7 @@ func TestNewPointEscaped(t *testing.T) {
 
 	// equals
 	pt = tsdb.NewPoint("cpu=main", tsdb.Tags{"tag=bar": "value=foo"}, tsdb.Fields{"name=bar": 1.0}, time.Unix(0, 0))
-	if exp := `cpu\=main,tag\=bar=value\=foo name\=bar=1.0 0`; pt.String() != exp {
+	if exp := `cpu=main,tag\=bar=value\=foo name\=bar=1.0 0`; pt.String() != exp {
```
Comment (otoolep) [inline tsdb/points_test.go]: I want to be clear here. You are changing the test case. Is this on purpose?

File: tsdb/points_test.go (hunk 1 above)
Comment (jwilder) [inline tsdb/points_test.go]: Yes.  With double-quotes around it.

File: tsdb/points_test.go (hunk 2 above)
Comment (jwilder) [inline tsdb/points_test.go]: Yes.  It should not have been escaped originally.

File: tsdb/points.go [hunk 3]
```diff
@@ -707,7 +718,7 @@ func scanLine(buf []byte, i int) (int, []byte) {
 		}
 
 		// If we see a double quote, makes sure it is not escaped
-		if buf[i] == '"' && buf[i-1] != '\\' {
+		if buf[i] == '"' && (i-1 > 0 && buf[i-1] != '\\') {
```
Comment (otoolep) [inline tsdb/points.go]: Basically, want to skip `i==0`?

Comment (jwilder) [inline tsdb/points.go]: Basically, yes.  It prevents an index out of range panic when `"` is the first char.

**Comment by otoolep** [comment]
+1, cherry-pick to 0.9.3 branch makes sense to me.
