### PR TITLE
Fix querying measurement and fields with spaces

### LINKED ISSUE #3319: [0.9.1] restarting process irrevocably BREAKS measurements with spaces
Since upgrading from 0.9.0 to 0.9.1 earlier, all measurements with spaces in their names have been broken, including all historical data. The package was upgraded by downloading the `.deb` and installing in-place over 0.9.0. Once done, the server booted up without any issues, but I immediately noticed that most (but not all) of the graphs in Grafana were broken.

A bit more investigating revealed that all metrics with a single word name (e.g. `"cpu"`, `"load"`, etc.) were working fine, but anything with spaces (e.g. `"disk /boot"`, `"riemann streams rate"`) were not returning any results to queries. The queries hadn't changed, and look like this:

```
SELECT mean(value) FROM "riemann streams rate" WHERE host='$host' AND $timeFilter GROUP BY time($interval) ORDER BY asc
```

When I logged in using the `influx` CLI, I confirmed that querying for data from these measurements did not return any data. However, after running `SHOW MEASUREMENTS` I noticed that every measurement with spaces show up twice - once as usual, and once with the spaces escaped:

```
> SHOW MEASUREMENTS
http response 200
http response 201
http response 206
...
http\ response\ 200
http\ response\ 201
http\ response\ 206
...
```

I note that `SHOW SERIES` does _not_ return any measurements without escaped names, which is bizarre. As I said, querying for data from the original (unescaped) measurement returns no data; querying for data from the escaped version (by double-escaping) complains that there's no fields in that measurement:

```
> SELECT * FROM "http\\ response\\ 200"
ERR: select statement must include at least one field or function call
> SELECT value FROM "http\\ response\\ 301" LIMIT 5
ERR: unknown field or tag name in select clause: value
```

This seems to have changed something at the data storage level, because downgrading InfluxDB to 0.9.0 has not fixed the issue. So, the current state of things is that the majority of our data cannot be accessed right now, despite no errors of any kind from Riemann, InfluxDB, or Grafana. Needless to say, this is a **HUGE REGRESSION** and we're currently facing loss of all our old data to try to get this back into a working state.

I posted in IRC but there was little to no response.

### PR DESCRIPTION
**Pull request by jwilder**
In 0.9.1, measurement and field names were getting added to the shard index with and without escaped characters differently from 0.9.0.  This prevented queries against the measurements because the parser would look for an unescaped measurement, but the index would have the escaped version causing the measurement to not be queryable.  This fix ensures that the index versions are unescaped and also fixes some query bugs where fields and measurements with spaces would not be parseable.

Fixes #3319

### CODE REVIEW

File: influxql/ast.go [hunk 1]
```diff
@@ -1946,10 +1946,24 @@ func (f *Field) Name() string {
 
 // String returns a string representation of the field.
 func (f *Field) String() string {
+	str := f.Expr.String()
+
+	switch f.Expr.(type) {
+	case *VarRef:
+		// Escape any quotes in the field
+		if strings.Contains(str, `"`) {
```
Comment (pauldix) [inline influxql/ast.go]: do we need to handle single quotes too?

Comment (jwilder) [inline influxql/ast.go]: Good call.  I'll add a test and fix.

Comment (jwilder) [inline influxql/ast.go]: Updated.

**Comment by pauldix** [comment]
+1, cherry pick into 0.9.2

**Comment by beckettsean** [comment]
@jwilder does this PR do anything to fix the corrupted indexes for people who upgraded to 0.9.1, or is the only solution destroy the data and try again with 0.9.2?

**Comment by jwilder** [comment]
It should.  The indexes are in-memory so they were being indexed differently.  The data should still be in the shards unless it was manually dropped or deleted on disk by the user.

I tested this by creating measurement and fields with spaces in 0.9.0, upgraded to 0.9.1 and verified the reported error.  I then tested this fix with those existing shards by upgrading from both 0.9.0 and 0.9.1 to 0.9.2.  Both upgrade paths returned the existing data and was query-able.

**Comment by beckettsean** [comment]
That's awesome! Thanks for verifying.
