### PR TITLE
Fix write fails for multiple points when tag starts with quote

### LINKED ISSUE #3928: Write fails for multiple points when tag starts with quote
2015/09/01 11:28:41 InfluxDB starting, version 0.9.3, branch unknown, commit 2094f3fec17e7f675e5cacc8e984d98b1aec662d
````
11:25 AM $ cat points_2
baz,mytag="a x=1 1441103862125
baz,mytag=a z=1 1441103862126
11:25 AM $ curl -i -XPOST 'http://localhost:8086/write?db=foo' --data-binary @points_2
HTTP/1.1 400 Bad Request
Request-Id: 1fafe215-50c6-11e5-819c-000000000000
X-Influxdb-Version: 0.9.3
Date: Tue, 01 Sep 2015 16:25:57 GMT
Content-Length: 94
Content-Type: text/plain; charset=utf-8

unable to parse 'baz,mytag="a x=1 1441103862125
baz,mytag=a z=1 1441103862126': bad timestamp
````

### PR DESCRIPTION
**Pull request by jwilder**
Quotes in tags should are not special.  We were scanning to far if there was an unbalanced quote in the tags section.  This updates `scanLine` to only handle quotes differently if it's scanning in the fields section or later. 

Fixes #3928

### CODE REVIEW

**Comment by otoolep** [comment]
Just so I am clear, what is meant to happen here? Does the leading quote become part of the tag value?

**Comment by jwilder** [comment]
@otoolep Yes

```
> show series
name: baz
---------
_key		mytag
baz,mytag="a	"a
baz,mytag=a	a
```

File: tsdb/points_test.go [hunk 1]
```diff
@@ -785,6 +785,17 @@ func TestParsePointQuotedTags(t *testing.T) {
 	)
 }
 
+func TestParsePointsUnbalancedQuotedTags(t *testing.T) {
+	pts, err := tsdb.ParsePointsString("baz,mytag=\"a x=1 1441103862125\nbaz,mytag=a z=1 1441103862126")
+	if err != nil {
+		t.Fatalf("ParsePoints failed: %v", err)
+	}
+
+	if exp := 2; len(pts) != exp {
```
Comment (otoolep) [inline tsdb/points_test.go]: Because `"` are often used to encapsulate stuff, can you expand this test case to show that the tag value for point 1 includes the quote, just so it's crystal to next guy e.g. me?

File: tsdb/points.go [hunk 2]
```diff
@@ -739,14 +739,19 @@ func skipWhitespace(buf []byte, i int) int {
 func scanLine(buf []byte, i int) (int, []byte) {
 	start := i
 	quoted := false
+	fields := false
```
Comment (otoolep) [inline tsdb/points.go]: Mild preference for this to be called something like "processingFields", but I'll leave that you, as you know what is most consistent with the rest of this source.

**Comment by otoolep** [comment]
Some minor feedback, but +1.

File: tsdb/points_test.go (hunk 1 above)
Comment (jwilder) [inline tsdb/points_test.go]: Done.
