### PR TITLE
Fix string field value escaping

### LINKED ISSUE #3013: Panic error with inserting values with commas
#### I receive panic error when I'm trying to write message with commas in fields value.
```
# curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE DATABASE mmm"
{"results":[{}]}
```
```
# curl -XPOST 'http://localhost:8086/write?db=mmm' --data-binary '@t.g'
curl: (52) Empty reply from server
```
```
# cat t.g
{
  "database" : "mmm",
  "retentionPolicy" : "",
  "points" :  [ {
    "measurement" : "http_status",
    "tags" : {
      "service" : "identity-service",
      "hostname" : "host1",
      "url" : "http://localhost:35774/"
    },
    "timestamp" : "2015-06-16T09:28:26.000Z",
    "fields" : {
      "value_meta" : "{\"error\":\"Pattern match failed! \\\".*v3.0.*\\\" not in \\\"{\\\"version\\\": {\\\"status\\\": \\\"stable\\\", \\\"updated\\\": \\\"2015-03-30T00:00:00Z\\\", \\\"media-types\\\": [{\\\"base\\\": \\\"application/json\\\", \\\"type\\\": \\\"application/json\\\"}], \\\"id\\\": \\\"v3.4\\\", \\\"links\\\": [{\\\"href\\\": \\\"http://localhost:35774/\\\", \\\"rel\\\": \\\"self\\\"}]}}\\\"\"}",
      "value" : 1.0
    }
  } ],
  "tags" : { }
}
```

#### I see stacktrace in log (I added some printf to investigate what happens with these values):
```
field |value|
value |1|
field |value_meta|
value |{"error":"Pattern match failed! ".*v3.0.*" not in "{"version": {"status": "stable\|
field | \"updated\": \"2015-03-30T00:00:00Z\", \"media-types\": [{\"base\": \"application/json\", \"type\": \"application/json\"}], \"id\": \"v3.4\", \"links\": [{\"href\": \"http://localhost:35774/\", \"rel\": \"self\"}]}}\""}"|
panic: unsupported value type during encode fields: <nil>

goroutine 46 [running]:
github.com/influxdb/influxdb/tsdb.(*FieldCodec).EncodeFields(0xc208104180, 0xc20813a0c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/zielonkam/gocodez/src/github.com/influxdb/influxdb/tsdb/shard.go:582 +0xf3b
github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints(0xc208110240, 0xc2081461b0, 0x1, 0x1, 0x0, 0x0)
	/home/zielonkam/gocodez/src/github.com/influxdb/influxdb/tsdb/shard.go:145 +0x427
github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard(0xc2080376c0, 0x1, 0xc2081461b0, 0x1, 0x1, 0x0, 0x0)
	/home/zielonkam/gocodez/src/github.com/influxdb/influxdb/tsdb/store.go:260 +0xf7
github.com/influxdb/influxdb/cluster.func·002(0x1, 0x1, 0xc2081461b0, 0x1, 0x1)
	/home/zielonkam/gocodez/src/github.com/influxdb/influxdb/cluster/points_writer.go:241 +0xfc
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
	/home/zielonkam/gocodez/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x30b





panic: unsupported value type during encode fields: <nil>

goroutine 43 [running]:
github.com/influxdb/influxdb/tsdb.(*FieldCodec).EncodeFields(0xc2080ed5f0, 0xc2081193b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/shard.go:573 +0x8e3
github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints(0xc2080fe240, 0xc2080ed220, 0x1, 0x1, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/shard.go:142 +0x427
github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard(0xc208065800, 0x2, 0xc2080ed220, 0x1, 0x1, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/store.go:256 +0xf7
github.com/influxdb/influxdb/cluster.func·002(0x2, 0x1, 0xc2080ed220, 0x1, 0x1)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cluster/points_writer.go:213 +0xfc
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cluster/points_writer.go:243 +0x2f
```

#### I checked that if I escape commas in field as below then influxdb is working properly:
```
{
  "database" : "mmm",
  "retentionPolicy" : "",
  "points" :  [ {
    "measurement" : "http_status",
    "tags" : {
      "service" : "identity-service",
      "hostname" : "host1",
      "url" : "http://localhost:35774/"
    },
    "timestamp" : "2015-06-16T09:28:26.000Z",
    "fields" : {
      "value_meta" : "{\"error\":\"Pattern match failed! \\\".*v3.0.*\\\" not in \\\"{\\\"version\\\": {\\\"status\\\": \\\"stable\\\"\\, \\\"updated\\\": \\\"2015-03-30T00:00:00Z\\\"\\, \\\"media-types\\\": [{\\\"base\\\": \\\"application/json\\\"\\, \\\"type\\\": \\\"application/json\\\"}]\\, \\\"id\\\": \\\"v3.4\\\"\\, \\\"links\\\": [{\\\"href\\\": \\\"http://localhost:35774/\\\"\\, \\\"rel\\\": \\\"self\\\"}]}}\\\"\"}",
      "value" : 1.0
    }
  } ],
  "tags" : { }
}
```

### PR DESCRIPTION
**Pull request by jwilder**
Commas and quotes could get escaped and parsed incorrectly if they
were both present in a string value.

Fixes #3013

### CODE REVIEW

**Comment by otoolep** [comment]
CHANGELOG needs updating.

File: tsdb/points.go [hunk 1]
```diff
@@ -68,6 +71,13 @@ func init() {
 	for k, v := range escapeCodes {
 		escapeCodesStr[string(k)] = string(v)
 	}
+
+	// Compile the regex that detects unquoted double quote sequences
+	var err error
+	quoteReplacer, err = regexp.Compile(`([^\\])"`)
```
Comment (otoolep) [inline tsdb/points.go]: Just use https://golang.org/pkg/regexp/#MustCompile, no?

Comment (jwilder) [inline tsdb/points.go]: Yeah.  Forgot about that func.  Updated.

File: tsdb/points.go [hunk 2]
```diff
@@ -604,7 +608,8 @@ func scanFieldValue(buf []byte, i int) (int, []byte) {
 			break
 		}
 
-		if buf[i] == '"' {
+		// If we see a double quote, makes sure it is not escaped
+		if buf[i] == '"' && buf[i-1] != '\\' {
```
Comment (otoolep) [inline tsdb/points.go]: If `i` is zero, this might blow up, right?

File: tsdb/points_test.go [hunk 3]
```diff
@@ -475,6 +475,37 @@ func TestParsePointWithStringWithCommas(t *testing.T) {
...
+	// escaped comma and quotes
+	test(t, `cpu,host=serverA,region=us-east value="{Hello\"{\,}\" World}" 1000000000`,
+		NewPoint(
+			"cpu",
+			Tags{
+				"host":   "serverA",
+				"region": "us-east",
+			},
+			Fields{
+				"value": `{Hello"{\,}" World}`,
```
Comment (otoolep) [inline tsdb/points_test.go]: Why is the comma still preceded by a `\`? I don't follow.

File: tsdb/points.go (hunk 2 above)
Comment (jwilder) [inline tsdb/points.go]: Technically, yes, if you call `scanFieldValue(buf, 0)` directly then it can blow up but `i` can't be zero during parsing because the we need to scan the the field name first and it must be non-zero in length so the function is always called with a non-zero value for `i`.  I could special case it here too but didn't think it was necessary since the func is private and only called in one place.

Comment (otoolep) [inline tsdb/points.go]: Cool on that reasoning -- thanks.

Comment (jwilder) [inline tsdb/points.go]: Called here: https://github.com/influxdb/influxdb/blob/master/tsdb/points.go#L890

File: tsdb/points_test.go (hunk 3 above)
Comment (jwilder) [inline tsdb/points_test.go]: Only `"` need to be escaped/unescaped for string fields.  Everything else is left as is.  We were escaping/unescaping commas and spaces incorrectly here before as well.

Comment (otoolep) [inline tsdb/points_test.go]: OK

**Comment by otoolep** [comment]
+1, I see where you're going.
