### PR TITLE
Derivative query with group by time but no aggregate function validation

### LINKED ISSUE #3718: Derivative query with group by time but no aggregate function should fail parse
If you do the query:

```sql
select derivative(value) from foo where time > now() - 4h group by time(1m)
```

That query should fail. Derivatives with a `GROUP BY time` clause require an aggregate function to be in the call to derivative, like this:

```sql
select derivative(first(value)) from foo where time > now() - 4h group by time(1m)
```

This should be validated at parse time. The error message should indicate that they can use an aggregate function inside the call to derivative, like min, max, first, last, mean, or sum.

### PR DESCRIPTION
**Pull request by corylanou**
Fixes #3718

### CODE REVIEW

File: influxql/ast.go [hunk 1]
```diff
@@ -1133,6 +1133,23 @@ func (s *SelectStatement) validateAggregates(tr targetRequirement) error {
 				if err := s.validSelectWithAggregate(numAggregates); err != nil {
 					return err
 				}
+				// Validate that if they have a time dimension, they need a sub-call like min/max, etc.
+				if s.hasTimeDimensions(s.Condition) {
+					var valid bool
+					for _, a := range expr.Args {
+						if c, ok := a.(*Call); ok {
+							n := strings.ToLower(c.Name)
+							if n == "min" || n == "max" || n == "first" || n == "last" || n == "mean" || n == "sum" {
```
Comment (jwilder) [inline influxql/ast.go]: Is this actually required?  Might be a bit brittle as we add new functions.  

I think `count` could be here as well.

Comment (corylanou) [inline influxql/ast.go]: That's a good question.  I felt the same way, but @pauldix specifically wanted the error to list them, so that was automatically brittle.  It made sense that the check as identical to the error.  I think either we have it in both spots, or take it out of both spots.

Comment (jwilder) [inline influxql/ast.go]: I think `spread` would also be needed to handle counter type measurements.

**Comment by jwilder** [comment]
:+1:
