### PR TITLE
do not allow empty database name, closes #1950

### LINKED ISSUE #1950: Error when creating a DB via the REST API
Accidently, I created a database with an empty name via the REST API.  It allowed me to remove the database, but since then, I can't create any databases anymore.

I always receive the error below:
error: "error parsing query: found -, expected ;, EOF at line 1, char 18"

This is on 0.9 rc10

### PR DESCRIPTION
**Pull request by dullgiulio**
As reported in #1950, disallow empty database names in both DB creation and JSON unmarshalling.

### CODE REVIEW

**Comment by otoolep** [comment]
Changes look good @dullgiulio -- can you make the extra changes I suggested, and sign the CLA?

**Comment by dullgiulio** [comment]
Sure, here you go. Also signed the CLA.

File: server_test.go [hunk 1]
```diff
@@ -321,6 +326,11 @@ func TestServer_DropDatabase(t *testing.T) {
 	s := OpenServer(NewMessagingClient())
 	defer s.Close()
 
+	// Attempt creating empty name database.
```
Comment (otoolep) [inline server_test.go]: Nit: comment is not quite right.

**Comment by otoolep** [comment]
Thanks @dullgiulio -- I will merge.
