### PR TITLE
Fix auth for CLI

### LINKED ISSUE #2239: Auth does not work in CLI
<code>use mydb</code>
<code>auth</code>
<code>username: mylogin</code>
<code>password: ...</code>

ERR: unable to parse Basic Auth credentials

### PR DESCRIPTION
**Pull request by corylanou**
The auth for CLI was not setting credentials properly in the client package.

This PR does a couple things:

1) Refactored the ParseConfig logic in the `cmd/influxd` package to be more consistent.  This was a side affect of trying to trace down where configs were parsed and was just to difficult to leave the current code.
2) Added a `SetAuth` to the client library to allow for resetting credentials.
3) Changed the client library to use basic authentication via headers instead of the uri.  Effectively moving from http://golang.org/pkg/net/url/#UserPassword to http://golang.org/pkg/net/http/#Request.SetBasicAuth

Fixes #2239

### CODE REVIEW

**Comment by corylanou** [comment]
As a side note, there is no real way to write a test for this as both the `cmd/influxd` and `cmd/influx` are `main` packages, so I can't spin up a server in memory to test it.  I'm open to other ideas if anyone has them.

**Comment by corylanou** [comment]
@otoolep previously, we had just `NewConfig` which wasn't specific enough between what we wanted for true server defaults, vs what we wanted to have to run in `Demo/Test` mode.

However, when we know we want a "Test" config (AKA Demo Mode), then we call that specifically.  This was already happening behind the scenes before I made this change, but now you see it where it happens, which I like a lot more.

For reference, here is what we add when you ask for a test config:

```
func NewTestConfig() (*Config, error) {
  c := NewConfig()

  // By default, store broker and data files in current users home directory
  u, err := user.Current()
  if err != nil {
    return nil, fmt.Errorf("failed to determine current user for storage")
  }

  c.Broker.Enabled = true
  c.Broker.Dir = filepath.Join(u.HomeDir, ".influxdb/broker")

  c.Data.Enabled = true
  c.Data.Dir = filepath.Join(u.HomeDir, ".influxdb/data")

  c.Admin.Enabled = true
  c.Admin.Port = 8083

  c.Monitoring.Enabled = false
  c.Snapshot.Enabled = true

  return c, nil
}
```

**Comment by otoolep** [comment]
OK, thanks @corylanou, makes sense. This is a different change, but `TestConfig` isn't a great name IMHO, and is what threw me. It sounds like some sort of config used for our testing, not a default config that is used is no path is supplied. It's more like `NewDefaultConfig`.

**Comment by otoolep** [comment]
Otherwise change looks fine.

**Comment by corylanou** [comment]
Agree on the naming.  it was between `NewDemoConfig` or `NewTestConfig`.  Some day we may come up with a better name.

**Comment by toddboom** [comment]
lgtm :shipit:

File: cmd/influx/main_test.go [hunk 1]
```diff
@@ -75,3 +82,161 @@ func TestParseCommand_Use(t *testing.T) {
...
+func TestQuery_NoAuth(t *testing.T) {
+	if testing.Short() {
+		t.Skip("skipping TestQuery_NoAuth")
+	}
+
+	// Create root path to server.
+	// Remove it to clean up past failed panics
+	// Defer it to clean up for successful tests
+	path := tempfile()
+	os.Remove(path)
```
Comment (otoolep) [inline cmd/influx/main_test.go]: `tempfile()` already removes the path, and cleaning up past runs is not possible, since the path changes each time.

File: cmd/influxd/run.go [hunk 2]
```diff
@@ -160,10 +159,34 @@ func (s *Node) closeSnapshotListener() error {
...
+
+		if err != nil {
+			return fmt.Errorf("error parsing config %s - %s\n", path, err)
+		}
+		// Override config properties.
+		if hostname != "" {
+			cmd.config.Hostname = hostname
+		}
+
+		log.Printf("using config: %s\n", path)
```
Comment (otoolep) [inline cmd/influxd/run.go]: FWIW, I'd be a bit more explicit here since this is a log message for the user too.

`using configuration at ....`

whatever you think, I just like to be clearer.

File: cmd/influxd/run.go [hunk 3]
```diff
@@ -160,10 +159,34 @@ func (s *Node) closeSnapshotListener() error {
...
+		return nil
+	}
 
+	cmd.config, err = NewTestConfig()
+	if err != nil {
+		return fmt.Errorf("error parsing default config: %s\n", err)
+	}
+	log.Println("no config provided, using default settings")
```
Comment (otoolep) [inline cmd/influxd/run.go]: Pure style: I think we should spell out `config` when messages are for users too.

**Comment by otoolep** [comment]
Looks good, just some minor feedback. Unfortunately I don't think we can clean up directories if a test panics, so that part of the change might be optimistic.

File: cmd/influxd/run.go (hunk 3 above)
Comment (toddboom) [inline cmd/influxd/run.go]: Do you mean `config` => `configuration` ?

Comment (toddboom) [inline cmd/influxd/run.go]: Oh, just saw above. Nevermind.
