### PR TITLE
Fix metafile so it doesn't get trampled by other goroutines.

### LINKED ISSUE #3832: [0.9.3-rc2] panic: runtime error: makeslice: len out of range (InfluxDB does not restart until WAL deleted)
Similar to https://github.com/influxdb/influxdb/issues/3730

```
2015-08-25 20:11:28.363628500  8888888           .d888 888                   8888888b.  888888b.
2015-08-25 20:11:28.363629500    888            d88P"  888                   888  "Y88b 888  "88b
2015-08-25 20:11:28.363630500    888            888    888                   888    888 888  .88P
2015-08-25 20:11:28.363631500    888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
2015-08-25 20:11:28.363632500    888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
2015-08-25 20:11:28.363633500    888   888  888 888    888 888  888   X88K   888    888 888    888
2015-08-25 20:11:28.363656500    888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
2015-08-25 20:11:28.363657500  8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"
2015-08-25 20:11:28.363658500 
2015-08-25 20:11:28.465026500 no configuration provided, using default settings
2015-08-25 20:11:28.467226500 [metastore] 2015/08/25 20:11:28 Using data dir: /root/.influxdb/meta
2015-08-25 20:11:28.469739500 [metastore] 2015/08/25 20:11:28 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
2015-08-25 20:11:28.469853500 [store] 2015/08/25 20:11:28 Using data dir: /root/.influxdb/data
2015-08-25 20:11:28.469946500 [metastore] 2015/08/25 20:11:28 Node at localhost:8088 [Follower]
2015-08-25 20:11:29.858793500 [metastore] 2015/08/25 20:11:29 Node at localhost:8088 [Leader]. peers=[localhost:8088]
2015-08-25 20:11:29.870381500 [metastore] 2015/08/25 20:11:29 Updated node id=1 hostname=localhost:8088
2015-08-25 20:11:45.006479500 [wal] 2015/08/25 20:11:45 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:11:45.006480500 [wal] 2015/08/25 20:11:45 WAL writing to /root/.influxdb/wal/example/default/12
2015-08-25 20:11:59.409930500 [wal] 2015/08/25 20:11:59 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:11:59.409932500 [wal] 2015/08/25 20:11:59 WAL writing to /root/.influxdb/wal/example/default/13
2015-08-25 20:12:11.365990500 [wal] 2015/08/25 20:12:11 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:12:11.365992500 [wal] 2015/08/25 20:12:11 WAL writing to /root/.influxdb/wal/example/default/14
2015-08-25 20:12:22.090104500 [wal] 2015/08/25 20:12:22 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:12:22.090106500 [wal] 2015/08/25 20:12:22 WAL writing to /root/.influxdb/wal/example/default/15
2015-08-25 20:12:31.859258500 [wal] 2015/08/25 20:12:31 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:12:31.859260500 [wal] 2015/08/25 20:12:31 WAL writing to /root/.influxdb/wal/example/default/16
2015-08-25 20:12:39.574495500 [wal] 2015/08/25 20:12:39 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:12:39.574497500 [wal] 2015/08/25 20:12:39 WAL writing to /root/.influxdb/wal/example/default/17
2015-08-25 20:12:50.599383500 [wal] 2015/08/25 20:12:50 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:12:50.599385500 [wal] 2015/08/25 20:12:50 WAL writing to /root/.influxdb/wal/example/default/19
2015-08-25 20:13:00.548703500 [wal] 2015/08/25 20:13:00 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:13:00.548705500 [wal] 2015/08/25 20:13:00 WAL writing to /root/.influxdb/wal/example/default/20
2015-08-25 20:13:11.258969500 [wal] 2015/08/25 20:13:11 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:13:11.258971500 [wal] 2015/08/25 20:13:11 WAL writing to /root/.influxdb/wal/example/default/21
2015-08-25 20:13:23.354210500 [wal] 2015/08/25 20:13:23 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:13:23.354213500 [wal] 2015/08/25 20:13:23 WAL writing to /root/.influxdb/wal/example/default/22
2015-08-25 20:13:39.113854500 [wal] 2015/08/25 20:13:39 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:13:39.113856500 [wal] 2015/08/25 20:13:39 WAL writing to /root/.influxdb/wal/example/default/23
2015-08-25 20:13:55.630614500 [wal] 2015/08/25 20:13:55 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:13:55.630616500 [wal] 2015/08/25 20:13:55 WAL writing to /root/.influxdb/wal/example/default/24
2015-08-25 20:14:11.657022500 [wal] 2015/08/25 20:14:11 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:14:11.657024500 [wal] 2015/08/25 20:14:11 WAL writing to /root/.influxdb/wal/example/default/25
2015-08-25 20:14:26.428152500 [wal] 2015/08/25 20:14:26 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:14:26.428154500 [wal] 2015/08/25 20:14:26 WAL writing to /root/.influxdb/wal/example/default/26
2015-08-25 20:14:41.745073500 [wal] 2015/08/25 20:14:41 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:14:41.745076500 [wal] 2015/08/25 20:14:41 WAL writing to /root/.influxdb/wal/example/default/3
2015-08-25 20:14:58.164222500 [wal] 2015/08/25 20:14:58 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:14:58.164224500 [wal] 2015/08/25 20:14:58 WAL writing to /root/.influxdb/wal/example/default/5
2015-08-25 20:15:12.202923500 [wal] 2015/08/25 20:15:12 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:15:12.202925500 [wal] 2015/08/25 20:15:12 WAL writing to /root/.influxdb/wal/example/default/7
2015-08-25 20:15:26.478782500 [wal] 2015/08/25 20:15:26 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:15:26.478784500 [wal] 2015/08/25 20:15:26 WAL writing to /root/.influxdb/wal/example/default/8
2015-08-25 20:15:39.633596500 [wal] 2015/08/25 20:15:39 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:15:39.633598500 [wal] 2015/08/25 20:15:39 WAL writing to /root/.influxdb/wal/example/default/9
2015-08-25 20:15:43.473918500 [wal] 2015/08/25 20:15:43 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
2015-08-25 20:15:43.473920500 [wal] 2015/08/25 20:15:43 WAL writing to /root/.influxdb/wal/example/fourweeks/6
2015-08-25 20:15:54.279327500 panic: runtime error: makeslice: len out of range
2015-08-25 20:15:54.279335500 
2015-08-25 20:15:54.279374500 goroutine 1 [running]:
2015-08-25 20:15:54.279375500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).readMetadataFile(0xc322e7a000, 0xc3b0ac6a80, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
2015-08-25 20:15:54.279376500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:371 +0x3a8
2015-08-25 20:15:54.279386500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).LoadMetadataIndex(0xc322e7a000, 0xc20804d630, 0xc2d2ef0570, 0x0, 0x0)
2015-08-25 20:15:54.279402500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:281 +0x1bd
2015-08-25 20:15:54.279411500 github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).LoadMetadataIndex(0xc2923dcc40, 0xc20804d630, 0xc2d2ef0570, 0x0, 0x0)
2015-08-25 20:15:54.279444500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:197 +0xf9
2015-08-25 20:15:54.279445500 github.com/influxdb/influxdb/tsdb.func<C2><B7>011(0x0, 0x0)
2015-08-25 20:15:54.279455500   /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:103 +0x533
2015-08-25 20:15:54.279464500 github.com/influxdb/influxdb/tsdb.(*Shard).Open(0xc249546120, 0x0, 0x0)
2015-08-25 20:15:54.279470500   /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:108 +0x5e
2015-08-25 20:15:54.279479500 github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0xc20801e340, 0x0, 0x0)
2015-08-25 20:15:54.279496500   /root/go/src/github.com/influxdb/influxdb/tsdb/store.go:257 +0xe20
2015-08-25 20:15:54.279509500 github.com/influxdb/influxdb/tsdb.(*Store).Open(0xc20801e340, 0x0, 0x0)
2015-08-25 20:15:54.279514500   /root/go/src/github.com/influxdb/influxdb/tsdb/store.go:288 +0x2ed
2015-08-25 20:15:54.279531500 github.com/influxdb/influxdb/cmd/influxd/run.func<C2><B7>003(0x0, 0x0)
2015-08-25 20:15:54.279540500   /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:325 +0xaab
2015-08-25 20:15:54.279545500 github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc2080b20e0, 0x0, 0x0)
2015-08-25 20:15:54.279562500   /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:347 +0x5e
2015-08-25 20:15:54.279571500 github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc2080b4300, 0xc20800a000, 0x0, 0x0, 0x0, 0x0)
2015-08-25 20:15:54.279584500   /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:112 +0x97e
2015-08-25 20:15:54.279602500 main.(*Main).Run(0xc20806db00, 0xc20800a000, 0x0, 0x0, 0x0, 0x0)
2015-08-25 20:15:54.279619500   /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x3f8
2015-08-25 20:15:54.279624500 main.main()
2015-08-25 20:15:54.279633500   /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xdc
2015-08-25 20:15:54.279649500 
2015-08-25 20:15:54.279650500 goroutine 6 [syscall, 4 minutes]:
2015-08-25 20:15:54.279666500 os/signal.loop()
2015-08-25 20:15:54.279666500   /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
2015-08-25 20:15:54.279683500 created by os/signal.init<C2><B7>1
2015-08-25 20:15:54.279684500   /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35
2015-08-25 20:15:54.279693500 
2015-08-25 20:15:54.279693500 goroutine 17 [syscall, 4 minutes, locked to thread]:
2015-08-25 20:15:54.279706500 runtime.goexit()
2015-08-25 20:15:54.279715500   /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1
2015-08-25 20:15:54.279724500 
2015-08-25 20:15:54.279724500 goroutine 8 [IO wait, 4 minutes]:
2015-08-25 20:15:54.279740500 net.(*pollDesc).Wait(0xc208010370, 0x72, 0x0, 0x0)
2015-08-25 20:15:54.279757500   /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
2015-08-25 20:15:54.279762500 net.(*pollDesc).WaitRead(0xc208010370, 0x0, 0x0)
2015-08-25 20:15:54.279779500   /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
2015-08-25 20:15:54.279783500 net.(*netFD).accept(0xc208010310, 0x0, 0x7f3d6467fe30, 0xc2080ee000)
2015-08-25 20:15:54.279804500   /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
2015-08-25 20:15:54.279809500 net.(*TCPListener).AcceptTCP(0xc208032190, 0x0, 0x0, 0x0)
2015-08-25 20:15:54.279822500   /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
2015-08-25 20:15:54.279839500 net.(*TCPListener).Accept(0xc208032190, 0x0, 0x0, 0x0, 0x0)
2015-08-25 20:15:54.279849500   /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
2015-08-25 20:15:54.279865500 github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080c1680, 0x7f3d64685eb8, 0xc208032190, 0x0, 0x0)
2015-08-25 20:15:54.279875500   /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
2015-08-25 20:15:54.279891500 created by github.com/influxdb/influxdb/cmd/influxd/run.func<C2><B7>003
2015-08-25 20:15:54.279892500   /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:313 +0x8f2
2015-08-25 20:15:54.279901500 
2015-08-25 20:15:54.279901500 goroutine 9 [chan receive, 4 minutes]:
2015-08-25 20:15:54.279916500 github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208032198, 0x0, 0x0, 0x0, 0x0)
2015-08-25 20:15:54.279946500   /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
2015-08-25 20:15:54.279947500 github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080c1740, 0x0, 0x0, 0x0, 0x0)
2015-08-25 20:15:54.279961500   /root/go/src/github.com/influxdb/influxdb/meta/store.go:2058 +0x64
2015-08-25 20:15:54.279978500 github.com/hashicorp/raft.(*NetworkTransport).listen(0xc208010460)
2015-08-25 20:15:54.279978500   /root/go/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
2015-08-25 20:15:54.279987500 created by github.com/hashicorp/raft.NewNetworkTransport
2015-08-25 20:15:54.279996500   /root/go/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4
2015-08-25 20:15:54.280005500 
2015-08-25 20:15:54.280005500 goroutine 10 [select]:
2015-08-25 20:15:54.280013500 github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080c21c0)
2015-08-25 20:15:54.280029500   /root/go/src/github.com/hashicorp/raft/raft.go:826 +0xc7c
2015-08-25 20:15:54.280034500 github.com/hashicorp/raft.(*Raft).runLeader(0xc2080c21c0)
2015-08-25 20:15:54.280043500   /root/go/src/github.com/hashicorp/raft/raft.go:798 +0x74e
2015-08-25 20:15:54.280051500 github.com/hashicorp/raft.(*Raft).run(0xc2080c21c0)
2015-08-25 20:15:54.280059500   /root/go/src/github.com/hashicorp/raft/raft.go:595 +0xc9
2015-08-25 20:15:54.280068500 github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)<C2><B7>fm()
2015-08-25 20:15:54.280078500   /root/go/src/github.com/hashicorp/raft/raft.go:245 +0x27
2015-08-25 20:15:54.280086500 github.com/hashicorp/raft.func<C2><B7>011()
2015-08-25 20:15:54.280087500   /root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
2015-08-25 20:15:54.280103500 created by github.com/hashicorp/raft.(*raftState).goFunc
2015-08-25 20:15:54.280104500   /root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3
2015-08-25 20:15:54.280112500 
2015-08-25 20:15:54.280113500 goroutine 11 [select, 4 minutes]:
2015-08-25 20:15:54.280129500 github.com/hashicorp/raft.(*Raft).runFSM(0xc2080c21c0)
2015-08-25 20:15:54.280141500   /root/go/src/github.com/hashicorp/raft/raft.go:502 +0x1043
2015-08-25 20:15:54.280147500 github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)<C2><B7>fm()
2015-08-25 20:15:54.280155500   /root/go/src/github.com/hashicorp/raft/raft.go:246 +0x27
2015-08-25 20:15:54.280160500 github.com/hashicorp/raft.func<C2><B7>011()
2015-08-25 20:15:54.280169500   /root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
2015-08-25 20:15:54.280178500 created by github.com/hashicorp/raft.(*raftState).goFunc
2015-08-25 20:15:54.280179500   /root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3
2015-08-25 20:15:54.280187500 
2015-08-25 20:15:54.280196500 goroutine 12 [select, 1 minutes]:
2015-08-25 20:15:54.280209500 github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080c21c0)
2015-08-25 20:15:54.280218500   /root/go/src/github.com/hashicorp/raft/raft.go:1613 +0x466
2015-08-25 20:15:54.280227500 github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)<C2><B7>fm()
2015-08-25 20:15:54.280227500   /root/go/src/github.com/hashicorp/raft/raft.go:247 +0x27
2015-08-25 20:15:54.280236500 github.com/hashicorp/raft.func<C2><B7>011()
2015-08-25 20:15:54.280244500   /root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
2015-08-25 20:15:54.280253500 created by github.com/hashicorp/raft.(*raftState).goFunc
2015-08-25 20:15:54.280253500   /root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3
2015-08-25 20:15:54.280270500 
2015-08-25 20:15:54.280271500 goroutine 13 [select, 4 minutes]:
2015-08-25 20:15:54.280278500 github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc208072ba0)
2015-08-25 20:15:54.280287500   /root/go/src/github.com/influxdb/influxdb/meta/state.go:187 +0x46e
2015-08-25 20:15:54.280296500 created by github.com/influxdb/influxdb/meta.(*localRaft).open
2015-08-25 20:15:54.280305500   /root/go/src/github.com/influxdb/influxdb/meta/state.go:177 +0x130c
2015-08-25 20:15:54.280313500 
2015-08-25 20:15:54.280314500 goroutine 14 [chan receive, 4 minutes]:
2015-08-25 20:15:54.280330500 github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080321a0, 0x0, 0x0, 0x0, 0x0)
2015-08-25 20:15:54.280343500   /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
2015-08-25 20:15:54.280367500 github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc208062000)
2015-08-25 20:15:54.280368500   /root/go/src/github.com/influxdb/influxdb/meta/store.go:619 +0x8f
2015-08-25 20:15:54.280377500 created by github.com/influxdb/influxdb/meta.(*Store).Open
2015-08-25 20:15:54.280377500   /root/go/src/github.com/influxdb/influxdb/meta/store.go:239 +0x391
2015-08-25 20:15:54.280386500 
2015-08-25 20:15:54.280386500 goroutine 15 [chan receive, 4 minutes]:
2015-08-25 20:15:54.280402500 github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080321a8, 0x0, 0x0, 0x0, 0x0)
2015-08-25 20:15:54.280416500   /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
2015-08-25 20:15:54.280425500 github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc208062000)
2015-08-25 20:15:54.280434500   /root/go/src/github.com/influxdb/influxdb/meta/store.go:723 +0xc9
2015-08-25 20:15:54.280443500 created by github.com/influxdb/influxdb/meta.(*Store).Open
2015-08-25 20:15:54.280451500   /root/go/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3db
2015-08-25 20:15:54.280460500 
2015-08-25 20:15:54.280460500 goroutine 18 [select, 4 minutes]:
2015-08-25 20:15:54.280476500 github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc2080b20e0, 0xc2080721e0)
2015-08-25 20:15:54.280482500   /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:442 +0x14a
2015-08-25 20:15:54.280491500 created by github.com/influxdb/influxdb/cmd/influxd/run.func<C2><B7>003
2015-08-25 20:15:54.280500500   /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:319 +0xa63
2015-08-25 20:15:54.280509500 
2015-08-25 20:15:54.280509500 goroutine 35 [select]:
2015-08-25 20:15:54.280525500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b21c0, 0xc247bca120)
2015-08-25 20:15:54.280534500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.280539500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.280548500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.280557500 
2015-08-25 20:15:54.280557500 goroutine 36 [select]:
2015-08-25 20:15:54.280565500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b2620, 0xc247bca1e0)
2015-08-25 20:15:54.280574500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.280590500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.280591500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.280607500 
2015-08-25 20:15:54.280608500 goroutine 50 [select]:
2015-08-25 20:15:54.280616500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b2700, 0xc27ce94480)
2015-08-25 20:15:54.280621500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.280638500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.280639500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.280648500 
2015-08-25 20:15:54.280648500 goroutine 194 [select]:
2015-08-25 20:15:54.280664500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc287216380, 0xc2f9834360)
2015-08-25 20:15:54.280673500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.280679500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.280687500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.280696500 
2015-08-25 20:15:54.280696500 goroutine 82 [select]:
2015-08-25 20:15:54.280705500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b27e0, 0xc25ae382a0)
2015-08-25 20:15:54.280714500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.280722500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.280731500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.280740500 
2015-08-25 20:15:54.280740500 goroutine 83 [select]:
2015-08-25 20:15:54.280749500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b29a0, 0xc271e3c0c0)
2015-08-25 20:15:54.280765500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.280774500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.280775500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.280783500 
2015-08-25 20:15:54.280784500 goroutine 52 [select]:
2015-08-25 20:15:54.280799500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc287216000, 0xc28734e120)
2015-08-25 20:15:54.280804500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.280813500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.280822500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.280831500 
2015-08-25 20:15:54.280831500 goroutine 98 [select]:
2015-08-25 20:15:54.280839500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b28c0, 0xc20b2f4900)
2015-08-25 20:15:54.280848500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.280865500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.280866500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.280874500 
2015-08-25 20:15:54.280875500 goroutine 106 [select]:
2015-08-25 20:15:54.280891500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc287216460, 0xc3351202a0)
2015-08-25 20:15:54.280900500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.280905500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.280914500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.280922500 
2015-08-25 20:15:54.280922500 goroutine 51 [select]:
2015-08-25 20:15:54.280931500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b2a80, 0xc25ae3ab40)
2015-08-25 20:15:54.280939500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.280948500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.280957500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.280966500 
2015-08-25 20:15:54.280966500 goroutine 104 [select]:
2015-08-25 20:15:54.280975500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2872161c0, 0xc2fe6ba240)
2015-08-25 20:15:54.280983500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.281000500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.281000500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.281009500 
2015-08-25 20:15:54.281009500 goroutine 89 [select]:
2015-08-25 20:15:54.281026500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b2e00, 0xc2d29766c0)
2015-08-25 20:15:54.281035500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.281040500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.281049500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.281058500 
2015-08-25 20:15:54.281058500 goroutine 114 [select]:
2015-08-25 20:15:54.281067500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b2b60, 0xc2a17b9140)
2015-08-25 20:15:54.281075500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.281084500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.281093500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.281102500 
2015-08-25 20:15:54.281102500 goroutine 53 [select]:
2015-08-25 20:15:54.281110500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b2c40, 0xc28734e360)
2015-08-25 20:15:54.281119500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.281135500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.281136500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.281145500 
2015-08-25 20:15:54.281153500 goroutine 54 [select]:
2015-08-25 20:15:54.281162500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2872160e0, 0xc2b33d20c0)
2015-08-25 20:15:54.281171500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.281176500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.281184500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.281193500 
2015-08-25 20:15:54.281193500 goroutine 105 [select]:
2015-08-25 20:15:54.281201500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b2ee0, 0xc2fc35c180)
2015-08-25 20:15:54.281210500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.281227500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.281228500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.281248500 
2015-08-25 20:15:54.281248500 goroutine 81 [select]:
2015-08-25 20:15:54.281257500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b2d20, 0xc2d30a83c0)
2015-08-25 20:15:54.281262500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.281279500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.281279500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.281289500 
2015-08-25 20:15:54.281290500 goroutine 136 [select]:
2015-08-25 20:15:54.281306500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b2fc0, 0xc315246de0)
2015-08-25 20:15:54.281315500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.281320500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.281329500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.281338500 
2015-08-25 20:15:54.281338500 goroutine 135 [select]:
2015-08-25 20:15:54.281346500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2872162a0, 0xc2fd959a40)
2015-08-25 20:15:54.281355500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.281372500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.281373500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
2015-08-25 20:15:54.281382500 
2015-08-25 20:15:54.281389500 goroutine 151 [select]:
2015-08-25 20:15:54.281398500 github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc2080b30a0, 0xc30fa2a8a0)
2015-08-25 20:15:54.281403500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4d3
2015-08-25 20:15:54.281412500 created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
2015-08-25 20:15:54.281421500   /root/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x79b
```

Influx started after deleting wal.

### LINKED ISSUE #3833: [0.9.3-rc2] panic: runtime error: makeslice: len out of range, persists on restart
I had a single-server InfluxDB instance up and running for ~20 minutes and then it crashed with the following panic.  Attempts to restart the instance resulted in a similar error (look for "InfluxDB" startup banner below).  Here is the output from the log:

```
[http] 2015/08/25 15:07:24 127.0.0.1 - - [25/Aug/2015:15:07:24 -0400] POST /write HTTP/1.1 204 0 - Apache-HttpClient/4.3.6 (java 1.5) 84ceda44-4b5c-11e5-840d-000000000000 22.0013ms
[http] 2015/08/25 15:07:24 127.0.0.1 - - [25/Aug/2015:15:07:24 -0400] POST /write HTTP/1.1 204 0 - Apache-HttpClient/4.3.6 (java 1.5) 852d4f57-4b5c-11e5-840e-000000000000 87.0049ms
[retention] 2015/08/25 15:07:31 retention policy enforcement check commencing
[retention] 2015/08/25 15:07:31 retention policy shard deletion check commencing
[http] 2015/08/25 15:07:31 127.0.0.1 - - [25/Aug/2015:15:07:31 -0400] POST /write HTTP/1.1 204 0 - Apache-HttpClient/4.3.6 (java 1.5) 892ee96b-4b5c-11e5-840f-000000000000 80.0046ms
[http] 2015/08/25 15:07:32 127.0.0.1 - - [25/Aug/2015:15:07:32 -0400] POST /write HTTP/1.1 204 0 - Apache-HttpClient/4.3.6 (java 1.5) 89f98f63-4b5c-11e5-8410-000000000000 21.0012ms
[http] 2015/08/25 15:07:33 127.0.0.1 - - [25/Aug/2015:15:07:33 -0400] POST /write HTTP/1.1 204 0 - Apache-HttpClient/4.3.6 (java 1.5) 8a13f596-4b5c-11e5-8411-000000000000 55.0031ms
[http] 2015/08/25 15:07:33 127.0.0.1 - - [25/Aug/2015:15:07:33 -0400] POST /write HTTP/1.1 204 0 - Apache-HttpClient/4.3.6 (java 1.5) 8a94e749-4b5c-11e5-8412-000000000000 32.0018ms
[http] 2015/08/25 15:07:34 127.0.0.1 - - [25/Aug/2015:15:07:34 -0400] POST /write HTTP/1.1 204 0 - Apache-HttpClient/4.3.6 (java 1.5) 8aaba3ee-4b5c-11e5-8413-000000000000 79.0045ms
[http] 2015/08/25 15:07:34 127.0.0.1 - - [25/Aug/2015:15:07:34 -0400] POST /write HTTP/1.1 204 0 - Apache-HttpClient/4.3.6 (java 1.5) 8ac5e310-4b5c-11e5-8414-000000000000 20.0012ms
[http] 2015/08/25 15:07:34 127.0.0.1 - - [25/Aug/2015:15:07:34 -0400] POST /write HTTP/1.1 204 0 - Apache-HttpClient/4.3.6 (java 1.5) 8b2346af-4b5c-11e5-8415-000000000000 77.0044ms
[http] 2015/08/25 15:07:36 127.0.0.1 - - [25/Aug/2015:15:07:36 -0400] GET /query?db=app_stats&q=select+connected%2C+busy%2C+decode%2C+%22read%22%2C+process%2C+rcvd_msgs_count%2C+rcvd_msgs_rate%2C+read_count%2C+read_events+from+%22fix.session.TNBT%2BSIM2%22 HTTP/1.1 200 2926 - InfluxDBShell/0.9.3-rc2 8be84741-4b5c-11e5-8416-000000000000 11.0006ms
panic: runtime error: makeslice: len out of range

goroutine 67 [running]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).readMetadataFile(0xc082158460, 0xc082222500, 0x47, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:371 +0x3af
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).flushMetadata(0xc082158460, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:637 +0x207
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc082158460, 0xc082128600)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:612 +0x370
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x7a2

goroutine 1 [chan receive, 20 minutes]:
main.(*Main).Run(0xc08200be40, 0xc082009fc0, 0x2, 0x2, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0x77e
main.main()
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xe3

goroutine 6 [syscall, 20 minutes]:
os/signal.loop()
	c:/go/src/os/signal/signal_unix.go:21 +0x26
created by os/signal.initÂ·1
	c:/go/src/os/signal/signal_unix.go:27 +0x3c

goroutine 17 [chan receive, 20 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc08202cd68, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x87
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc082010280)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:619 +0x96
created by github.com/influxdb/influxdb/meta.(*Store).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:239 +0x398

goroutine 8 [IO wait, 20 minutes]:
net.(*pollDesc).Wait(0xc0820a02f0, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0820a01e0, 0xb321d0, 0x8, 0xc0820e4000, 0xc0820e2000, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).acceptOne(0xc0820a0180, 0xc0820de000, 0x2, 0x2, 0xc0820a01e0, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:558 +0x547
net.(*netFD).accept(0xc0820a0180, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:585 +0x17a
net.(*TCPListener).AcceptTCP(0xc08202cd58, 0xb44630, 0x0, 0x0)
	c:/go/src/net/tcpsock_posix.go:234 +0x55
net.(*TCPListener).Accept(0xc08202cd58, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/tcpsock_posix.go:244 +0x53
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc0820d4f30, 0x138718, 0xc08202cd58, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x5e
created by github.com/influxdb/influxdb/cmd/influxd/run.funcÂ·003
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:313 +0x8f9

goroutine 9 [chan receive, 20 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc08202cd60, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x87
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc0820d4fc0, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:2058 +0x6b
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc08201b650)
	C:/projects/gocode/src/github.com/hashicorp/raft/net_transport.go:346 +0x57
created by github.com/hashicorp/raft.NewNetworkTransport
	C:/projects/gocode/src/github.com/hashicorp/raft/net_transport.go:138 +0x2cb

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc0820b01c0)
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:826 +0xc83
github.com/hashicorp/raft.(*Raft).runLeader(0xc0820b01c0)
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:798 +0x755
github.com/hashicorp/raft.(*Raft).run(0xc0820b01c0)
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:595 +0xd0
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)Â·fm()
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:245 +0x2e
github.com/hashicorp/raft.funcÂ·011()
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:152 +0x58
created by github.com/hashicorp/raft.(*raftState).goFunc
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:153 +0xea

goroutine 11 [select, 19 minutes]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc0820b01c0)
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:502 +0x104a
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)Â·fm()
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:246 +0x2e
github.com/hashicorp/raft.funcÂ·011()
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:152 +0x58
created by github.com/hashicorp/raft.(*raftState).goFunc
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:153 +0xea

goroutine 12 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc0820b01c0)
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:1613 +0x46d
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)Â·fm()
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:247 +0x2e
github.com/hashicorp/raft.funcÂ·011()
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:152 +0x58
created by github.com/hashicorp/raft.(*raftState).goFunc
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:153 +0xea

goroutine 13 [select, 20 minutes]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc08200f4a0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/state.go:187 +0x475
created by github.com/influxdb/influxdb/meta.(*localRaft).open
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/state.go:177 +0x1313

goroutine 18 [chan receive, 20 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc08202cd70, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x87
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc082010280)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:723 +0xd0
created by github.com/influxdb/influxdb/meta.(*Store).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3e2

goroutine 15 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc08205f720)
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/hh/service.go:103 +0x2ee
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/hh/service.go:67 +0x215

goroutine 20 [select, 20 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc0820ac1c0, 0xc08200eba0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:442 +0x151
created by github.com/influxdb/influxdb/cmd/influxd/run.funcÂ·003
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:319 +0xa6a

goroutine 16 [select, 20 minutes]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc08205f720)
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/hh/service.go:121 +0x2ab
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/hh/service.go:68 +0x22f

goroutine 33 [chan receive, 20 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc08202cd78, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x87
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc08201b180)
	C:/projects/gocode/src/github.com/influxdb/influxdb/cluster/service.go:83 +0x109
created by github.com/influxdb/influxdb/cluster.(*Service).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/cluster/service.go:60 +0x13f

goroutine 34 [select]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc08200dae0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/precreator/service.go:75 +0x40e
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/precreator/service.go:53 +0x211

goroutine 35 [chan receive, 20 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc08202cd80, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x87
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc08200dbd0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/snapshotter/service.go:75 +0xb4
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/snapshotter/service.go:48 +0x13a

goroutine 36 [IO wait, 20 minutes]:
net.(*pollDesc).Wait(0xc0820e22f0, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0820e21e0, 0xb321d0, 0x8, 0xc082004a60, 0xc0820a0000, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).acceptOne(0xc0820e2180, 0xc0820de0e0, 0x2, 0x2, 0xc0820e21e0, 0xc0820e0500, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:558 +0x547
net.(*netFD).accept(0xc0820e2180, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:585 +0x17a
net.(*TCPListener).AcceptTCP(0xc082134048, 0xc082106380, 0x0, 0x0)
	c:/go/src/net/tcpsock_posix.go:234 +0x55
net.(*TCPListener).Accept(0xc082134048, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/tcpsock_posix.go:244 +0x53
net/http.(*Server).Serve(0xc08210a0c0, 0x138718, 0xc082134048, 0x0, 0x0)
	c:/go/src/net/http/server.go:1728 +0x99
net/http.Serve(0x138718, 0xc082134048, 0x13d588, 0xc082004a50, 0x0, 0x0)
	c:/go/src/net/http/server.go:1606 +0xa8
github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc08200dc70)
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/admin/service.go:107 +0x14e
created by github.com/influxdb/influxdb/services/admin.(*Service).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/admin/service.go:70 +0x479

goroutine 37 [select]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc08201b1f0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:157 +0x3f0
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:93 +0x2e6

goroutine 38 [IO wait]:
net.(*pollDesc).Wait(0xc0820e2470, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0820e2360, 0xb321d0, 0x8, 0xc0821fffe0, 0xc08258c480, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).acceptOne(0xc0820e2300, 0xc0820de460, 0x2, 0x2, 0xc0820e2360, 0x127ae8, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:558 +0x547
net.(*netFD).accept(0xc0820e2300, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:585 +0x17a
net.(*TCPListener).AcceptTCP(0xc082134050, 0xc08216bdc8, 0x0, 0x0)
	c:/go/src/net/tcpsock_posix.go:234 +0x55
net.(*TCPListener).Accept(0xc082134050, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/tcpsock_posix.go:244 +0x53
net/http.(*Server).Serve(0xc082128420, 0x138718, 0xc082134050, 0x0, 0x0)
	c:/go/src/net/http/server.go:1728 +0x99
net/http.Serve(0x138718, 0xc082134050, 0x13d5b0, 0xc08201b260, 0x0, 0x0)
	c:/go/src/net/http/server.go:1606 +0xa8
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc08200ddb0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/httpd/service.go:108 +0x80
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/httpd/service.go:76 +0x692

goroutine 39 [select]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc08200f0e0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/retention/service.go:69 +0x349
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x13f

goroutine 40 [select]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc08200f0e0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/retention/service.go:102 +0x722
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/services/retention/service.go:46 +0x159

goroutine 41 [chan receive, 20 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc0820ac1c0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:393 +0x1de
created by github.com/influxdb/influxdb/cmd/influxd/run.funcÂ·003
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:342 +0xf15

goroutine 42 [select, 20 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc0820ae300)
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:140 +0x2e1
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:122 +0xdf6

goroutine 81 [IO wait, 18 minutes]:
net.(*pollDesc).Wait(0xc0820a42f0, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0820a41e0, 0xb13770, 0x7, 0xc7b108, 0xb14f70, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820a4180, 0xc082156000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc08202c048, 0xc082156000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205e048, 0xc082156000, 0x1000, 0x1000, 0xc082452450, 0x0, 0x0)
	c:/go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0820e00a0, 0xc082156000, 0x1000, 0x1000, 0xc082106380, 0x0, 0x0)
	c:/go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc0820d0420)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc0820d0420, 0x13910a, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc0820d0420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc0823e87e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc0823e87e0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc0820d0420, 0xc0821305b0, 0x0, 0x0)
	c:/go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205e000, 0x0, 0x0, 0x0)
	c:/go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205e000)
	c:/go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

goroutine 82 [IO wait, 18 minutes]:
net.(*pollDesc).Wait(0xc0820a4470, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0820a4360, 0xb13770, 0x7, 0xc7b108, 0xb14f70, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820a4300, 0xc08201d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc08202c050, 0xc08201d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205e0e8, 0xc08201d000, 0x1000, 0x1000, 0xc082452240, 0x0, 0x0)
	c:/go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0820e00e0, 0xc08201d000, 0x1000, 0x1000, 0xc08202ea80, 0x0, 0x0)
	c:/go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc0820d06c0)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc0820d06c0, 0x13920a, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc0820d06c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc0824541b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc0824541b0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc0820d06c0, 0xc0821301a0, 0x0, 0x0)
	c:/go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205e0a0, 0x0, 0x0, 0x0)
	c:/go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205e0a0)
	c:/go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

goroutine 83 [IO wait]:
net.(*pollDesc).Wait(0xc0820a45f0, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0820a44e0, 0xb13770, 0x7, 0xc7b108, 0xb14f70, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820a4480, 0xc082171000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc08202c098, 0xc082171000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205e188, 0xc082171000, 0x1000, 0x1000, 0xc0824e31e8, 0x0, 0x0)
	c:/go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0820e0120, 0xc082171000, 0x1000, 0x1000, 0xc0821b0380, 0x0, 0x0)
	c:/go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc0820d0780)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc0820d0780, 0x13930a, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc0820d0780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc082750bd0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc082750bd0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc0820d0780, 0xc0820b75f0, 0x0, 0x0)
	c:/go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205e140, 0x0, 0x0, 0x0)
	c:/go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205e140)
	c:/go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

goroutine 84 [IO wait, 7 minutes]:
net.(*pollDesc).Wait(0xc0820a4770, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0820a4660, 0xb13770, 0x7, 0xc7b108, 0xb14f70, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820a4600, 0xc082087000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc08202c0a0, 0xc082087000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205e228, 0xc082087000, 0x1000, 0x1000, 0xc08212eb38, 0x0, 0x0)
	c:/go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0820e0160, 0xc082087000, 0x1000, 0x1000, 0xc082106000, 0x0, 0x0)
	c:/go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc0820d07e0)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc0820d07e0, 0x13910a, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc0820d07e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc0821d6450, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc0821d6450, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc0820d07e0, 0xc0821a8b60, 0x0, 0x0)
	c:/go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205e1e0, 0x0, 0x0, 0x0)
	c:/go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205e1e0)
	c:/go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

goroutine 85 [IO wait, 7 minutes]:
net.(*pollDesc).Wait(0xc0820a48f0, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0820a47e0, 0xb13770, 0x7, 0xc7b108, 0xb14f70, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820a4780, 0xc082065000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc08202c0a8, 0xc082065000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205e2c8, 0xc082065000, 0x1000, 0x1000, 0xc0821243d0, 0x0, 0x0)
	c:/go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0820e0220, 0xc082065000, 0x1000, 0x1000, 0xc08202f180, 0x0, 0x0)
	c:/go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc0820d0840)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc0820d0840, 0x13900a, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc0820d0840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc0821d7260, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc0821d7260, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc0820d0840, 0xc082532f70, 0x0, 0x0)
	c:/go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205e280, 0x0, 0x0, 0x0)
	c:/go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205e280)
	c:/go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

goroutine 62 [IO wait, 7 minutes]:
net.(*pollDesc).Wait(0xc0822242f0, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0822241e0, 0xb13770, 0x7, 0xc7b108, 0xb14f70, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc082224180, 0xc0820a3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082084040, 0xc0820a3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc0820f40e8, 0xc0820a3000, 0x1000, 0x1000, 0xc0820a8cf0, 0x0, 0x0)
	c:/go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0821e2600, 0xc0820a3000, 0x1000, 0x1000, 0xc0820ee700, 0x0, 0x0)
	c:/go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc08227e780)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc08227e780, 0x138e0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc08227e780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc082585800, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc082585800, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc08227e780, 0xc082221930, 0x0, 0x0)
	c:/go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc0820f40a0, 0x0, 0x0, 0x0)
	c:/go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc0820f40a0)
	c:/go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

goroutine 61 [IO wait, 18 minutes]:
net.(*pollDesc).Wait(0xc0820a4a70, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0820a4960, 0xb13770, 0x7, 0xc7b108, 0xb14f70, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820a4900, 0xc08212d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082084038, 0xc08212d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc0820f4048, 0xc08212d000, 0x1000, 0x1000, 0xc082452190, 0x0, 0x0)
	c:/go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0821e25a0, 0xc08212d000, 0x1000, 0x1000, 0xc082106380, 0x0, 0x0)
	c:/go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc08227e720)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc08227e720, 0x138f0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc08227e720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc082454090, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc082454090, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc08227e720, 0xc0821300d0, 0x0, 0x0)
	c:/go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc0820f4000, 0x0, 0x0, 0x0)
	c:/go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc0820f4000)
	c:/go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

goroutine 152 [IO wait, 7 minutes]:
net.(*pollDesc).Wait(0xc0822248f0, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0822247e0, 0xb13770, 0x7, 0xc7b108, 0xb14f70, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc082224780, 0xc082487000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082084050, 0xc082487000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205e7c8, 0xc082487000, 0x1000, 0x1000, 0xc0824353a0, 0x0, 0x0)
	c:/go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc08245a060, 0xc082487000, 0x1000, 0x1000, 0xc082400000, 0x0, 0x0)
	c:/go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc082128720)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc082128720, 0x138d0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc082128720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc08243b710, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc08243b710, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc082128720, 0xc082260a90, 0x0, 0x0)
	c:/go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205e780, 0x0, 0x0, 0x0)
	c:/go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205e780)
	c:/go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

goroutine 56 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc0820ac0e0, 0xc08227e240)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:600 +0x4da
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:219 +0x7a2

goroutine 151 [IO wait, 18 minutes]:
net.(*pollDesc).Wait(0xc082224470, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc082224360, 0xb13770, 0x7, 0xc7b108, 0xb14f70, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc082224300, 0xc08247f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082084048, 0xc08247f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc08205e408, 0xc08247f000, 0x1000, 0x1000, 0xc0824522f0, 0x0, 0x0)
	c:/go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc08245a000, 0xc08247f000, 0x1000, 0x1000, 0xc082106380, 0x0, 0x0)
	c:/go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc082128660)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc082128660, 0x138e0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc082128660, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc08225e4e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc08225e4e0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc082128660, 0xc082130410, 0x0, 0x0)
	c:/go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc08205e3c0, 0x0, 0x0, 0x0)
	c:/go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc08205e3c0)
	c:/go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365

goroutine 273 [IO wait, 18 minutes]:
net.(*pollDesc).Wait(0xc082224a70, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc082224960, 0xb13770, 0x7, 0xc7b108, 0xb14f70, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc082224900, 0xc08248d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082084000, 0xc08248d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc0823fc048, 0xc08248d000, 0x1000, 0x1000, 0xc0824523a0, 0x0, 0x0)
	c:/go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc08228c000, 0xc08248d000, 0x1000, 0x1000, 0xc08202ea80, 0x0, 0x0)
	c:/go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc082129d40)
	c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc082129d40, 0x138c0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc082129d40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc0823e8990, 0x0, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc0823e8990, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc082129d40, 0xc0821304e0, 0x0, 0x0)
	c:/go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc0823fc000, 0x0, 0x0, 0x0)
	c:/go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc0823fc000)
	c:/go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:1751 +0x365


============================== 08/25/2015 15:07:40

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

Using configuration at: C:/projects/TNBT/data/influx/audit.ini
[metastore] 2015/08/25 15:07:40 Using data dir: C:\projects\TNBT\data\influx\audit\meta
[metastore] 2015/08/25 15:07:40 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:6002]
[store] 2015/08/25 15:07:40 Using data dir: C:\projects\TNBT\data\influx\audit\data
[metastore] 2015/08/25 15:07:40 Node at localhost:6002 [Follower]
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).readMetadataFile(0xc0820ac700, 0xc08200ce10, 0x47, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:371 +0x3af
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).LoadMetadataIndex(0xc0820ac700, 0xc0820ec0f0, 0xc0820d3a70, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:281 +0x1c4
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).LoadMetadataIndex(0xc0820d5d40, 0xc0820ec0f0, 0xc0820d3a70, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:197 +0x100
github.com/influxdb/influxdb/tsdb.funcÂ·011(0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/shard.go:103 +0x53a
github.com/influxdb/influxdb/tsdb.(*Shard).Open(0xc0820f67e0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/shard.go:108 +0x65
github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0xc0820128f0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/store.go:257 +0xe27
github.com/influxdb/influxdb/tsdb.(*Store).Open(0xc0820128f0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tsdb/store.go:288 +0x2f4
github.com/influxdb/influxdb/cmd/influxd/run.funcÂ·003(0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:325 +0xab2
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc0820ac1c0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:347 +0x65
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc0820ae300, 0xc082009fc0, 0x2, 0x2, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:112 +0x985
main.(*Main).Run(0xc08200be40, 0xc082009fc0, 0x2, 0x2, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x3ff
main.main()
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xe3

goroutine 6 [syscall]:
os/signal.loop()
	c:/go/src/os/signal/signal_unix.go:21 +0x26
created by os/signal.initÂ·1
	c:/go/src/os/signal/signal_unix.go:27 +0x3c

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc0820a62f0, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08202cd48, 0xc0820a61e0, 0xb321d0, 0x8, 0xc0820e2000, 0xc0820e0000, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).acceptOne(0xc0820a6180, 0xc0820dc000, 0x2, 0x2, 0xc0820a61e0, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:558 +0x547
net.(*netFD).accept(0xc0820a6180, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:585 +0x17a
net.(*TCPListener).AcceptTCP(0xc08202cd58, 0xb44630, 0x0, 0x0)
	c:/go/src/net/tcpsock_posix.go:234 +0x55
net.(*TCPListener).Accept(0xc08202cd58, 0x0, 0x0, 0x0, 0x0)
	c:/go/src/net/tcpsock_posix.go:244 +0x53
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc0820d2f30, 0x139620, 0xc08202cd58, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x5e
created by github.com/influxdb/influxdb/cmd/influxd/run.funcÂ·003
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:313 +0x8f9

goroutine 9 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc08202cd60, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x87
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc0820d3050, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:2058 +0x6b
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc08201b650)
	C:/projects/gocode/src/github.com/hashicorp/raft/net_transport.go:346 +0x57
created by github.com/hashicorp/raft.NewNetworkTransport
	C:/projects/gocode/src/github.com/hashicorp/raft/net_transport.go:138 +0x2cb

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).runFollower(0xc0820b01c0)
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:606 +0x8a7
github.com/hashicorp/raft.(*Raft).run(0xc0820b01c0)
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:591 +0xa3
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)Â·fm()
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:245 +0x2e
github.com/hashicorp/raft.funcÂ·011()
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:152 +0x58
created by github.com/hashicorp/raft.(*raftState).goFunc
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:153 +0xea

goroutine 11 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc0820b01c0)
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:502 +0x104a
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)Â·fm()
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:246 +0x2e
github.com/hashicorp/raft.funcÂ·011()
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:152 +0x58
created by github.com/hashicorp/raft.(*raftState).goFunc
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:153 +0xea

goroutine 12 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc0820b01c0)
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:1613 +0x46d
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)Â·fm()
	C:/projects/gocode/src/github.com/hashicorp/raft/raft.go:247 +0x2e
github.com/hashicorp/raft.funcÂ·011()
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:152 +0x58
created by github.com/hashicorp/raft.(*raftState).goFunc
	C:/projects/gocode/src/github.com/hashicorp/raft/state.go:153 +0xea

goroutine 13 [select]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc08200f620)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/state.go:187 +0x475
created by github.com/influxdb/influxdb/meta.(*localRaft).open
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/state.go:177 +0x1313

goroutine 14 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc08202cd68, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x87
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc0820103c0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:619 +0x96
created by github.com/influxdb/influxdb/meta.(*Store).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:239 +0x398

goroutine 15 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc08202cd70, 0x0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x87
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc0820103c0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:723 +0xd0
created by github.com/influxdb/influxdb/meta.(*Store).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3e2

goroutine 16 [select]:
github.com/influxdb/influxdb/meta.(*Store).WaitForLeader(0xc0820103c0, 0x0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:553 +0x416
github.com/influxdb/influxdb/meta.funcÂ·006(0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:267 +0x5f
github.com/influxdb/influxdb/meta.(*Store).syncNodeInfo(0xc0820103c0, 0x0, 0x0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:290 +0x8f
created by github.com/influxdb/influxdb/meta.(*Store).Open
	C:/projects/gocode/src/github.com/influxdb/influxdb/meta/store.go:253 +0x576

goroutine 33 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc0820ac1c0, 0xc08200eba0)
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:442 +0x151
created by github.com/influxdb/influxdb/cmd/influxd/run.funcÂ·003
	C:/projects/gocode/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:319 +0xa6a
```

### PR DESCRIPTION
**Pull request by pauldix**
Fixes #3832 and fixes #3833

### CODE REVIEW

File: tsdb/engine/wal/wal.go [hunk 1]
```diff
@@ -620,6 +623,28 @@ func (l *Log) autoflusher(closing chan struct{}) {
...
+		st, err := l.metaFile.Stat()
+		if err != nil {
+			return 0, err
+		}
+
+		return st.Size(), nil
+	}()
+	if err != nil {
+		return err
+	} else if size == 0 {
```
Comment (otoolep) [inline tsdb/engine/wal/wal.go]: Is it possible for `size` to go 0 after this check takes place? Is so, does it matter?

Comment (pauldix) [inline tsdb/engine/wal/wal.go]: nope, the file is append only

File: tsdb/engine/wal/wal.go [hunk 2]
```diff
@@ -455,7 +458,7 @@ func (l *Log) nextMetaFile() error {
 			return err
 		}
 
-		id = int(n)
+		id = int(n) + 1
```
Comment (otoolep) [inline tsdb/engine/wal/wal.go]: What is happening here?

Comment (pauldix) [inline tsdb/engine/wal/wal.go]: we roll over to a new meta file that can be written to while the old ones get emptied out and flushed to the index

Comment (otoolep) [inline tsdb/engine/wal/wal.go]: So the locking *and* this change are key to " Fix metafile so it doesn't get trampled by other goroutines"? Or are there two issues here, but only 1 in the title?

Comment (pauldix) [inline tsdb/engine/wal/wal.go]: both are necessary since changing a shared variable in goroutines should be protected by a mutex.

**Comment by otoolep** [comment]
Seems reasonable, +1, though my understanding of the WAL implementation is currently quite basic.

**Comment by pauldix** [comment]
I'm going to merge so I can get this out to people for testing. Going to do this and cut 0.9.3-rc3
