### PR TITLE
Fix parsing negative floats

### LINKED ISSUE #2919: Unable to insert negatif floats
Hi, 

With the rc33, I'm getting a parse error whatever I try to insert a negatif float value into my db.

Here's a reproduction of the bug:

    curl -XPOST 'http://localhost:8086/write' -d '
    {
        "database": "mydb",
        "retentionPolicy": "default",
        "points": [
            {
                "measurement": "cpu_load_short",
                "tags": {
                    "host": "server01",
                    "region": "us-west"
                },
                "time": "2009-11-10T23:00:00Z",
                "fields": {
                    "value": -0.64
                }
            }
        ]
    }
    '

and I get : 

    unable to parse number value '-0.64.0': strconv.ParseFloat: parsing "-0.64.0": invalid syntax
    unable to parse number value '-0.64.0': strconv.ParseFloat: parsing "-0.64.0": invalid syntax

### PR DESCRIPTION
**Pull request by jwilder**
Fixes #2919

### CODE REVIEW

File: tsdb/points.go [hunk 1]
```diff
@@ -928,7 +928,7 @@ func (p Fields) MarshalBinary() []byte {
 			// ensure there is a decimal in the encoded for
 
 			val := []byte(strconv.FormatFloat(t, 'f', -1, 64))
-			hasDecimal := t-float64(int64(t)) > 0
+			hasDecimal := t-float64(int64(t)) != 0
```
Comment (dgnorton) [inline tsdb/points.go]: Should be:
```
_, frac := math.Modf(t)
hasDecimal := frac != 0
```
Because truncating won't work for all values.  http://play.golang.org/p/rdJCCMf3uB

**Comment by dgnorton** [comment]
One comment.  Otherwise +1

**Comment by jwilder** [comment]
@dgnorton Thanks!  Updated and will merge on green.
