### PR TITLE
Graphite logs in seconds, not milliseconds

### LINKED ISSUE #2077: Graphite plugin decodes Unix time to incorrect local time value
Hi,
Using master branch and Graphite plugin enabled I get the following:
```
root@grid-monitoring:~# echo "example.foo.bar 3 `date +%s`"|nc localhost 2003

root@grid-monitoring:~# curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=graphite" --data-urlencode "q=SELECT * FROM example.foo.bar"
{
    "results": [
        {
            "series": [
                {
                    "name": "example.foo.bar",
                    "columns": [
                        "time",
                        "example.foo.bar"
                    ],
                    "values": [
                        [
                            "1970-01-17T12:28:44.244Z",
                            3
                        ]
                    ]
                }
            ]
        }
    ]
}
```
The same incorrect time values I get using [collectl](http://collectl.sourceforge.net/) with InfluxDB.

I'm quite new to golang and thus I presume there is just some typo in [graphite.go#L97](https://github.com/influxdb/influxdb/blob/master/graphite/graphite.go#L97) in function parameters to [time.Unix](http://golang.org/pkg/time/#Time.Unix) where seconds are set to zero.
Is it justified to change the line to:
`timestamp := time.Unix(unixTime, 0)`
?

### PR DESCRIPTION
**Pull request by corylanou**
Was incorrectly decoding as milliseconds, should be seconds.

Fixes #2077.

### CODE REVIEW

**Comment by otoolep** [comment]
+1. I don't know is Graphite ever sends fractional timestamps, but this should work if the timestamps are always integers. I guess we can revisit if it does.

File: graphite/graphite.go [hunk 1]
```diff
@@ -94,7 +94,7 @@ func (p *Parser) Parse(line string) (influxdb.Point, error) {
 		return influxdb.Point{}, err
 	}
 
-	timestamp := time.Unix(0, unixTime*int64(time.Millisecond))
+	timestamp := time.Unix(unixTime, 0)
```
Comment (jwilder) [inline graphite/graphite.go]: Just tested sending fractional seconds to a real graphite instance and it does accept them.  Don't think this is fully correct as is.  Probably need to use `strconv.ParseFloat` instead.

Comment (jwilder) [inline graphite/graphite.go]: See https://github.com/graphite-project/carbon/blob/master/lib/carbon/protocols.py#L77

Comment (otoolep) [inline graphite/graphite.go]: Yeah, I had this vague memory of seeing Graphite data with fractional timestamps. Thanks for looking into it @jwilder

**Comment by corylanou** [comment]
So the way graphite apparently works is depending on how you set a retention policy, it can either average your points, or use the last point, for the "second" you wrote data.  However, it can accept fractional seconds.

So, to make our endpoint compatible, I'm accepting fractional time, and storing it raw (not averaging or taking the last).  So, our behavior isn't exactly as graphite will behave, but I believe this is the correct behavior so that we don't lose data.

@otoolep @jwilder

File: graphite/graphite.go [hunk 2]
```diff
@@ -89,12 +89,21 @@ func (p *Parser) Parse(line string) (influxdb.Point, error) {
 	fieldValues[name] = v
 
 	// Parse timestamp.
-	unixTime, err := strconv.ParseInt(fields[2], 10, 64)
+	//unixTime, err := strconv.ParseInt(fields[2], 10, 64)
```
Comment (otoolep) [inline graphite/graphite.go]: Can you actually remove this line?

File: graphite/graphite.go [hunk 3]
```diff
@@ -89,12 +89,21 @@ func (p *Parser) Parse(line string) (influxdb.Point, error) {
...
+	unixTime, err := strconv.ParseFloat(fields[2], 64)
 	if err != nil {
 		return influxdb.Point{}, err
 	}
 
-	timestamp := time.Unix(0, unixTime*int64(time.Millisecond))
+	var timestamp time.Time
+	// Check if we have fractional seconds
+	if float64(int64(unixTime)) != unixTime {
```
Comment (otoolep) [inline graphite/graphite.go]: You want to use `math.Floor()`. You also don't need the `if` block. Just do:
```
timestamp = time.Unix(int64(unixTime),  int64((unixTime-math.Floor(unixTime)) * float64(time.Second)))
```
because if we don't have fractional seconds, `int64((unixTime-math.Floor(unixTime)) * float64(time.Second))` will be zero anyway.

**Comment by otoolep** [comment]
Change makes sense, but I do have some feedback. +1 from once those changes are in place.

**Comment by corylanou** [comment]
Refactors complete based on comments.  Merging on green.
