### PR TITLE
handle aggregations with 0 intervals

### LINKED ISSUE #2487: Query for exact timestamp causes panic
This query works:
`SELECT count(msgCount) FROM outbounddata WHERE providerId='1' AND time > now() - 15m`

This query causes panic: ( time = vs time > )
`SELECT count(msgCount) FROM outbounddata WHERE providerId='1' AND time = now() - 15m`

```
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x6c318d pc=0x6c318d]

goroutine 5120 [running]:
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc20bea8310, 0xc20be318c0, 0xc209290700)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:138 +0x68d
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc20be79440, 0xc20be318c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:774 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:753 +0x5a
```

Schema:
```
{
    "database": "streamDB",
    "retentionPolicy": "default",
    "points": [
        {
            "name": "outbounddata",
            "tags": {
                "providerId": "1",
                "customerId": "xyz"
               
            },
            "fields": {
                "stream":"stream1",
                           "subscription":"sdfsd1",
                           "msgCount": 1
            }
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by neonstalwart**
fixes #2487

i wondered whether or not a 0-length interval should be valid for aggregating but then i considered that if we eventually allow multiple points to be written to the same time then aggregations over 0-length intervals seem valid.

cc @toddboom

### CODE REVIEW

**Comment by toddboom** [comment]
+1

**Comment by pauldix** [comment]
The query in your test won't actually work. You can't have two data points at the same nano-second. And this query is asking for all points at the exact nano-second at `2000-01-01 00:00:05Z` which has everything after the 5 set to zero.

Zero intervals aren't actually valid for aggregate queries. The correct way to do this query would be:

```
SELECT count(value) FROM cpu WHERE time >= '2000-01-01 00:00:05' and time < '2000-01-01 00:00:06'
```

The better thing to do would be to actually return an error if the query has an aggregate function of any kind and a `time = 'some val'` They need to have an interval represented.

**Comment by toddboom** [comment]
No interest in being able to support a `count` of a single value?

**Comment by neonstalwart** [comment]
@pauldix so the query is the thing being tested (see #2487) so it needs to stay the same.  if i have the wrong expected value for the result then that should change.  however, (before i change it) it's my understanding that the intent is to eventually allow more than one point at the same exact nano-second.  when that's the case wouldn't aggregates of an exact time make sense?

**Comment by toddboom** [comment]
@pauldix i think this may also fix the non-aggregate case, fwiw

**Comment by neonstalwart** [comment]
@toddboom i'm not sure what you're referring to but i think queries without aggregates go here https://github.com/influxdb/influxdb/pull/2547/files#diff-135f9f554ea5c27580f7c818e4ae53a1R81 which means this doesn't affect them (for good or bad).  maybe i'm misunderstanding what you mean.

**Comment by toddboom** [comment]
@neonstalwart nope, i was wrong - i was testing for an old issue that i think was fixed elsewhere. you're correct.

**Comment by pauldix** [comment]
@neonstalwart we don't currently have a plan to enable points at the same nano-second within an individual series. Although I guess we could have points at the same nano-second across multiple series. So if you have a query like that but there are points with multiple tags then it would work.

At the very least I'd like to see the test in server integration updated to have two data points written in with different tags at the same nano-second and see if the result is correct (rather than a null result).

**Comment by neonstalwart** [comment]
> we don't currently have a plan to enable points at the same nano-second within an individual series

ok, i misunderstood #1920 but i see now how it's different.

test updated - waiting for green.

**Comment by neonstalwart** [comment]
this failure is unrelated to my change... can someone start it again?

**Comment by toddboom** [comment]
on it

**Comment by neonstalwart** [comment]
@pauldix how's that now?

File: cmd/influxd/server_integration_test.go [hunk 1]
```diff
@@ -674,6 +674,12 @@ func runTestsData(t *testing.T, testName string, nodes Cluster, database, retent
 			expected: `{"results":[{"series":[{"name":"cpu","columns":["time","value"],"values":[["2000-01-01T00:00:10Z",30]]}]}]}`,
 		},
 		{
+			name:     "aggregation with no interval",
+			query:    `SELECT count(value) FROM cpu WHERE time = '2000-01-01 00:00:00'`,
+			queryDb:  "%DB%",
+			expected: `{"results":[{"series":[{"name":"cpu","columns":["time","count"],"values":[["2000-01-01T00:00:00Z",2]]}]}]}`,
```
Comment (pauldix) [inline cmd/influxd/server_integration_test.go]: Where are these 2 points being written in? I assume it's in another test, but I can't find to validate that 2 is the correct number :)

Comment (neonstalwart) [inline cmd/influxd/server_integration_test.go]: the test above it writes the points and we are not resetting between tests

Comment (pauldix) [inline cmd/influxd/server_integration_test.go]: ok, makes sense. At some point we should really be resetting, but that'll have to come later

Comment (neonstalwart) [inline cmd/influxd/server_integration_test.go]: yeah, @otoolep suggested to avoid resetting when possible to keep the time of the tests down.

**Comment by pauldix** [comment]
Thanks @neonstalwart!

File: cmd/influxd/server_integration_test.go (hunk 1 above)
Comment (otoolep) [inline cmd/influxd/server_integration_test.go]: Yeah, I've seen test resets that wipe that database, and write all the same data again. Seems kinda pointless. Why not just write a set of data for a given related set of tests, and then execute the various queries. Of course, reset is there when you need it, but if we start needlessly resetting before every write, our test-run times will just grow to many minutes.

As always, it's a judgement call.
