### PR TITLE
Fix panic: runtime error: slice bounds out of range

### LINKED ISSUE #5257: [TSM] Panic during compaction
Doing a full-write load tests across two different servers, I encountered this panic:
```
panic: runtime error: slice bounds out of range

goroutine 7044023 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*indirectIndex).UnmarshalBinary(0xc84de30320, 0x7f7925d7b1fa, 0x166b6, 0x166be, 0x0, 0x0)
        /tmp/tmp.m6jFTgA2aM/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/reader.go:622 +0x532
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*mmapAccessor).init(0xc84fe81d60, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.m6jFTgA2aM/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/reader.go:858 +0x57c
github.com/influxdb/influxdb/tsdb/engine/tsm1.NewTSMReaderWithOptions(0x0, 0x0, 0xc8b7d9f040, 0x0, 0x0, 0x0)
        /tmp/tmp.m6jFTgA2aM/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/reader.go:148 +0x2d8
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*FileStore).Replace(0xc82f7440e0, 0xc829f0dd00, 0x2, 0x2, 0xc8c0cc9a10, 0x1, 0x1, 0x0, 0x0)
        /tmp/tmp.m6jFTgA2aM/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/file_store.go:367 +0x41f
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*DevEngine).compactTSMLevel.func1(0xc89597bfd0, 0xc820cd6f30, 0x1, 0x200010001, 0x0, 0xc829f0dd00, 0x2, 0x2)
        /tmp/tmp.m6jFTgA2aM/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:524 +0x79d
created by github.com/influxdb/influxdb/tsdb/engine/tsm1.(*DevEngine).compactTSMLevel
        /tmp/tmp.m6jFTgA2aM/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:535 +0x25f
```

Interestingly, it occurred on both boxes at nearly the same time - 4:47am on one and 4:52 on the other, which was ~16h into the test. Both tests were started at the same time. The first was 100k series using 5k batches, and 1m spread between timestamps (37GB written, 164 TSM files). The other was the same, but with 50k series (36GB written, 105 TSM files).

This test was performed with the following nightly build:
```
InfluxDB v0.10.0-nightly-6ccc416 (git: master 6ccc416ef0d3b0ba6d43328a2719886b66eb5e49, built 2016-01-01T05:00:47+0000)
```

### PR DESCRIPTION
**Pull request by jwilder**
The block count was an uint16 when incrementing the index location
which was an int32.  This caused the value the uint16 value to overflow
before the index location was incremented causing the wrong location
to be read on the next iteration of the loop.  This triggers the slice
out of range errors.

Added a test that recreates the panic seen in #5257 and possibly #5202 which
is older code.

Fixes #5257

### CODE REVIEW

File: tsdb/engine/tsm1/reader.go [hunk 1]
```diff
@@ -607,7 +607,7 @@ func (d *indirectIndex) UnmarshalBinary(b []byte) error {
 		i++
 
 		// 2 byte count of index entries
-		count := btou16(b[i : i+indexCountSize])
+		count := int32(btou16(b[i : i+indexCountSize]))
```
Comment (otoolep) [inline tsdb/engine/tsm1/reader.go]: I must be dense, but I don't see how this affects anything. Where exactly does a 16-bit wide count affect anything?

Comment (otoolep) [inline tsdb/engine/tsm1/reader.go]: I.e. by its nature `btou16` returns a 16-bit type. And since `count` is never incremented, how it could it overflow?

Comment (jwilder) [inline tsdb/engine/tsm1/reader.go]: You can't see where it is incremented in the diff.  It happens on here: https://github.com/influxdb/influxdb/pull/5264/files#diff-2226d419783ec10497f3bab10d1c4300R619

See this snippet for essentially what is happening: https://play.golang.org/p/zMYh_UOw4h

Comment (otoolep) [inline tsdb/engine/tsm1/reader.go]: OK, I see it now. `28` is shoved into 16 bits too.

The change is a little obscure. Would it be better to move the casting to nearer where it matters? That would probably make it clearer to the next guy.

I.e.

`i += int32(count) - 1 * int32(indexEntrySize))`

You get the idea -- deal with the overflow at the point where it matters.

**Comment by otoolep** [comment]
+1

**Comment by otoolep** [comment]
I have some feedback but I understand the fix now.

**Comment by toddboom** [comment]
@jwilder installed your branch on those nodes and confirmed that it fixed the issue. nice job! :+1:

**Comment by ivanscattergood** [comment]
@jwilder I was looking at the Changelog and I cannot see this issue (#5264): 

https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md

I am keen to test to see if this fixes #5202 & #5283

**Comment by jwilder** [comment]
@ivanscattergood I updated the change log.  It should be in the current nightlies.  If you could test it out for those two issues, that would be great.
