### PR TITLE
Fix restore functionality hangs forever

### LINKED ISSUE #4806: [0.9.5-nightly] Restore functionality hangs forever
System: `14.04.1-Ubuntu`, InfluxDB version: `0.9.5-rc2`, Single instance (no clustering)

Running the `backup` functionality I successfully got a snapshot of my data (~456M). 

Running the  `restore` functionality on another machine (with the same setup and InfluxDB version) from the command line it then hangs forever.

Here is the output:
```
unpacking: _internal/monitor/1 (4669440 bytes)
unpacking: _internal/monitor/11 (33353728 bytes)
unpacking: _internal/monitor/13 (17215488 bytes)
unpacking: _internal/monitor/3 (13205504 bytes)
unpacking: _internal/monitor/5 (18153472 bytes)
unpacking: _internal/monitor/7 (23330816 bytes)
unpacking: _internal/monitor/9 (28286976 bytes)
unpacking: meta (650 bytes)
[metastore] 2015/11/16 10:47:12 Using data dir: /root/.influxdb/meta
[metastore] 2015/11/16 10:47:12 Node at 127.0.0.1:8088 [Follower]
[metastore] 2015/11/16 10:47:13 Node at 127.0.0.1:8088 [Leader]. peers=[]
[metastore] 2015/11/16 10:47:13 Created local node: id=1, host=127.0.0.1:8088
[metastore] 2015/11/16 10:47:13 spun up monitoring for 1
[metastore] 2015/11/16 10:47:13 temporary accept error: listener closing
[metastore] 2015/11/16 10:47:13 temporary accept error: listener closing


```

### PR DESCRIPTION
**Pull request by oiooj**
if return `errors.New("listener closing")` , the `serveExecListener`function will not return in a loop，and the program will hangs at https://github.com/influxdb/influxdb/blob/master/meta/store.go#L567

Fix #4806 

Ref: https://github.com/influxdb/influxdb/blob/master/meta/store.go#L739

- [ ] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign CLA

### CODE REVIEW

**Comment by oiooj** [comment]
@pauldix @otoolep

**Comment by benbjohnson** [comment]
lgtm, although we should probably change the `Accept()` error check to look for `IsTemporary()` instead of doing string comparisons.

**Comment by otoolep** [comment]
I agree with @benbjohnson 

@oiooj -- thanks, you have found a real bug in our code. However, the better fix is as shown here:

https://github.com/influxdb/influxdb/blob/master/services/opentsdb/service.go#L211

Would you mind following this pattern and fixing the bug that way? We shouldn't have coded string-compares.

**Comment by oiooj** [comment]
sure, fixed

File: meta/store.go [hunk 1]
```diff
@@ -735,12 +734,20 @@ func (s *Store) serveExecListener() {
 		// Accept next TCP connection.
 		var err error
 		conn, err := s.ExecListener.Accept()
-		if err != nil {
-			if strings.Contains(err.Error(), "connection closed") {
+		if opErr, ok := err.(*net.OpError); ok && opErr.Temporary() {
```
Comment (otoolep) [inline meta/store.go]: This doesn't look right to me.

If the error is not temporary, then simply return. Otherwise continue in the loop. Won't that work?

Also, why are you sleeping for a second? Is that debug code?

Comment (oiooj) [inline meta/store.go]: If the error is temporary, then continue. Other error return. if error == nil , handle this Conn.
And there is no need to sleep for a second, deleted.

Comment (otoolep) [inline meta/store.go]: OK, I see where you are going.

This still seems a little bit awkward to me. Let me explain.

If the error returned from `Accept` is temporary, then keep looping. However, if the error is not temporary, then return. The way other code signals that the function should return is simply by closing the listener. That will result in a non-temporary error, so polling `closing` isn't really necessary.

Perhaps this wouldn't work with the `ExecListener` for some reason? (I have not looked at that code yet).

File: meta/store.go [hunk 2]
```diff
@@ -735,12 +734,19 @@ func (s *Store) serveExecListener() {
...
+			s.Logger.Printf("exec listener temporary accept error: %s", err)
+
+			select {
+			case <-s.closing:
```
Comment (otoolep) [inline meta/store.go]: I would expect that if a signal is sent on `closing` then the `ExecListener` would be closed from somewhere else and a non-temporary error would result. I might be wrong though.

**Comment by oiooj** [comment]
@otoolep yes, you're right. 

Now if I send a signal to shutdown the system all is normal.
```
[run] 2015/11/29 11:17:23 Signal received, initializing clean shutdown...
[run] 2015/11/29 11:17:23 Waiting for clean shutdown...
[metastore] 2015/11/29 11:17:23 RPC listener accept error and closed: network connection closed
[metastore] 2015/11/29 11:17:23 exec listener accept error and closed: network connection closed
[copier] 2015/11/29 11:17:23 copier listener closed
[cluster] 2015/11/29 11:17:23 cluster service accept error: network connection closed
[snapshot] 2015/11/29 11:17:23 snapshot listener closed
[shard-precreation] 2015/11/29 11:17:23 Precreation service terminating
[registration] 2015/11/29 11:17:23 registration service terminating
[continuous_querier] 2015/11/29 11:17:23 continuous query service terminating
[retention] 2015/11/29 11:17:23 retention policy enforcement terminating
[monitor] 2015/11/29 11:17:23 shutting down monitor system
[monitor] 2015/11/29 11:17:23 terminating storage of statistics
[handoff] 2015/11/29 11:17:23 shutting down hh service
[subscriber] 2015/11/29 11:17:23 closed service
[run] 2015/11/29 11:17:23 server shutdown completed
```

just like the cluster service.

**Comment by otoolep** [comment]
Thanks @oiooj -- +1 from me.

@benbjohnson -- would you mind re-reviewing?

**Comment by benbjohnson** [comment]
lgtm
