### PR TITLE
Prevent panic in DecodeSameTypeBlock

### LINKED ISSUE #4365: [tsm1]: panic: runtime error: index out of range
Installed the nightly 9.5 build (version 0.9.5-nightly-6f80d69), configured the tsm1 data store and started running my test program.  InfluxDB is running on a Ubuntu 13.04 VM with 4 cores, 3G ram, 20G hd.  

The test program batch inserts 15K - 30K points every 5 seconds.  Each point has 7 tag values, each tag has a cardinality of 10.  Two continuous queries are configured to run every 5m and 1h, down sampling the data into 5m and 1h buckets.  

Influx ingested the batch inserts without problems, but memory consumption continued to grow until the process memory reached about 94% of system memory.  Causal observation (using top) show memory appeared to increase as the continuous queries executed.  

When process memory reached 94% of system memory, the system became unresponsive and a 500 error was received on the batch write.  I gracefully restarted the system and influx failed to start.  Subsequent attempts to start influx all fail with the same panic.  

Below is a log snippet showing the panic.
```
2015/10/07 15:59:57 InfluxDB starting, version 0.9.5-nightly-6f80d69, branch master, commit 6f80d690dd9001cce860ce4a2f625a97d70587ed, built '2015-10-07T04:00:42+0000'
2015/10/07 15:59:57 Go version go1.5.1, GOMAXPROCS set to 4
2015/10/07 15:59:57 Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/10/07 15:59:57 Using data dir: /var/opt/influxdb/meta
[metastore] 2015/10/07 15:59:57 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2015/10/07 15:59:57 Node at localhost:8088 [Follower]
[metastore] 2015/10/07 15:59:59 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[monitor] 2015/10/07 15:59:59 Starting monitor system
[monitor] 2015/10/07 15:59:59 'build' registered for diagnostics monitoring
[monitor] 2015/10/07 15:59:59 'runtime' registered for diagnostics monitoring
[monitor] 2015/10/07 15:59:59 'network' registered for diagnostics monitoring
[monitor] 2015/10/07 15:59:59 'system' registered for diagnostics monitoring
[store] 2015/10/07 15:59:59 Using data dir: /var/opt/influxdb/data
[metastore] 2015/10/07 15:59:59 Updated node id=1 hostname=localhost:8088
[monitor] 2015/10/07 15:59:59 Storing statistics in database '_internal' retention policy '', at interval 10s
[tsm1wal] 2015/10/07 15:59:59 tsm1 WAL starting with 5242880 flush memory size threshold and 104857600 max memory size threshold
[tsm1wal] 2015/10/07 15:59:59 tsm1 WAL writing to /var/opt/influxdb/data/_internal/monitor/1
[tsm1wal] 2015/10/07 15:59:59 startup flush of /var/opt/influxdb/data/_internal/monitor/1 with 47 keys and 358 total values of 5728 bytes
[tsm1] 2015/10/07 15:59:59 rewriting index file /var/opt/influxdb/data/_internal/monitor/1/0000166.tsm1 with /var/opt/influxdb/data/_internal/monitor/1/0000168.tsm1
[tsm1] 2015/10/07 15:59:59 rewriting index file /var/opt/influxdb/data/_internal/monitor/1/0000148.tsm1 with /var/opt/influxdb/data/_internal/monitor/1/0000169.tsm1
panic: runtime error: index out of range

goroutine 60 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.Values.DecodeSameTypeBlock(0xc820361e80, 0x0, 0x0, 0x7f2b14f79e3a, 0x3c, 0x72b4a, 0x0, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/encoding.go:88 +0x284
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).DecodeAndCombine(0xc820222240, 0xc820361e80, 0x0, 0x0, 0x7f2b14f79e3a, 0x3c, 0x72b4a, 0xc8202de000, 0x0, 0x4e20, ...)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1648 +0xba
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).rewriteFile(0xc820222240, 0xc82000cfc0, 0xc82028e5a0, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1107 +0x208f
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Write.func1(0xc820222240, 0xc82028aeb0, 0xc82029ce00, 0xc82028aec0, 0xc82000cfc0, 0xc82028e5a0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:392 +0x3f
created by github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Write
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:398 +0x69b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc82028aecc)
	/root/.gvm/gos/go1.5.1/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc82028aec0)
	/root/.gvm/gos/go1.5.1/src/sync/waitgroup.go:126 +0xb4
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Write(0xc820222240, 0xc82028e030, 0xc82021b0e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:436 +0x731
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Log).flush(0xc820222120, 0x4, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:617 +0xab1
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Log).readAndFlushWAL(0xc820222120, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:326 +0x1e8
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Log).Open(0xc820222120, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:155 +0x40c
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Open(0xc820222240, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:261 +0x62a
github.com/influxdb/influxdb/tsdb.(*Shard).Open.func1(0xc8201ffa20, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/shard.go:123 +0x365
github.com/influxdb/influxdb/tsdb.(*Shard).Open(0xc8201ffa20, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/shard.go:100 +0x2d
github.com/influxdb/influxdb/tsdb.(*Store).loadShards(0xc820168140, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/store.go:301 +0xd2c
github.com/influxdb/influxdb/tsdb.(*Store).Open(0xc820168140, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/store.go:369 +0x35a
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1(0xc82016b560, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:365 +0xe08
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc82016b560, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:311 +0x2d
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc820148000, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:121 +0xe27
main.(*Main).Run(0xc8200f9f00, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/cmd/influxd/main.go:86 +0x6a1
main.main()
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0x29b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/root/.gvm/gos/go1.5.1/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/root/.gvm/gos/go1.5.1/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/root/.gvm/gos/go1.5.1/src/os/signal/signal_unix.go:28 +0x37

goroutine 34 [IO wait]:
net.runtime_pollWait(0x7f2b16001070, 0x72, 0xc82000e150)
	/root/.gvm/gos/go1.5.1/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82013e290, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.5.1/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82013e290, 0x0, 0x0)
	/root/.gvm/gos/go1.5.1/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82013e230, 0x0, 0x7f2b18e96788, 0xc820011020)
	/root/.gvm/gos/go1.5.1/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82013c068, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.5.1/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82013c068, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.5.1/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc820139100, 0x7f2b160000f0, 0xc82013c068, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x4b
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:349 +0xafb

goroutine 35 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc82013c070, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc8201954a0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/meta/store.go:2066 +0x51
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc82013e2a0)
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/net_transport.go:346 +0x79
created by github.com/hashicorp/raft.NewNetworkTransport
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/net_transport.go:138 +0x284

goroutine 36 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc8201ae000)
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/raft.go:849 +0xcce
github.com/hashicorp/raft.(*Raft).runLeader(0xc8201ae000)
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/raft.go:821 +0x936
github.com/hashicorp/raft.(*Raft).run(0xc8201ae000)
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/raft.go:602 +0xbb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/raft.go:252 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8201ae000, 0xc8201a68d0)
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 37 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc8201ae000)
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/raft.go:509 +0x10eb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/raft.go:253 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8201ae000, 0xc8201a68e0)
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 38 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc8201ae000)
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/raft.go:1636 +0x493
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/raft.go:254 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8201ae000, 0xc8201a68f0)
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.52T7DyVJmO/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 39 [select]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc820146d20)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/meta/state.go:187 +0x4f5
created by github.com/influxdb/influxdb/meta.(*localRaft).open
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/meta/state.go:177 +0x1344

goroutine 40 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc82013c078, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc820168280)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/meta/store.go:622 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/meta/store.go:239 +0x364

goroutine 41 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc82013c080, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc820168280)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/meta/store.go:726 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3b6

goroutine 7 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc82016b560, 0xc820136480)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:495 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:355 +0xc7f

goroutine 8 [select]:
github.com/influxdb/influxdb/meta.(*Store).WaitForLeader(0xc820168280, 0x6fc23ac00, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/meta/store.go:556 +0x3fc
github.com/influxdb/influxdb/monitor.(*Monitor).storeStatistics(0xc82019a000)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/monitor/service.go:341 +0x2dd
created by github.com/influxdb/influxdb/monitor.(*Monitor).Open
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/monitor/service.go:138 +0x349

goroutine 9 [runnable]:
syscall.Syscall(0x107, 0xffffffffffffff9c, 0xc820208540, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.5.1/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.unlinkat(0xffffffffffffff9c, 0xc820208500, 0x3d, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.5.1/src/syscall/zsyscall_linux_amd64.go:102 +0x8c
syscall.Unlink(0xc820208500, 0x3d, 0x0, 0x0)
	/root/.gvm/gos/go1.5.1/src/syscall/syscall_linux.go:81 +0x49
os.Remove(0xc820208500, 0x3d, 0x0, 0x0)
	/root/.gvm/gos/go1.5.1/src/os/file_unix.go:286 +0x3b
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).removeCheckpoint(0xc820222240, 0xc8201d4140, 0x37, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1770 +0x1b4
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).writeIndexAndGetDataFile(0xc820222240, 0xc8202b4018, 0x140b05f0a712c181, 0x140b0612e882cf86, 0xc8202ac000, 0x2c, 0x2c, 0xc8202c60b0, 0x2c, 0x2c, ...)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:765 +0xa62
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).rewriteFile(0xc820222240, 0xc82000d680, 0xc82028e240, 0x0, 0x0)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1149 +0xde9
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Write.func1(0xc820222240, 0xc82028aeb0, 0xc82029ce00, 0xc82028aec0, 0xc82000d680, 0xc82028e240)
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:392 +0x3f
created by github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Write
	/tmp/tmp.52T7DyVJmO/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:398 +0x69b
```

### PR DESCRIPTION
**Pull request by jwilder**
If DecodeSameTypeBlock is called on on an empty Values slice, it would
panic with an index out of bounds error.

Fixes #4365

### CODE REVIEW

**Comment by otoolep** [comment]
Are we just masking something, or calling this on an empty slice valid?

**Comment by jwilder** [comment]
There may be a higher level issue, but the code assumes there is at least 1 value which is not safe.  The test case should not panic IMO and it does without this change..

I updated the code to panic if we have no values but are passed in a block to decode.  That would definitely be broken.  Not sure why we have `DecodeSameTypeBlock` as well as `DecodeBlock`.  Seems like `DecodeSameTypeBlock` isn't really need.

**Comment by otoolep** [comment]
OK. I'm going to have to leave this for @pauldix -- he might believe it should simply never happen, and it might a clue to other issues. Simply returning a nil result might result in subtle query (I assume it's query path) errors that may be much harder to detect.

Of course, the check may simply have been forgotten, but I don't know that.

**Comment by otoolep** [comment]
Just to be clear, obviously no query should ever cause the system to panic, but since "tsm1" is experimental, it seems to me we have the time to fully investigate the issue.

**Comment by jwilder** [comment]
This is in the compaction part of the engine.

**Comment by otoolep** [comment]
OK, thanks @jwilder.

File: tsdb/engine/tsm1/tsm1.go [hunk 1]
```diff
@@ -614,7 +614,11 @@ func (e *Engine) Compact(fullCompaction bool) error {
 			for {
 				// write the values, the block or combine with previous
 				if len(previousValues) > 0 {
-					previousValues = append(previousValues, previousValues.DecodeSameTypeBlock(block)...)
+					decoded, err := DecodeBlock(block)
+					if err != nil {
+						panic(fmt.Sprintf("failure decoding block: %v", err))
```
Comment (jwilder) [inline tsdb/engine/tsm1/tsm1.go]: We could return the error here as well but a failure to decode a block is not good.

File: tsdb/engine/tsm1/tsm1.go [hunk 2]
```diff
@@ -1645,7 +1649,10 @@ func (e *Engine) readSeries() (map[string]*tsdb.Series, error) {
 // has future encoded blocks so that this method can know how much of its values can be
 // combined and output in the resulting encoded block.
 func (e *Engine) DecodeAndCombine(newValues Values, block, buf []byte, nextTime int64, hasFutureBlock bool) (Values, []byte, error) {
-	values := newValues.DecodeSameTypeBlock(block)
+	values, err := DecodeBlock(block)
+	if err != nil {
+		panic(fmt.Sprintf("failure decoding block: %v", err))
```
Comment (jwilder) [inline tsdb/engine/tsm1/tsm1.go]: Same here... could return the error, but other places in the engine panic when there is a error at the block level.

**Comment by jwilder** [comment]
@otoolep @pauldix Update to remove `DecodeSameTypeBlock`.

**Comment by otoolep** [comment]
Seems fine, though I would love to know if @pauldix thinks `Encode` should ever be called with a nil byte slice.

File: tsdb/engine/tsm1/tsm1.go (hunk 1 above)
Comment (pauldix) [inline tsdb/engine/tsm1/tsm1.go]: I'd rather fail hard for now. That way it comes up immediately

**Comment by pauldix** [comment]
Encode should never be called with a nil slice. You can see in tsm1 where it gets called there are always checks to ensure `len > 0`

File: tsdb/engine/tsm1/encoding.go [hunk 3]
```diff
@@ -70,6 +70,10 @@ func (v Values) MaxTime() int64 {
 }
 
 func (v Values) Encode(buf []byte) ([]byte, error) {
+	if len(v) == 0 {
```
Comment (otoolep) [inline tsdb/engine/tsm1/encoding.go]: This should not be necessary, according to @pauldix. Perhaps it's just for safety, up to you.

**Comment by jwilder** [comment]
Ok.  I can switch `Encode` to panic in that case as well.

File: tsdb/engine/tsm1/encoding.go (hunk 3 above)
Comment (jwilder) [inline tsdb/engine/tsm1/encoding.go]: Yes.  It should not happen based on `tsm1` engine being the caller but it's a public func so some other code could call it at some point.  Personally, I don't a func should make assumptions about how it's called or who is calling it.  I'd rather document that calling `Encode` with an empty slice will panic so it's clear how it behaves.

Comment (pauldix) [inline tsdb/engine/tsm1/encoding.go]: Agree with @jwilder, +1!

Comment (pauldix) [inline tsdb/engine/tsm1/encoding.go]: since it's a public function, a check is good

Comment (otoolep) [inline tsdb/engine/tsm1/encoding.go]: Excellent point.
