### PR TITLE
Fix growing destination buffer during WAL entry encoding

### LINKED ISSUE #5075: [0.9.6] influxdb randomly crashing with panic: runtime error: index out of range
```
2015/12/10 00:44:42 InfluxDB starting, version 0.9.6, branch 0.9.6, commit ea8bbabfb68394aab5d9f23f08e29986bc137955, built 2015-12-09T16:10:21+0000
2015/12/10 00:44:42 Go version go1.4.2, GOMAXPROCS set to 12
2015/12/10 00:44:43 Using configuration at: /config/config.toml
[metastore] 2015/12/10 00:44:43 Using data dir: /data/meta
[metastore] 2015/12/10 00:44:43 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[influx-mysql-cp.beget:8088]
[metastore] 2015/12/10 00:44:43 Node at influx-mysql-cp.beget:8088 [Follower]
[metastore] 2015/12/10 00:44:48 Node at influx-mysql-cp.beget:8088 [Leader]. peers=[influx-mysql-cp.beget:8088]
[metastore] 2015/12/10 00:44:48 Updated node id=1 hostname=influx-mysql-cp.beget:8088
[metastore] 2015/12/10 00:44:48 spun up monitoring for 1
[store] 2015/12/10 00:44:48 Using data dir: /data/db
[tsm1wal] 2015/12/10 00:44:48 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2015/12/10 00:44:48 tsm1 WAL writing to /data/wal/_internal/monitor/2
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00001.wal, size 859
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00004.wal, size 2555
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00005.wal, size 7824
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00007.wal, size 6363
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00009.wal, size 830
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00010.wal, size 831
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00011.wal, size 827
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00012.wal, size 3450
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00013.wal, size 3591
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00015.wal, size 4508
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00016.wal, size 773
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00017.wal, size 6379
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00023.wal, size 4488
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00025.wal, size 8472
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/2/_00040.wal, size 0
[tsm1wal] 2015/12/10 00:44:48 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2015/12/10 00:44:48 tsm1 WAL writing to /data/wal/_internal/monitor/3
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/3/_00001.wal, size 957
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/3/_00002.wal, size 3548
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/3/_00004.wal, size 5442
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/3/_00005.wal, size 781
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/3/_00006.wal, size 7095
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/3/_00007.wal, size 838
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/3/_00009.wal, size 3609
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/3/_00014.wal, size 7284
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/3/_00015.wal, size 1760
[cacheloader] 2015/12/10 00:44:48 reading file /data/wal/_internal/monitor/3/_00016.wal, size 0
[tsm1wal] 2015/12/10 00:44:48 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2015/12/10 00:44:48 tsm1 WAL writing to /data/wal/mysql-cp/default/1
[cacheloader] 2015/12/10 00:44:49 reading file /data/wal/mysql-cp/default/1/_00052.wal, size 2381471
[cacheloader] 2015/12/10 00:44:50 reading file /data/wal/mysql-cp/default/1/_00053.wal, size 8730030
[cacheloader] 2015/12/10 00:44:51 reading file /data/wal/mysql-cp/default/1/_00054.wal, size 0
[handoff] 2015/12/10 00:45:24 Starting hinted handoff service
[monitor] 2015/12/10 00:45:24 'hh' registered for diagnostics monitoring
[handoff] 2015/12/10 00:45:24 Using data dir: /data/hh
[subscriber] 2015/12/10 00:45:24 opened service
[monitor] 2015/12/10 00:45:24 Starting monitor system
[monitor] 2015/12/10 00:45:24 'build' registered for diagnostics monitoring
[monitor] 2015/12/10 00:45:24 'runtime' registered for diagnostics monitoring
[monitor] 2015/12/10 00:45:24 'network' registered for diagnostics monitoring
[monitor] 2015/12/10 00:45:24 'system' registered for diagnostics monitoring
[cluster] 2015/12/10 00:45:24 Starting cluster service
[shard-precreation] 2015/12/10 00:45:24 Starting precreation service with check interval of 1m0s, advance period of 1h0m0s
[snapshot] 2015/12/10 00:45:24 Starting snapshot service
[copier] 2015/12/10 00:45:24 Starting copier service
[admin] 2015/12/10 00:45:24 Starting admin service
[monitor] 2015/12/10 00:45:24 Storing statistics in database '_internal' retention policy '', at interval 50s
[admin] 2015/12/10 00:45:24 Listening on HTTP: 192.168.0.36:8083
[continuous_querier] 2015/12/10 00:45:24 Starting continuous query service
[httpd] 2015/12/10 00:45:24 Starting HTTP service
[httpd] 2015/12/10 00:45:24 Authentication enabled: false
[httpd] 2015/12/10 00:45:24 Listening on HTTP: 192.168.0.36:8086
[udp] 2015/12/10 00:45:24 Started listening on UDP: 192.168.0.36:4444
[retention] 2015/12/10 00:45:24 Starting retention policy enforcement service with check interval of 30m0s
[run] 2015/12/10 00:45:24 Listening for signals
2015/12/10 00:45:24 Sending anonymous usage statistics to m.influxdb.com
panic: runtime error: index out of range

goroutine 314 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*WriteWALEntry).Encode(0xccd5dda0f8, 0xc9ffe28000, 0x100000, 0x100000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:373 +0x1234
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*WAL).writeToLog(0xc208c49100, 0x7f0799e68b40, 0xccd5dda0f8, 0x0, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:208 +0xbb
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*WAL).WritePoints(0xc208c49100, 0xc233613080, 0x0, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:149 +0xa3
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*DevEngine).WritePoints(0xc208058960, 0xc31fdec000, 0x3d4, 0x400, 0x0, 0xcba5e16000, 0x3d4, 0x400, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:255 +0x55f
github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints(0xc208c1f340, 0xc31fdec000, 0x3d4, 0x400, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/tsdb/shard.go:263 +0x66d
github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard(0xc2080e6000, 0x1, 0xc31fdec000, 0x3d4, 0x400, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/tsdb/store.go:398 +0x14e
github.com/influxdb/influxdb/cluster.func·002(0x1, 0x1, 0xc31fdec000, 0x3d4, 0x400)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/cluster/points_writer.go:315 +0x131
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/cluster/points_writer.go:347 +0x31a

goroutine 1 [chan receive, 3 minutes]:
main.(*Main).Run(0xc208049700, 0xc20800a010, 0x1, 0x1, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/cmd/influxd/main.go:96 +0x7b3
main.main()
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0xdc

...
```

influxdb was downloaded from https://s3.amazonaws.com/influxdb/influxdb_0.9.6_x86_64.tar.gz

### PR DESCRIPTION
**Pull request by jwilder**
The test to see if the destination buffer for encoding and decoding a WAL
entry was broken and would cause a panic if there were large batches that
would overflow the buffer size.

Fixes #5075

### CODE REVIEW

File: tsdb/engine/tsm1/wal.go [hunk 1]
```diff
@@ -366,6 +366,13 @@ func (w *WriteWALEntry) Encode(dst []byte) ([]byte, error) {
 
 	for k, v := range w.Values {
 
+		// Make sure we have enough space in our buf before copying.  If not,
+		// grow the buf.
+		if len(dst[:n])+2+len(k)+len(v)*8+4 > len(dst) {
```
Comment (otoolep) [inline tsdb/engine/tsm1/wal.go]: So this change is because the buffer was insufficiently big for even the first batch, right?

File: tsdb/engine/tsm1/wal.go [hunk 2]
```diff
@@ -380,19 +387,19 @@ func (w *WriteWALEntry) Encode(dst []byte) ([]byte, error) {
...
-
 		n += copy(dst[n:], u16tob(uint16(len(k))))
 		n += copy(dst[n:], []byte(k))
 
 		n += copy(dst[n:], u32tob(uint32(len(v))))
 
 		for _, vv := range v {
+
+			// Grow our slice if needed
+			if len(dst[:n])+16 > len(dst) {
```
Comment (otoolep) [inline tsdb/engine/tsm1/wal.go]: What is this change for? Didn't you make the buffer large enough up above? So many `v` s. :-)

File: tsdb/engine/tsm1/wal.go (hunk 1 above)
Comment (otoolep) [inline tsdb/engine/tsm1/wal.go]: I would love to see these magic numbers const out.

File: tsdb/engine/tsm1/wal.go (hunk 2 above)
Comment (otoolep) [inline tsdb/engine/tsm1/wal.go]: OK, this is the key fix, not moving the other block.

**Comment by otoolep** [comment]
OK, I checked out the branch, and generally follow it now. I'd like to understand @jwilder why you moved the earlier block, but I'm merging now.

**Comment by otoolep** [comment]
I had to rebase and force-push due to CHANGELOG conflicts.

**Comment by otoolep** [comment]
Cherry-picked to 0.9.6
