### PR TITLE
Fix excessive heartbeater logging of "connection refused" on cluster node stop

### LINKED ISSUE #1896: Excessive heartbeater logging of "connection refused" on cluster node stop
Same 3 node set up as described in #1882. If I stop one of the nodes, the other two start spewing "connection refused" to the log at the rate of several per-second, which seems to me like a potential problem (tried setting raft-tracing to false in config, but that doesn't seem to help):

```
[raft]  2015/03/09 23:04:46 heartbeater: error: Get http://echo05:8086/raft/heartbeat?commitIndex=1392&leaderID=1&term=5: dial tcp 192.168.122.105:8086: connection refused
[raft]  2015/03/09 23:04:46 heartbeater: error: Get http://echo05:8086/raft/heartbeat?commitIndex=1392&leaderID=1&term=5: dial tcp 192.168.122.105:8086: connection refused
[raft]  2015/03/09 23:04:46 heartbeater: error: Get http://echo05:8086/raft/heartbeat?commitIndex=1392&leaderID=1&term=5: dial tcp 192.168.122.105:8086: connection refused
[raft]  2015/03/09 23:04:46 heartbeater: error: Get http://echo05:8086/raft/heartbeat?commitIndex=1392&leaderID=1&term=5: dial tcp 192.168.122.105:8086: connection refused
[raft]  2015/03/09 23:04:46 heartbeater: error: Get http://echo05:8086/raft/heartbeat?commitIndex=1392&leaderID=1&term=5: dial tcp 192.168.122.105:8086: connection refused
[raft]  2015/03/09 23:04:46 heartbeater: error: Get http://echo05:8086/raft/heartbeat?commitIndex=1392&leaderID=1&term=5: dial tcp 192.168.122.105:8086: connection refused
```

### PR DESCRIPTION
**Pull request by jwilder**
When a broker is down, the leader will log a heartbeat error every second until it re-joins.  This can fill up the logs fairly quickly.  This PR adds a timestamp to the raft config struct to track the last time a node had a heartbeat error.  It will only log the error once every 15s, per node, to cut down on the noise.

Fixes #1896

### CODE REVIEW

**Comment by corylanou** [comment]
+1

**Comment by otoolep** [comment]
An issue I can see with this is that we don't really know when heartbeating succeeded again. This will help us with our logs, but log messages when the states *changes* would be more helpful.

**Comment by corylanou** [comment]
Probably beyond the scope of this, but it would be nice to know when the last "successful" heartbeat was as well and log that so you you get a feel for how long it was offline.

File: raft/log.go [hunk 1]
```diff
@@ -1176,7 +1176,11 @@ func (l *Log) heartbeater(term uint64, committed chan uint64, wg *sync.WaitGroup
 		go func(n *ConfigNode) {
 			peerIndex, err := l.Transport.Heartbeat(n.URL, term, commitIndex, leaderID)
 			if err != nil {
-				l.Logger.Printf("send heartbeat: error: %s", err)
+				// log heartbeat error once every 15 seconds to avoid flooding the logs
+				if time.Now().Unix()-atomic.LoadInt64(&n.LastHeartbeatError) > 15 {
```
Comment (otoolep) [inline raft/log.go]: If we're going to hardcode this, I would go with a lower value, like 10 seconds.

Comment (otoolep) [inline raft/log.go]: Also, the number of heartbeats sent would be good. Perhaps we really need stats on the broker side, like we do for servers. That would be quite helpful, but is obviously beyond the scope.

Comment (jwilder) [inline raft/log.go]: I started w/ 10s but it still felt noisy.  I updated the PR to log the last success and the error count.  It could probably be increased to 60s now.

**Comment by jwilder** [comment]
Also, keep in mind that the current _success_ behavior is to not log anything.

File: raft/log.go [hunk 2]
```diff
@@ -1176,9 +1176,19 @@ func (l *Log) heartbeater(term uint64, committed chan uint64, wg *sync.WaitGroup
 		go func(n *ConfigNode) {
 			peerIndex, err := l.Transport.Heartbeat(n.URL, term, commitIndex, leaderID)
 			if err != nil {
-				l.Logger.Printf("send heartbeat: error: %s", err)
+				c := atomic.AddInt64(&n.HeartbeatErrorCount, 1)
+				// log heartbeat error once every 15 seconds to avoid flooding the logs
+				if time.Now().Unix()-atomic.LoadInt64(&n.LastHeartbeatError) > 15 {
```
Comment (otoolep) [inline raft/log.go]: Can you lift the magic number to the top of the file? And name it as a const?

**Comment by otoolep** [comment]
Thanks for the enhancements. The choice of 15 vs. 10 is definitely up to you, but do remove the magic number.

+1
