### PR TITLE
Read locks and data race fixes

### LINKED ISSUE #2401: Data race in shard stats
```
WARNING: DATA RACE
Read by goroutine 446:
  github.com/influxdb/influxdb.(*Stats).Walk()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/stats.go:91 +0x148
  github.com/influxdb/influxdb.funcÂ·010()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:374 +0x134
  github.com/influxdb/influxdb.funcÂ·011()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:394 +0x4f0

Previous write by goroutine 416:
  github.com/influxdb/influxdb.(*Int).Add()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/stats.go:22 +0x96
  github.com/influxdb/influxdb.(*Stats).Add()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/stats.go:57 +0x256
  github.com/influxdb/influxdb.funcÂ·054()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/shard.go:249 +0x441
  github.com/boltdb/bolt.(*DB).Update()
      /home/ubuntu/influxdb-build/src/github.com/boltdb/bolt/db.go:505 +0x12e
  github.com/influxdb/influxdb.(*Shard).writeSeries()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/shard.go:265 +0xe4
  github.com/influxdb/influxdb.(*Shard).processor()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/shard.go:313 +0x264

Goroutine 446 (running) created at:
  github.com/influxdb/influxdb.(*Server).StartSelfMonitoring()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:412 +0x2f1
  github.com/influxdb/influxdb/cmd/influxd.(*RunCommand).Open()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run.go:467 +0x3270
  github.com/influxdb/influxdb/cmd/influxd_test.createCombinedNodeCluster()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/server_integration_test.go:121 +0xeae
  github.com/influxdb/influxdb/cmd/influxd_test.TestSingleServerDiags()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/server_integration_test.go:1466 +0x3f1
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133

Goroutine 416 (running) created at:
  github.com/influxdb/influxdb.(*Shard).open()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/shard.go:127 +0x7c0
  github.com/influxdb/influxdb.(*Server).applyCreateShardGroupIfNotExists()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:1222 +0x10d1
  github.com/influxdb/influxdb.funcÂ·046()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:3447 +0x76a
  github.com/influxdb/influxdb.(*Server).processor()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:3473 +0x1b7
==================
==================
WARNING: DATA RACE
Read by goroutine 446:
  github.com/influxdb/influxdb.(*Stats).Walk()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/stats.go:91 +0x148
  github.com/influxdb/influxdb.funcÂ·010()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:374 +0x134
  github.com/influxdb/influxdb.funcÂ·011()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:394 +0x4f0

Previous write by goroutine 416:
  github.com/influxdb/influxdb.(*Int).Add()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/stats.go:22 +0x96
  github.com/influxdb/influxdb.(*Stats).Add()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/stats.go:57 +0x256
  github.com/influxdb/influxdb.(*Stats).Inc()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/stats.go:62 +0x52
  github.com/influxdb/influxdb.funcÂ·054()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/shard.go:250 +0x493
  github.com/boltdb/bolt.(*DB).Update()
      /home/ubuntu/influxdb-build/src/github.com/boltdb/bolt/db.go:505 +0x12e
  github.com/influxdb/influxdb.(*Shard).writeSeries()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/shard.go:265 +0xe4
  github.com/influxdb/influxdb.(*Shard).processor()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/shard.go:313 +0x264

Goroutine 446 (running) created at:
  github.com/influxdb/influxdb.(*Server).StartSelfMonitoring()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:412 +0x2f1
  github.com/influxdb/influxdb/cmd/influxd.(*RunCommand).Open()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/run.go:467 +0x3270
  github.com/influxdb/influxdb/cmd/influxd_test.createCombinedNodeCluster()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/server_integration_test.go:121 +0xeae
  github.com/influxdb/influxdb/cmd/influxd_test.TestSingleServerDiags()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/server_integration_test.go:1466 +0x3f1
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133

Goroutine 416 (running) created at:
  github.com/influxdb/influxdb.(*Shard).open()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/shard.go:127 +0x7c0
  github.com/influxdb/influxdb.(*Server).applyCreateShardGroupIfNotExists()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:1222 +0x10d1
  github.com/influxdb/influxdb.funcÂ·046()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:3447 +0x76a
  github.com/influxdb/influxdb.(*Server).processor()
      /home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/server.go:3473 +0x1b7
```

### PR DESCRIPTION
**Pull request by jwilder**
This PR replaces many write locks with read locks where possible.  It also fixes two data races.

Fixes #2401

### CODE REVIEW

**Comment by toddboom** [comment]
+1

lots of good stuff here! :dancer:

File: stats.go [hunk 1]
```diff
@@ -90,7 +90,9 @@ func (s *Stats) Walk(f func(string, int64)) {
 	defer s.mu.RUnlock()
 
 	for k, v := range s.m {
+		v.mu.RLock()
```
Comment (otoolep) [inline stats.go]: Ah, so here is the race, nice.

**Comment by otoolep** [comment]
+1
