### PR TITLE
Prevent NaN float values from being stored

### LINKED ISSUE #4521: TSM1: panic: decode of short block: got 1, exp 9
I am testing InfluxDB 0.9.5 Nightly with Sensu and Grafana, and have experienced a couple of InfluxDB crashes... 
I put the first one down to user error, however have now had a repeat. 

I am running: `InfluxDB shell 0.9.5-nightly-66a31ee` installed from nightly RPM on a CentOS 6.5 VM running in Parallels on OS X 10.11. 

The log file is here: https://gist.github.com/fatmcgav/b997941c053a0f155160

Let me know if you need any further info. 

Cheers
Gav

### PR DESCRIPTION
**Pull request by jwilder**
This PR has a few changes to how points are accepted and stored.

* Float `NaN` values were not supported, but were able to be written through the line protocol, collectd, and other inputs.  These values caused problem during query time as well as with the the `tsm1` engine since they were not intended to be stored.  This change returns parse error for `NaN` float values as well as prevents `NewPoint` from returning a valid point if given a `NaN` float value.  The `tsm1` float encoding will now also return an error if a `NaN` value is attempted to be encoded.
* The change to `NewPoint` returning an error propagated up to the client packages which will require upgrades to users that are not controlling the version of the client that they are using.  They will need to handle the error and determine the best thing to do with points that can't be stored.
* Since many clients already assume `NaN` can be stored, the inputs have been updated to drop and log (when appropriate) points with invalid field values.  Graphite, UDP, Collectd, and OpenTSDB inputs already dropped points so this change makes the behavior consistent across all inputs.
* HTTP line protocol handler will now write all successfully parsed points instead of failing the entire batch if one failed.  When some points fail to parse and the remaining are written successfully, the endpoint returns a `partial write` error with the failed lines in the response.  This makes the behavior more consistent with the other inputs.
* Since `NaN` values cannot be parsed correctly now, TSM WAL entries will fail to parse and the WAL will abort startup.  TSM data will need to be removed, but we'll log the point data that failed to parse to help with troubleshooting.

Fixes #4521 #4513

### CODE REVIEW

**Comment by beckettsean** [comment]
Thanks, this is a great fix, @jwilder.

Regarding "HTTP line protocol handler will now write all successfully parsed points instead of failing the entire batch if one failed. When some points fail to parse and the remaining are written successfully, the endpoint returns a partial write error with the failed lines in the response." this sounds like a global change to the system, yes? We need to update the docs to reflect this, I believe.

**Comment by jwilder** [comment]
@beckettsean  For the HTTP line protocol handler, previously you would get an error and not points written.  With this change you would still get an error, but part of you batch would be written.  We already return this error in some cluster failure scenarios (e.g. replication of 3 but only 1 succeeded would return a partial write error depending on the write consistency level).

File: cluster/rpc.go [hunk 1]
```diff
@@ -113,9 +113,13 @@ type WritePointsRequest struct {
 
 // AddPoint adds a point to the WritePointRequest with field key 'value'
 func (w *WritePointsRequest) AddPoint(name string, value interface{}, timestamp time.Time, tags map[string]string) {
-	w.Points = append(w.Points, models.NewPoint(
+	pt, err := models.NewPoint(
 		name, tags, map[string]interface{}{"value": value}, timestamp,
-	))
+	)
+	if err != nil {
```
Comment (otoolep) [inline cluster/rpc.go]: Did you consider changing the return value of this function to support sending back an error?

File: cluster/rpc.go [hunk 2]
```diff
@@ -139,9 +143,13 @@ func (w *WriteShardRequest) Points() []models.Point { return w.unmarshalPoints()
 
 // AddPoint adds a new time series point
 func (w *WriteShardRequest) AddPoint(name string, value interface{}, timestamp time.Time, tags map[string]string) {
-	w.AddPoints([]models.Point{models.NewPoint(
+	pt, err := models.NewPoint(
 		name, tags, map[string]interface{}{"value": value}, timestamp,
-	)})
+	)
+	if err != nil {
```
Comment (otoolep) [inline cluster/rpc.go]: Ditto.

**Comment by pauldix** [comment]
@jwilder does the update break the client? Possible to just do it on the v2 client?

File: tsdb/engine/tsm1/float.go [hunk 3]
```diff
@@ -52,20 +54,25 @@ func NewFloatEncoder() *FloatEncoder {
...
-func (s *FloatEncoder) Bytes() []byte {
-	return append([]byte{floatCompressedGorilla << 4}, s.buf.Bytes()...)
+func (s *FloatEncoder) Bytes() ([]byte, error) {
+	return append([]byte{floatCompressedGorilla << 4}, s.buf.Bytes()...), s.err
 }
 
 func (s *FloatEncoder) Finish() {
 	if !s.finished {
 		// write an end-of-stream record
+		s.finished = true
```
Comment (otoolep) [inline tsdb/engine/tsm1/float.go]: Why this change? Did it matter?

File: tsdb/engine/tsm1/float_test.go [hunk 4]
```diff
@@ -176,6 +185,21 @@ func TestFloatEncoder_Roundtrip(t *testing.T) {
 	}
 }
 
+func TestFloatEncoder_Roundtrip_NaN(t *testing.T) {
+
```
Comment (otoolep) [inline tsdb/engine/tsm1/float_test.go]: Nit: line looks superfluous.

**Comment by otoolep** [comment]
All generally makes sense, some minor feedback and questions. +1 from me.

**Comment by jwilder** [comment]
@pauldix Should not affect the current client.  The only change is https://github.com/influxdb/influxdb/pull/4587/files#diff-12d7ec39292af18c588a073414f3e853R477 which would return a commented out point with an error message as the comment.  That will parse on the server and be ignored.  I didn't want to change the signature or panic since either of those would break existing clients.

File: cluster/rpc.go (hunk 1 above)
Comment (jwilder) [inline cluster/rpc.go]: No.  I didn't.  This func is only called in the tests.

File: cluster/rpc.go (hunk 2 above)
Comment (jwilder) [inline cluster/rpc.go]: No.  Only called in tests.

File: tsdb/engine/tsm1/float.go (hunk 3 above)
Comment (jwilder) [inline tsdb/engine/tsm1/float.go]: Yes.  The `Finish` call writes a `NaN` as sentinel value using `Push`.  I need to mark the stream as finished so I could allow the `NaN` value to be written via `Push`.  See https://github.com/influxdb/influxdb/pull/4587/files#diff-4fcee93b376ee05d583de8af541239b8R71

**Comment by jwilder** [comment]
The v2 client will have a compile breakage when updating as they will need to handle the error returned by `NewPoint` now.

**Comment by pauldix** [comment]
@jwilder sounds good, +1

**Comment by Issif** [comment]
Wonderful !!

I will try this tomorrow with next nighlty.

Thanks a lot guys !
