### PR TITLE
Fix deadlock in metastore

### LINKED ISSUE #3607: [0.9.3-rc2] Unable to query influxdb
Hi,

We are doing feasibility testing.

We inserted 35 million records in one of the measurements. But now influx is not responding when we query the table.

Can someone please suggest what can be done?

Shilpi

### PR DESCRIPTION
**Pull request by jwilder**
The interaction of continuous query service, the meta-store loading
and initializing raft state, and syncing node info could cause a
deadlock in some instances.  There was an extra read-lock taken by isLeader()
when it already had a read-lock.  Removing this extra lock fixes the startup
deadlock.

Fixes #3607

### CODE REVIEW

File: meta/state.go [hunk 1]
```diff
@@ -334,8 +334,6 @@ func (r *localRaft) leader() string {
 }
 
 func (r *localRaft) isLeader() bool {
-	r.store.mu.RLock()
```
Comment (jwilder) [inline meta/state.go]: This lock is already take but the public `IsLeader` func.

**Comment by otoolep** [comment]
`isLeader()` is also called from `exec()`. You've considered that too? I just want to be sure.

If so, +1.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/blob/master/meta/store.go#L1485

**Comment by jwilder** [comment]
Yes.  `r.raft` is created when the store opens and is only updated when the store closes.  The `r.raft.State()` func is thread safe as well.

**Comment by pauldix** [comment]
+1
