### PR TITLE
Mean and percentile function fixes

### LINKED ISSUE #2374: Two different panics during SELECT percentile
From commit 9824585a4301ac4a8a6fd92e9c6aec4103eccdcb:

When I run the query `SELECT percentile(value) FROM "random_measurement_0" WHERE time > now() - 12h GROUP BY time(5m)`, the server panics. Granted, percentile takes two arguments and this shouldn't work, but it shouldn't panic either.

```
panic: runtime error: index out of range

goroutine 2781 [running]:
github.com/influxdb/influxdb/influxql.InitializeReduceFunc(0xc2086b7680, 0x1, 0x0, 0x0)
        /Users/mr/go/src/github.com/influxdb/influxdb/influxql/functions.go:110 +0x62b
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc208721880, 0xc20845da40, 0xc208228700)
        /Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:89 +0x274
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc208788f80, 0xc20845da40)
        /Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:774 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
        /Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:753 +0x5a
```

Then when I run a more proper query like `SELECT percentile(value, 75) FROM "random_measurement_0" WHERE time > now() - 12h GROUP BY time(5m)`, I get a different panic:

```
panic: interface conversion: interface is nil, not []interface {}

goroutine 4402 [running]:
github.com/influxdb/influxdb/influxql.func·016(0xc2081c4fc0, 0xc, 0xc, 0x0, 0x0)
        /Users/mr/go/src/github.com/influxdb/influxdb/influxql/functions.go:548 +0x107
github.com/influxdb/influxdb/influxql.(*MapReduceJob).processAggregate(0xc208789730, 0xc2088827b0, 0xc20865b9e0, 0xc2087f5000, 0x91, 0x91, 0x0, 0x0)
        /Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:632 +0x33d
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc208789730, 0xc20877c9c0, 0xc208074000)
        /Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:167 +0x8bf
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc208698c40, 0xc20877c9c0)
        /Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:774 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
        /Users/mr/go/src/github.com/influxdb/influxdb/influxql/engine.go:753 +0x5a
```

### PR DESCRIPTION
**Pull request by jwilder**
This PR fixes #2374 which had two panics related to percentiles.  It also fixes a JSON marshaling exception when `NaN` is returned from a mean function.

### CODE REVIEW

**Comment by toddboom** [comment]
:+1:

File: cmd/influxd/server_integration_test.go [hunk 1]
```diff
@@ -1456,9 +1456,7 @@ func TestSingleServerDiags(t *testing.T) {
 		t.Skip(fmt.Sprintf("skipping '%s'", testName))
 	}
 	dir := tempfile()
-	defer func() {
```
Comment (otoolep) [inline cmd/influxd/server_integration_test.go]: I think `go lint` will complain about these changes. Not sure, but I think so. We don't run lint right now, so perhaps it doesn't matter.

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,9 @@
 ## v0.9.0-rc28 [unreleased]
 
+### Bugfixes
+- [#2374](https://github.com/influxdb/influxdb/issues/2374): Two different panics during SELECT percentile
```
Comment (otoolep) [inline CHANGELOG.md]: I know this is a small thing, but I am pretty sure @pauldix does not want this format. He specially told me links to PRs only a few months back. Not a big deal, but you should check with him when you get a chance.

Comment (pauldix) [inline CHANGELOG.md]: Link to PR is preferable, but either works. If the PR mentions the issue then they'll be linked together either way.
