### PR TITLE
fix #2337: panic if tag key isn't double quoted

### LINKED ISSUE #2337: panic when tag key isn't double quoted but should be
The following query causes a panic because the expression is parsed as `data MINUS center = 'foo'` if the user forgets to double quote `"data-center"`.  It should return an error when it sees an invalid operation while processing the query.

```sql
SHOW SERIES WHERE data-center = 'foo'`
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4db811]

goroutine 9631 [running]:
github.com/influxdb/influxdb.(*Measurement).idsForExpr(0xc20805c5a0, 0xc208094fc0, 0x0, 0x0, 0x0, 0x422e49, 0x0, 0x0)
	/home/dgnorton/go/src/github.com/influxdb/influxdb/database.go:371 +0xbb1
github.com/influxdb/influxdb.(*Measurement).walkWhereForSeriesIds(0xc20805c5a0, 0x7fe4fed5ff18, 0xc208094fc0, 0xc208095080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/dgnorton/go/src/github.com/influxdb/influxdb/database.go:436 +0xd48
github.com/influxdb/influxdb.(*Server).executeShowSeriesStatement(0xc208030200, 0xc208034a00, 0xc20803482e, 0x3, 0x0, 0x0)
	/home/dgnorton/go/src/github.com/influxdb/influxdb/server.go:2549 +0x450
github.com/influxdb/influxdb.func·039()
	/home/dgnorton/go/src/github.com/influxdb/influxdb/server.go:2177 +0x13ad
created by github.com/influxdb/influxdb.(*Server).ExecuteQuery
	/home/dgnorton/go/src/github.com/influxdb/influxdb/server.go:2233 +0x314
```

### PR DESCRIPTION
**Pull request by dgnorton**
The main part of the fix is near the top of `Measurement.idsForExpr` in `database.go`.  It needed to make sure that one side of the binary expression is a `VarRef`.

### CODE REVIEW

**Comment by otoolep** [comment]
Rebase?

**Comment by dgnorton** [comment]
@otoolep done

File: database.go [hunk 1]
```diff
@@ -281,15 +281,19 @@ func (m *Measurement) seriesByTags(tags map[string]string) *Series {
...
 	seriesIdsToExpr := make(map[uint64]influxql.Expr)
 	if stmt.Condition == nil || stmt.OnlyTimeDimensions() {
 		for _, id := range m.seriesIDs {
 			seriesIdsToExpr[id] = nil
 		}
-		return seriesIdsToExpr
+		return seriesIdsToExpr, nil
+	}
+	ids, _, _, err := m.walkWhereForSeriesIds(stmt.Condition, seriesIdsToExpr)
+
```
Comment (otoolep) [inline database.go]: Style: remove this blank line?

**Comment by otoolep** [comment]
+1
