### PR TITLE
Fix panics when stopping server

### LINKED ISSUE #3848: [0.9.3-rc3] restart influxdb causing panic
influxdb 0.9.3rc3
centos 7.1
sometime influxdb stop write the point,and I restart the influxdb 
restart influxdb with high load causing panic
```
[run] 2015/08/26 12:57:48 Signal received, initializing clean shutdown...
[run] 2015/08/26 12:57:48 Waiting for clean shutdown...
[snapshot] 2015/08/26 12:57:48 snapshot listener closed
[tcp] 2015/08/26 12:57:48 cluster service accept error: network connection closed
[http] 2015/08/26 12:57:48 172.17.0.30 - root [26/Aug/2015:12:57:48 +0800] POST /write?db=metrics&p=%5BREDACTED%5D&precision=s&u=root HTTP/1.1 204 0 - Ruby ff6ba6dc-4bae-11e5-a2ea-000000000000 9.527186ms
[shard-precreation] 2015/08/26 12:57:48 Precreation service terminating
panic: assignment to entry in nil map

goroutine 662224 [running]:
github.com/influxdb/influxdb/tsdb.(*Store).CreateShard(0xc2080341a0, 0xc2441cfd8f, 0x7, 0xc20f810370, 0x7, 0x1, 0x0, 0x0)
        /home/philip/build2/src/github.com/influxdb/influxdb/tsdb/store.go:90 +0x727
github.com/influxdb/influxdb/cluster.func·002(0x1, 0x1, 0xc234d5c000, 0x6a, 0x80)
        /home/philip/build2/src/github.com/influxdb/influxdb/cluster/points_writer.go:245 +0x1c4
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
        /home/philip/build2/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x30b

goroutine 1 [select]:
main.(*Main).Run(0xc20806bb00, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /home/philip/build2/src/github.com/influxdb/influxdb/cmd/influxd/main.go:101 +0xe06
main.main()
        /home/philip/build2/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xdc
```

### PR DESCRIPTION
**Pull request by jwilder**
Two different panics could occur if in-flight writes or queries were running on the server when the server started to shutdown.  The problem was that lower level services were closed before the higher level ones were.  The cluster service was also not waiting for connections to complete before returning from `Close`.

Fixes #3848 #3881

### CODE REVIEW

File: cluster/service.go [hunk 1]
```diff
@@ -108,7 +108,7 @@ func (s *Service) Close() error {
 
 	// Shut down all handlers.
 	close(s.closing)
-	// s.wg.Wait() // FIXME(benbjohnson)
```
Comment (otoolep) [inline cluster/service.go]: Fixin' it now @benbjohnson  :-)

File: cmd/influxd/run/server.go [hunk 2]
```diff
@@ -381,23 +381,32 @@ func (s *Server) Open() error {
...
 	stopProfile()
 
+	// Close the listener first to stop any new connections
 	if s.Listener != nil {
 		s.Listener.Close()
 	}
-	if s.MetaStore != nil {
-		s.MetaStore.Close()
+
+	// Close services to any inflight requests can be stopped
```
Comment (otoolep) [inline cmd/influxd/run/server.go]: This comment isn't quite clear to me. Is a word missing?

**Comment by otoolep** [comment]
+1, small nit.

File: cluster/service.go (hunk 1 above)
Comment (benbjohnson) [inline cluster/service.go]: :)
