### PR TITLE
Fix panic when querying against not-fully replicated shards

### LINKED ISSUE #3574: [ 0.9.3-nightly-be792b9] Querying data node causes panic
```
[http] 2015/08/06 17:06:37 ::1 - - [06/Aug/2015:17:06:37 +0800] GET /query?q=SELECT+max+FROM+%22Requests%22+&db=throne HTTP/1.1 200 210 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0 712beabc-3c1a-11e5-80ca-000000000000 1.365744ms
panic: interface conversion: interface is float64, not map[string]interface {}

goroutine 408 [running]:
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc208504000, 0xc2083ba000, 0xa, 0x2710, 0x0)
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:758 +0xc63
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc208504000)
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:693 +0xba
github.com/influxdb/influxdb/tsdb.(*RawExecutor).execute(0xc208560330, 0xc20806a9c0)
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:149 +0x2d7
created by github.com/influxdb/influxdb/tsdb.(*RawExecutor).Execute
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:93 +0x5a
```

### PR DESCRIPTION
**Pull request by jwilder**
The TSDBStore was returning a nil mapper if the shard did not exist.  The caller always
assumed the mapper would not be nil causing a panic.  Instead, have the mapper skip the mapping
phase if it's shard reference is nil.  This fixes queries against data-only nodes and against
shards that are not fully replicated in the cluster.

Fixes #3574

### CODE REVIEW

File: tsdb/mapper.go [hunk 1]
```diff
@@ -88,6 +88,12 @@ func (lm *SelectMapper) Open() error {
 		return lm.remote.Open()
 	}
 
+	// This can happen when a shard has been assigned to this node but we have not
+	// written to it so it may not exist yet.
+	if lm.shard == nil {
+		return nil
+	}
+
```
Comment (dgnorton) [inline tsdb/mapper.go]: Probably need to add the same check here:  https://github.com/influxdb/influxdb/blob/master/tsdb/show_measurements.go#L144

**Comment by dgnorton** [comment]
Can you add a test for it?

File: tsdb/store.go [hunk 2]
```diff
@@ -305,10 +305,6 @@ func (s *Store) WriteToShard(shardID uint64, points []Point) error {
 
 func (s *Store) CreateMapper(shardID uint64, stmt influxql.Statement, chunkSize int) (Mapper, error) {
 	shard := s.Shard(shardID)
-	if shard == nil {
```
Comment (otoolep) [inline tsdb/store.go]: I don't follow (without digging into all the code). Why didn't this catch it?

File: tsdb/mapper.go (hunk 1 above)
Comment (jwilder) [inline tsdb/mapper.go]: Updated.

File: tsdb/store.go (hunk 2 above)
Comment (jwilder) [inline tsdb/store.go]: This issue is that `CreateMapper` returns `nil` which causes a panic in here: https://github.com/influxdb/influxdb/pull/3906/files#diff-06abda922c6e558f8a9fe56e04b7ed5eL94

**Comment by otoolep** [comment]
+1
