### PR TITLE
Wire up admin privilege grant and revoke (#2). Fixes #2872

### LINKED ISSUE #2872: Granting all privileges to a users doesn't work.
The following commands:
```sql
CREATE USER jdoe WITH PASSWORD '1337'
grant all priviledges to jdoe
SHOW USERS
```

Should result in:

```json
{"results":[{"series":[{"columns":["user","admin"],"values":[["jdoe",true]]}]}]}
```

But results in:

```json
{"results":[{"series":[{"columns":["user","admin"],"values":[["jdoe",false]]}]}]}
```

Please see the skipped test in `/cmd/influxed/run/server_test.go` named `TestServer_UserCommands`, table test: `show users, existing user as admin`

### PR DESCRIPTION
**Pull request by gunnaraasen**
This is an alternative to #3233 for setting the admin privilege on an existing user.

There does not seem to be a clean way to set/unset the admin privilege flag without making wider reaching changes to the way user privileges are stored. `influxql.Privilege` is used for per database privilege settings, e.g. `map[string]Privilege` so extending it with `influxql.AdminPrivilege` and `influxql.NoAdminPrivilege` to set an admin flag felt off.

With this change, the admin privilege is set when a `setPrivilege` is executed with `influxql.AllPrivileges` and no database name.

### CODE REVIEW

**Comment by otoolep** [comment]
I think the CHANGELOG needs updating too, right?

**Comment by gunnaraasen** [comment]
@otoolep thanks for the reminder. `CHANGELOG` has been updated.

**Comment by gunnaraasen** [comment]
@otoolep @toddboom This is ready for review. Turns out authorization on the query endpoint was not hooked up at all so the scope of this PR grew to fixing https://github.com/influxdb/influxdb/issues/3259.

File: influxql/ast.go [hunk 1]
```diff
@@ -555,7 +592,7 @@ func (s *CreateRetentionPolicyStatement) String() string {
 
 // RequiredPrivileges returns the privilege required to execute a CreateRetentionPolicyStatement.
 func (s *CreateRetentionPolicyStatement) RequiredPrivileges() ExecutionPrivileges {
-	return ExecutionPrivileges{{Name: "", Privilege: AllPrivileges}}
+	return ExecutionPrivileges{{Admin: true, Name: "", Privilege: AllPrivileges}}
```
Comment (otoolep) [inline influxql/ast.go]: Is this correct? You need to be an admin to create an RP on a database?

**Comment by otoolep** [comment]
Makes general sense to me. You'll need to rebase.

File: influxql/ast.go (hunk 1 above)
Comment (gunnaraasen) [inline influxql/ast.go]: I made any statement that previously required `AllPrivileges` a statement that requires admin access. My assumption was that no additional privileges should be granted for `AllPrivileges` that were not already allowed by the `Read` and `Write` privileges. Therefore, all statements that were previously `AllPrivileges` now require admin privilege.

RP creation seems like something that _could_ only require the `Write` privilege, since there should be no way to delete data by creating a new RP.

Comment (beckettsean) [inline influxql/ast.go]: Seems like a good default for now. Let's make a matrix of operations and permissions and see what shakes out.

**Comment by gunnaraasen** [comment]
Rebased onto master.

**Comment by otoolep** [comment]
+1 from me.

File: influxql/ast.go (hunk 1 above)
Comment (beckettsean) [inline influxql/ast.go]: Here's a proposal for permissions by GRANT type per opertation: https://docs.google.com/a/errplane.com/spreadsheets/d/1V1acjK8PS8QCQ3MagsvIMhT3giy8dJArzBOVanl_Vz0/edit?usp=sharing

**Comment by toddboom** [comment]
+1
