### PR TITLE
fix #3102: add authentication cache

### LINKED ISSUE #3102: InfluxDB 0.9 behind ELB results in 503s
We just upgraded from InfluxDB 0.8 to 0.9 and are now seeing many `503 Service Unavailable: Back-end server is at capacity` from AWS load balancers.

Beneath is a graph from CloudWatch. 0.9 was deployed around 08:00:

image

CPU load on InfluxDB instance is higher:

image

The health check is working. My guess is that it has to do with instances refusing socket connections.

The 503s happen both for writes and reads. We use Grafana for monitoring. When Grafana makes a batch of requests to update graphs, usually one or two requests are OK and the rest fails with 503s.

Is this a bug or should we simply avoid using ELB? We use it primarily because of Route53's aliasing and for SSL termination.

### PR DESCRIPTION
**Pull request by dgnorton**

### CODE REVIEW

File: influxql/parser.go [hunk 1]
```diff
@@ -94,7 +94,7 @@ func (p *Parser) ParseStatement() (Statement, error) {
 	case ALTER:
 		return p.parseAlterStatement()
 	case SET:
-		return p.parseSetStatement()
```
Comment (otoolep) [inline influxql/parser.go]: Is this because the only use of `SET` in our system is for setting a password?

Comment (dgnorton) [inline influxql/parser.go]: I changed the name of the function to match the pattern we use for all the other `parse...` functions.

**Comment by otoolep** [comment]
+1, makes sense to me. We'll want this cherry-picked to the 0.9.1 branch too.

If there is already a test for altering and dropping a user, and ensuring he or she can't still authenticate (to ensure cache is cleared), we should be good.

**Comment by pauldix** [comment]
+1

File: meta/store.go [hunk 2]
```diff
@@ -980,11 +984,18 @@ func (s *Store) Authenticate(username, password string) (ui *UserInfo, err error
 			return ErrUserNotFound
 		}
 
+		// Check the local auth cache first.
+		if p, ok := s.authCache[username]; ok && p == password {
```
Comment (pauldix) [inline meta/store.go]: should change this. if it's `ok` but `p != password` we should return an authentication error rather than doing the bcrypt. Means that someone could easily DDOS an InfluxDB server with bad auth info

File: meta/store.go [hunk 3]
```diff
@@ -96,6 +96,9 @@ type Store struct {
 	// The amount of time without an apply before sending a heartbeat.
 	CommitTimeout time.Duration
 
+	// Authentication cache.
+	authCache map[string]string
```
Comment (otoolep) [inline meta/store.go]: Technically speaking, I think this also needs synchronization. The code which checks the cache could run in a different goroutine than that which process `DROP

**Comment by otoolep** [comment]
+1, thanks for the tests.

I presume you will cherry-pick this over to the 0.9.1 branch.

File: meta/store.go [hunk 4]
```diff
@@ -1301,6 +1326,27 @@ func (s *Store) sync(index uint64, timeout time.Duration) error {
...
+// BcryptCost is the cost associated with generating password with Bcrypt.
+// This setting is lowered during testing to improve test suite performance.
+var BcryptCost = 10
+
+// HashPasswordFn represnets a password hashing function.
+type HashPasswordFn func(password string) ([]byte, error)
+
+// GetHashPasswordFn returns the current password hashing function.
+func (s *Store) GetHashPasswordFn() HashPasswordFn {
+	s.mu.Lock()
```
Comment (jwilder) [inline meta/store.go]: Could probably use a read-lock here.

File: meta/store.go [hunk 5]
```diff
@@ -994,11 +1008,22 @@ func (s *Store) Authenticate(username, password string) (ui *UserInfo, err error
 			return ErrUserNotFound
 		}
 
+		// Check the local auth cache first.
+		if p, ok := s.authCache[username]; ok {
```
Comment (jwilder) [inline meta/store.go]: Does `s.read` run this func under a lock?  `s.authCache` needs a mutex around it I think.

File: meta/store.go [hunk 6]
```diff
@@ -994,11 +1008,28 @@ func (s *Store) Authenticate(username, password string) (ui *UserInfo, err error
 			return ErrUserNotFound
 		}
 
+		// Check the local auth cache first.
+		s.mu.RLock()
+		p, ok := s.authCache[username]
+		s.mu.RUnlock()
```
Comment (otoolep) [inline meta/store.go]: Is there a chance a "alter user" command could come in after the "runlock" bt before the "lock" below, which would delete the entry from the cache, but the the code below would shove the invalid cached value back in? If so, I think the locking needs to be of much wider scope. Alternatively you could double check that the entry exists in the cache before setting the updated cached value.

Comment (otoolep) [inline meta/store.go]: If you go the latter path, I think you have to redo the checks under write lock, kinda like expvar does:

https://golang.org/src/expvar/expvar.go?s=2966:3008#L144

Comment (jwilder) [inline meta/store.go]: Not sure either of these options will work.  If the password was altered, then the value we'd be adding in the cache is still the old one because we read it before the update.  The user would not be in the cache at this point.  Even it was, we'd still be setting the wrong value again.

**Comment by otoolep** [comment]
+1, as long as the calls to `delete` take place holding the same RWLock.

**Comment by jwilder** [comment]
Takes them here: https://github.com/influxdb/influxdb/blob/master/meta/store.go#L1315

**Comment by otoolep** [comment]
Cherry-picked to 0.9.1
