### PR TITLE
Fix group by time intervals

### LINKED ISSUE #3926: [0.9.3] First or last value of `GROUP BY time(x)` is often null
For some reason the `GROUP BY time(x)` queries always return the first value as null. (even if data is available at that time). It also does the same for larger interval.

```sh
# Setup
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
curl -G http://localhost:8086/query --data-urlencode "q=CREATE RETENTION POLICY myrp ON mydb DURATION 365d REPLICATION 1 DEFAULT"

# Write lots of data
curl -X POST "http://localhost:8086/write?db=mydb" --data-binary "cpu,region=useast,host=server_1,service=redis value=61"

# The query
curl -G http://localhost:8086/query --data-urlencode "db=mydb" --data-urlencode "q=SELECT MEAN(value) FROM cpu WHERE time > now() - 5s GROUP BY time(5s)"
```

Example response:
```json
{"results":[{"series":[{"name":"cpu","columns":["time","mean"],"values":[["2015-09-01T14:05:10Z",null],["2015-09-01T14:05:15Z",61]]}]}]}
```

### PR DESCRIPTION
**Pull request by corylanou**
We were not properly setting seek/max bounds on cursors of `partial` buckets at the beginning and end of a tmax/tmin bucket.

The issue is best illustrated by looking at the added tests.

fixes #3926

### CODE REVIEW

File: tsdb/query_executor.go [hunk 1]
```diff
@@ -211,11 +211,14 @@ func (q *QueryExecutor) ExecuteQuery(query *influxql.Query, database string, chu
 func (q *QueryExecutor) PlanSelect(stmt *influxql.SelectStatement, chunkSize int) (Executor, error) {
 	shards := map[uint64]meta.ShardInfo{} // Shards requiring mappers.
 
+	// It is important to "stamp" this time so that everywhere we evaluate `now()` in the statement is EXACTLY the same `now`
+	now := time.Now().UTC()
```
Comment (corylanou) [inline tsdb/query_executor.go]: This change wasn't required, but it made sense that any time we use `now` it's the exact `now` everywhere.

File: tsdb/mapper.go [hunk 2]
```diff
@@ -768,7 +773,7 @@ func (tsc *tagSetCursor) Next(tmin, tmax int64, selectFields, whereFields []stri
 		p := heap.Pop(tsc.pointHeap).(*pointHeapItem)
 
 		// We're done if the point is outside the query's time range [tmin:tmax).
-		if p.timestamp != tmin && (tmin > p.timestamp || p.timestamp >= tmax) {
+		if p.timestamp != tmin && (p.timestamp < tmin || p.timestamp >= tmax) {
```
Comment (corylanou) [inline tsdb/mapper.go]: swapped order of comparison for readability

File: tsdb/mapper.go [hunk 3]
```diff
@@ -440,8 +445,8 @@ func (lm *SelectMapper) nextChunkAgg() (interface{}, error) {
 				heap.Push(tsc.pointHeap, p)
 			}
 			// Wrap the tagset cursor so it implements the mapping functions interface.
-			nextf := func() (time int64, value interface{}) {
-				k, v := tsc.Next(qmin, tmax, []string{lm.fieldNames[i]}, lm.whereFields)
+			nextf := func() (_ int64, value interface{}) {
```
Comment (corylanou) [inline tsdb/mapper.go]: we never reference this value so we should explicitly ignore it.

File: tsdb/mapper.go [hunk 4]
```diff
@@ -428,7 +433,7 @@ func (lm *SelectMapper) nextChunkAgg() (interface{}, error) {
 			// changes to the mapper functions, which can come later.
 			// Prime the buffers.
 			for i := 0; i < len(tsc.cursors); i++ {
-				k, v := tsc.cursors[i].SeekTo(tmin)
+				k, v := tsc.cursors[i].SeekTo(qmin)
```
Comment (otoolep) [inline tsdb/mapper.go]: This seems like a different issue you're fixing here, right?

File: tsdb/mapper.go (hunk 2 above)
Comment (otoolep) [inline tsdb/mapper.go]: Cosmetic, right?

Comment (corylanou) [inline tsdb/mapper.go]: correct

File: tsdb/mapper.go (hunk 4 above)
Comment (corylanou) [inline tsdb/mapper.go]: no, this was indeed part of the bug.  Before it would seek to `tmin`, and it could find values that were `before` the time range asked for, so it would exit the cursor prematurely if that happened.

**Comment by otoolep** [comment]
Some important fixes, nice, +1.
