### PR TITLE
Fix aggregate output across the cluster

### LINKED ISSUE #4801: 0.9.5-rc2: Cluster : get wrong result when add new node and query through this node with aggregation function.
reproduce steps:

1、start a single node and insert some data
2、add new node to join the first node(in my case, i joined 2 nodes)
3、execute query on the old node with agg func , e.g. select max(value) from xxx groupby time(1m)
4、execute query on new node with the same sql above

you will see the results showed from two nodes are different,  result from old node is correct which show a lot of rows according to grouyby interval,  result from new node, however,  is just a single line.

we've already fixed and will send a PR asap.

### PR DESCRIPTION
**Pull request by li-ang**
fix #4801
Ignoring time for aggregate output would lead to get wrong result when influxdb is working in cluster.
So, when the time of aggregate output isn't equal to zore, we shouldn't ignore time and return it in result.

- [x] CHANGELOG.md updated
- [x] Rebased/mergable
- [x] Tests pass
- [x] Sign [CLA](http://influxdb.com/community/cla.html)

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @li-ang -- we'll take a look.

**Comment by otoolep** [comment]
Have you signed the CLA @li-ang ?

**Comment by li-ang** [comment]
@otoolep Yes！

**Comment by otoolep** [comment]
OK, I see that -- thanks. CLA confirmed signed.

File: cluster/shard_mapper.go [hunk 1]
```diff
@@ -230,10 +230,21 @@ func (r *RemoteMapper) NextChunk() (chunk interface{}, err error) {
 			}
 			aggValues = append(aggValues, v)
 		}
-		mo.Values = []*tsdb.MapperValue{&tsdb.MapperValue{
-			Value: aggValues,
-			Tags:  mvj[0].Tags,
-		}}
+
+		if mvj[0].Time != 0 {
```
Comment (otoolep) [inline cluster/shard_mapper.go]: I'm not really sure why it this would make a difference. Either way you end up with a `Time` field equal to 0, right?

File: cluster/shard_mapper.go [hunk 2]
```diff
@@ -230,10 +230,21 @@ func (r *RemoteMapper) NextChunk() (chunk interface{}, err error) {
...
+			mo.Values = []*tsdb.MapperValue{&tsdb.MapperValue{
+				Time:  mvj[0].Time,
+				Value: aggValues,
+				Tags:  mvj[0].Tags,
+			}}
+
+		} else {
+			mo.Values = []*tsdb.MapperValue{&tsdb.MapperValue{
```
Comment (otoolep) [inline cluster/shard_mapper.go]: The `Time` field is zero here because of the way Go works, right?

File: cluster/shard_mapper.go (hunk 1 above)
Comment (li-ang) [inline cluster/shard_mapper.go]: No, when the mvj[0].Time mayby not equal to 0 when your aggregate query setence has `where time > xxx ` subsentence.

File: cluster/shard_mapper.go (hunk 2 above)
Comment (li-ang) [inline cluster/shard_mapper.go]: Right!

File: cluster/shard_mapper.go (hunk 1 above)
Comment (otoolep) [inline cluster/shard_mapper.go]: Still don't follow you. :-(

Comment (CrazyJvm) [inline cluster/shard_mapper.go]: hi @otoolep, have you checked https://github.com/influxdb/influxdb/issues/4801 already?  let's say if you execute `select mean(value) from mem_used group by time(1m)` ,  `Time` won't be zero because every interval has its own timestamp. however if you execute `select mean(value) from mem_used` without `groupby`, then `Time` will be ignored, and the value of `Time` is 0.

Comment (otoolep) [inline cluster/shard_mapper.go]: D'oh! I see it now, the old code was *not* setting the time field -- I never looked there. You are right. Thanks @li-ang

However, wouldn't this change work just as well:

```
mo.Values = []*tsdb.MapperValue{&tsdb.MapperValue{
+    Time: mvj[0].Time,
    Value: aggValues,
    Tags: mvj[0].Tags,
}}
```

In otherwords, just set the time.

Comment (CrazyJvm) [inline cluster/shard_mapper.go]: Yes, that's right. just need add `Time`. @otoolep 

and there will be another fix very soon following this PR.

**Comment by li-ang** [comment]
Done!  @otoolep

File: cluster/shard_mapper.go [hunk 3]
```diff
@@ -231,9 +231,11 @@ func (r *RemoteMapper) NextChunk() (chunk interface{}, err error) {
 			aggValues = append(aggValues, v)
 		}
 		mo.Values = []*tsdb.MapperValue{&tsdb.MapperValue{
+			Time:  mvj[0].Time,
 			Value: aggValues,
 			Tags:  mvj[0].Tags,
 		}}
+
```
Comment (CrazyJvm) [inline cluster/shard_mapper.go]: why blank line?

**Comment by otoolep** [comment]
This makes sense to me, thanks @li-ang +1

@dgnorton -- I need a review from you too.

**Comment by corylanou** [comment]
Not sure if it's easily done, but it would be nice to see a test that shows why this fixes the problem.

**Comment by otoolep** [comment]
Yeah, I agree @corylanou -- it's somewhat difficult in the remote mapping scenario, but I think it's possible.

**Comment by otoolep** [comment]
Setting the "force remote mapping" flag might do it -- that's what it's there for.

**Comment by li-ang** [comment]
No setting the `force remote mapping` flag results as following:

```
➜  influx git:(master) ./influx -host 192.168.1.62
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://192.168.1.62:8086 version 0.9
InfluxDB shell 0.9
> show servers
id	cluster_addr		raft	raft-leader
1	192.168.1.62:8088	true	true
2	192.168.1.64:8088	true	false
3	192.168.1.3:8088	true	false

> show shards
name: foo_62
------------
id	database	retention_policy	shard_group	start_time	end_time		expiry_time		owners
1	foo_62		default			1		2015-11-16T00:00:00Z	2015-11-23T00:00:00Z	2015-11-23T00:00:00Z	1

> use foo_62
Using database foo_62

> show retention policies on foo_62
name	duration	replicaN	default
default	0		1		true

> select mean(float_value) from cpu where time > now() - 10m group by time(1m)
name: cpu
---------
time			mean
1447815780000000000	
1447815840000000000	
1447815900000000000	
1447815960000000000	
1447816020000000000	
1447816080000000000	
1447816140000000000	
1447816200000000000	0.4495545135199543
1447816260000000000	0.45045361601059564
1447816320000000000	0.45013218154087115
1447816380000000000	0.4511877603664354

> 

```
```
➜  influx git:(master) ./influx -host 192.168.1.3 
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://192.168.1.3:8086 version 0.9
InfluxDB shell 0.9
> show servers
id	cluster_addr		raft	raft-leader
1	192.168.1.62:8088	true	true
2	192.168.1.64:8088	true	false
3	192.168.1.3:8088	true	false

> show shards
name: foo_62
------------
id	database	retention_policy	shard_group	start_time	end_time		expiry_time		owners
1	foo_62		default			1		2015-11-16T00:00:00Z	2015-11-23T00:00:00Z	2015-11-23T00:00:00Z	1

> use foo_62
Using database foo_62
> show retention policies on foo_62
name	duration	replicaN	default
default	0		1		true

> select mean(float_value) from cpu where time > now() - 10m group by time(1m)
name: cpu
---------
time	mean
0	0.45079965450552983

> 
```

Setting the `force remote mapping` flag results as following:

```
> show shards
name: foo_62
------------
id	database	retention_policy	shard_group	start_time	end_time		expiry_time		owners
1	foo_62		default			1		2015-11-16T00:00:00Z	2015-11-23T00:00:00Z	2015-11-23T00:00:00Z	1

> use foo_62
Using database foo_62
> show retention policies on foo_62
name	duration	replicaN	default
default	0		1		true

> select mean(float_value) from cpu where time > now() - 10m group by time(1m)
name: cpu
---------
time	mean
0	0.45028738264377094

> 

➜  influx git:(master) ./influx -host 192.168.1.3
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://192.168.1.3:8086 version 0.9
InfluxDB shell 0.9
> show servers
id	cluster_addr		raft	raft-leader
1	192.168.1.62:8088	true	false
2	192.168.1.64:8088	true	true
3	192.168.1.3:8088	true	false

> show shards
name: foo_62
------------
id	database	retention_policy	shard_group	start_time	end_time		expiry_time		owners
1	foo_62		default			1		2015-11-16T00:00:00Z	2015-11-23T00:00:00Z	2015-11-23T00:00:00Z	1

> use foo_62
Using database foo_62
> select mean(float_value) from cpu where time > now() - 10m group by time(1m)
name: cpu
---------
time	mean
0	0.45069478050940354

> 
```

**Comment by li-ang** [comment]
@otoolep @corylanou

**Comment by otoolep** [comment]
@dgnorton -- ping.

**Comment by dgnorton** [comment]
+1
I would say it needs tests but we don't have a good framework setup to add them now.  @corylanou and I are working on that so this will be covered soon anyway.

**Comment by otoolep** [comment]
Thanks again @li-ang
