### PR TITLE
Handle error when point doesnt have a shard group

### LINKED ISSUE #4622: [0.9.5] Large timestamps panic openTSDB plugin
Giving openTSDB a point with a timestamp that is more than 13 digits long causes panic. However the database is still up and running.

```json
{
  "metric": "sys.cpu.nice",
  "timestamp": 12345678901234,
  "value": 9,
  "tags": {
    "host": "web02",
    "dc": "lga"
  }
}
```

```
2015/10/29 17:14:05 TSDB listener accept  &{0xc82032e368 0xc8202586c0}
2015/10/29 17:14:05 http: panic serving [::1]:53092: runtime error: invalid memory address or nil pointer dereference
goroutine 74 [running]:
net/http.(*conn).serve.func1(0xc82030b8c0, 0xf46de8, 0xc8203f6100)
	/Users/michaeldesa/.gvm/gos/go1.5.1/src/net/http/server.go:1287 +0xb5
github.com/influxdb/influxdb/cluster.(*PointsWriter).MapShards(0xc820134240, 0xc82030f980, 0xc82026d000, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/cluster/points_writer.go:207 +0x70e
github.com/influxdb/influxdb/cluster.(*PointsWriter).WritePoints(0xc820134240, 0xc82030f980, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/cluster/points_writer.go:240 +0x1df
github.com/influxdb/influxdb/services/opentsdb.(*Handler).servePut(0xc820108380, 0xf470e0, 0xc82030b970, 0xc82012e700)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/services/opentsdb/handler.go:121 +0xb0a
github.com/influxdb/influxdb/services/opentsdb.(*Handler).ServeHTTP(0xc820108380, 0xf470e0, 0xc82030b970, 0xc82012e700)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/services/opentsdb/handler.go:36 +0xa5
net/http.serverHandler.ServeHTTP(0xc8202a00c0, 0xf470e0, 0xc82030b970, 0xc82012e700)
	/Users/michaeldesa/.gvm/gos/go1.5.1/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82030b8c0)
	/Users/michaeldesa/.gvm/gos/go1.5.1/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/Users/michaeldesa/.gvm/gos/go1.5.1/src/net/http/server.go:1910 +0x3f6
```

### PR DESCRIPTION
**Pull request by nathanielc**
Fixes #4622

The OpenTSDB protocol interprets timestamps as microseconds so the time 12345678901234 is in the year 2361 but the maximum year that can be represented as an int64 nanoseconds timestamp is 2262 so during the protobuf seriealization we created an overflow that introduced odd behavior that later results in a panic. Both a sanity check for timestamps and shard group creating have been added so we do not panic.

### CODE REVIEW

File: meta/store.go [hunk 1]
```diff
@@ -1250,7 +1261,11 @@ func (s *Store) CreateShardGroupIfNotExists(database, policy string, timestamp t
...
 	sgi, err := s.CreateShardGroup(database, policy, timestamp)
 	if err == ErrShardGroupExists {
-		return s.ShardGroupByTimestamp(database, policy, timestamp)
+		sgi, err = s.ShardGroupByTimestamp(database, policy, timestamp)
+	}
+	// Check that we are returning either an error or a valid shard group.
+	if sgi == nil && err == nil {
+		return nil, errors.New("failed to create a new shard group, error unknown.")
 	}
 	return sgi, err
```
Comment (nathanielc) [inline meta/store.go]: This function was returning nil,nil as a result of the bug which later caused the panic.

File: CHANGELOG.md [hunk 2]
```diff
@@ -12,6 +12,7 @@
 
 ### Bugfixes
 - [#4849](https://github.com/influxdb/influxdb/issues/4849): Derivative works with count, mean, median, sum, first, last, max, min, and percentile.
+- [#4622](https://github.com/influxdb/influxdb/issues/4622): Fix panic when passing too large of timestamps to OpenTSDB input.
```
Comment (otoolep) [inline CHANGELOG.md]: This should be moved to the 0.9.7 section, since 0.9.6. has branched.

**Comment by otoolep** [comment]
If openTSDB is a specific source for this issue, shouldn't we also drop the points in that input, and perhaps add a stat?

I like this change (we should keep it), but I also think it's up to the input to drop the point if it recognises it can't be handled.

Thoughts?

**Comment by nathanielc** [comment]
I like the idea of dropping it at OpenTSDB, seems like its also possible in other protocols as well including the write line protocol. I'll take a look tomorrow to see if I can't reproduce this bug in other protocols.

**Comment by pauldix** [comment]
So is there a bug in the OpenTSDB input? Or is this time problem something that has since been fixed, but people still have bogus data already written in that we need to handle?

**Comment by nathanielc** [comment]
There is a bug in OpenTSDB since it reads times in microseconds its possible to represent a time that the rest of the system can't handle. I'll add a check for it in the OpenTSDB protocol. There is no data already written, the previous result was a panic getting a shard and so the data never made it to the data store engine.

We also have a similar bug in the write_protocol if you specify a precision and a time value that is out of range for int64 nanoseconds. The error doesn't result in a panic but rather an immediate overflow and we write a point with the wrong timestamp. I'll add some checks to the write line protocol as well. Not sure there is anything we can do about any existing data in this case.

Example that breaks the line protocol:

```
curl -X POST 'http://localhost:8086/write?db=testdb&precision=u' --data-binary 'test value=42 12345678901234'
```

Results in a data point being written to ~1970 when it should be in year ~2361


I'll push an update in a bit with the fix for the write_line parser so we can discuss the impact of the bug. I'll go check the other inputs as well so we catch these errors early.

**Comment by pauldix** [comment]
I'd say in the HTTP writer, we should return errors for time overflows. For all the other end points we can simply log the error and drop the point on the floor.

**Comment by nathanielc** [comment]
OK, that sounds good, I'll get patch up shortly.

**Comment by nathanielc** [comment]
How does this look? I added the time validation logic directly in the models/point.go code since that is the central location. As a result each input plugin now has sane validation and drops invalid packets or throws an error depending on their previous behavior. All the tests pass and even though it is a big change it seems like the right one.

File: models/points.go [hunk 3]
```diff
@@ -232,11 +232,32 @@ func parsePoint(buf []byte, defaultTime time.Time, precision string) (Point, err
 		if err != nil {
 			return nil, err
 		}
-		pt.time = time.Unix(0, ts*pt.GetPrecisionMultiplier(precision)).UTC()
+		pt.time, err = SafeCalcTime(ts, precision)
```
Comment (otoolep) [inline models/points.go]: Are there performance implications of doing this for every point?

Comment (nathanielc) [inline models/points.go]: For the case that the precision is in nanoseconds the only overhead is the function call which the compiler is hopefully in-lining anyway. The below result show that there isn't a measurable difference between master and this branch.

Master benchmarks for models:

```
BenchmarkMarshal-8                        300000              5026 ns/op
BenchmarkParsePointNoTags-8              2000000               612 ns/op          37.58 MB/s
BenchmarkParsePointsTagsSorted2-8        2000000               847 ns/op          60.15 MB/s
BenchmarkParsePointsTagsSorted5-8        1000000              1033 ns/op          80.32 MB/s
BenchmarkParsePointsTagsSorted10-8       1000000              1445 ns/op          98.93 MB/s
BenchmarkParsePointsTagsUnSorted2-8      1000000              1047 ns/op          48.68 MB/s
BenchmarkParsePointsTagsUnSorted5-8      1000000              1044 ns/op          79.44 MB/s
BenchmarkParsePointsTagsUnSorted10-8      500000              2580 ns/op          55.42 MB/s
```

Benchamrks for this branch:

```
BenchmarkMarshal-8                        300000              5158 ns/op
BenchmarkParsePointNoTags-8              2000000               630 ns/op          36.45 MB/s
BenchmarkParsePointsTagsSorted2-8        2000000               849 ns/op          60.07 MB/s
BenchmarkParsePointsTagsSorted5-8        1000000              1041 ns/op          79.71 MB/s
BenchmarkParsePointsTagsSorted10-8       1000000              1397 ns/op         102.34 MB/s
BenchmarkParsePointsTagsUnSorted2-8      1000000              1036 ns/op          49.20 MB/s
BenchmarkParsePointsTagsUnSorted5-8      1000000              1044 ns/op          79.49 MB/s
BenchmarkParsePointsTagsUnSorted10-8      500000              2489 ns/op          57.44 MB/s
```

But all of the benchmarks just parse with precision of "n" so I have added new benchmarks that parse with precision 'n' and 'u' to show the difference. When parsing with a non 'n' precision there is an extra divide operation. 

```
BenchmarkParsePointWithPrecisionN-8      2000000               624 ns/op          36.81 MB/s
BenchmarkParsePointWithPrecisionU-8      2000000               625 ns/op          36.77 MB/s
```

Based on these benchmarks there is not a significant difference between precision of 'n' and precision of 'u'

Comment (otoolep) [inline models/points.go]: Great, thanks for checking. This is heavily used code, so thought it better
to ask.

File: models/time.go [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+	MaxNanoTime = time.Unix(0, math.MaxInt64).UTC()
+	// Minumum time that can be represented via int64 nanoseconds since the epoch.
+	MinNanoTime = time.Unix(0, math.MinInt64).UTC()
+
+	// The time is out of the representable range using int64 nanoseconds since the epoch.
+	ErrTimeOutOfRange = fmt.Errorf("time outside range %s - %s", MinNanoTime, MaxNanoTime)
+)
+
+// Safely calculate the time given. Will return error if the time is outside the
+// support range.
```
Comment (otoolep) [inline models/time.go]: Nit: support -> supported

File: services/collectd/service.go [hunk 5]
```diff
@@ -29,6 +29,7 @@ const (
 	statBatchesTrasmitted   = "batchesTx"
 	statPointsTransmitted   = "pointsTx"
 	statBatchesTransmitFail = "batchesTxFail"
+	statDroppedPoints       = "droppedPoints"
```
Comment (otoolep) [inline services/collectd/service.go]: `droppedPoints` -> `droppedPointsInvalid` would be better.

File: services/opentsdb/service.go [hunk 6]
```diff
@@ -42,6 +42,7 @@ const (
 	statBatchesTransmitFail      = "batchesTxFail"
 	statConnectionsActive        = "connsActive"
 	statConnectionsHandled       = "connsHandled"
+	statDroppedPoints            = "droppedPoints"
```
Comment (otoolep) [inline services/opentsdb/service.go]: Again, let's put the word invalid in there to give us and our users a hint about why the points were dropped.

**Comment by otoolep** [comment]
Some small feedback, works for me. +1 once the changes are made.

@jwilder may like to look at this too.

**Comment by jwilder** [comment]
:+1:
