### PR TITLE
Distributed Query/Clustering Fixes

### LINKED ISSUE #2348: Data node fail to join cluster in 0.9.0rc25
I can't have additional data node joining a cluster with influxdb 0.9.0rc25 (or git master).

With the following configuration:

server1.toml:

```
port = 8086
reporting-disabled = true
[broker]
dir="/tmp/influxdb/8086/broker"
[data]
dir="/tmp/influxdb/8086/data"
```

server2.toml:
```
port = 8087
reporting-disabled = true
[broker]
dir="/tmp/influxdb/8087/broker"
[data]
dir="/tmp/influxdb/8087/data"
```

I start the influxDB server with:

```
$ rm -fr /tmp/influxdb/; influxd -config server1.toml
```

And, in another terminal
```
$ influxd -config server2.toml -join http://localhost:8086
```

After that, writing (with replication factor = 2) on either localhost:8086 or localhost:8087, only the first got the write.

In addition, curl on /data/data_nodes return only one URL

```
$ curl -v http://localhost:8086/data/data_nodes
[...]
[{"id":1,"url":"http://vanaheim:8086"}]
```

Following the exact same step with rc24, the last curl return two nodes:
```
[{"id":1,"url":"http://vanaheim:8086"},{"id":2,"url":"http://vanaheim:8087"}]
```

I've done a git bisect to find the commit which broke my setup, it's c5bdb5af.

More precisely, commenting the following line fix my issue : https://github.com/influxdb/influxdb/blob/3332f09c5b6c0d8c01750c87112f9eea663d7d9c/cmd/influxd/run.go#L643

Here is the paste with console output from influxdb : http://pastebin.com/zpCs9ZVd

### PR DESCRIPTION
**Pull request by jwilder**
This PR fixes cluster joins and distributed queries.

New data nodes would never join an existing cluster properly.  They would start up but would not attempt to join the cluster so they all reported themselves as Server ID 1.

The distributed queries issue was that previously sent data was not being cleared out on each iteration of the mapper output processing.  Subsequent iterations would send out duplicate data causing incorrect results.
 
Fixes #2348 #2343 #2334 #2272

### CODE REVIEW

File: cmd/influxd/server_integration_test.go [hunk 1]
```diff
@@ -1458,9 +1458,10 @@ func Test3NodeServerFailover(t *testing.T) {
 }
 
 // ensure that all queries work if there are more nodes in a cluster than the replication factor
-func Test3NodeClusterPartiallyReplicated(t *testing.T) {
+// and there is more than 1 shards
+func Test6NodeClusterPartiallyReplicated(t *testing.T) {
 	t.Parallel()
-	testName := "3-node server integration partial replication"
+	testName := "6-node server integration partial replication"
```
Comment (otoolep) [inline cmd/influxd/server_integration_test.go]: 6 is not really a valid number for a cluster. Best practices means you should use odd numbers. Why 6?

Comment (otoolep) [inline cmd/influxd/server_integration_test.go]: Why change it at all? Would 5 or 7 be better?

File: circle-test.sh [hunk 2]
```diff
@@ -67,7 +67,7 @@ case $CIRCLE_NODE_INDEX in
         rc=${PIPESTATUS[0]}
         ;;
     1)
-        go test $PARALLELISM $TIMEOUT -v -race ./... 2>&1 | tee $CIRCLE_ARTIFACTS/test_logs_race.txt
```
Comment (otoolep) [inline circle-test.sh]: Hmmm. I think we need to try hard to understand why we need to do this.

File: cmd/influxd/run.go [hunk 3]
```diff
@@ -682,6 +669,15 @@ func joinServer(s *influxdb.Server, u url.URL, joinURLs []url.URL) {
 			return
 		}
 	}
+
+	if len(joinURLs) == 0 {
```
Comment (otoolep) [inline cmd/influxd/run.go]: Not strictly part of this, but are we missing a return at line 666 above? If so, can you add it to this PR?

File: cmd/influxd/run.go [hunk 4]
```diff
@@ -662,10 +651,8 @@ func (cmd *RunCommand) openServer(joinURLs []url.URL) *influxdb.Server {
 	return s
 }
 
-// joins a server to an existing cluster.
-func joinServer(s *influxdb.Server, u url.URL, joinURLs []url.URL) {
-	// TODO: Use separate broker and data join urls.
-
+// joinOrInitializeServer a server to an existing cluster or initializes.
+func joinOrInitializeServer(s *influxdb.Server, u url.URL, joinURLs []url.URL) {
```
Comment (otoolep) [inline cmd/influxd/run.go]: Now that I see it I don't fully understand the comments in this function. 

"Create data node on an existing data node." -- what do this mean?

**Comment by otoolep** [comment]
Some of these changes look really important. I'm not ready to +1 it yet however, as I have some questions.

File: cmd/influxd/run.go [hunk 5]
```diff
@@ -642,19 +642,8 @@ func (cmd *RunCommand) openServer(joinURLs []url.URL) *influxdb.Server {
 	// Give brokers time to elect a leader if entire cluster is being restarted.
 	time.Sleep(1 * time.Second)
 
-	if s.ID() == 0 && s.Index() == 0 {
```
Comment (otoolep) [inline cmd/influxd/run.go]: So why wasn't this condition correct? Why was also requiring `Index()` to be 0 wrong?

**Comment by toddboom** [comment]
Reviewing this now.

File: cmd/influxd/server_integration_test.go (hunk 1 above)
Comment (corylanou) [inline cmd/influxd/server_integration_test.go]: What we are trying to do is get the server to create more than one shard per shard group, to test the full range of possibilities across writing/reading series data.

From what we could tell, the number of shards that a shard group creates is calculated on the # of data nodes / replication factor.  So, we needed something that would do that.  We probably should make this a 5 node cluster with a replication factor of 2.

File: circle-test.sh (hunk 2 above)
Comment (corylanou) [inline circle-test.sh]: Jason and I are running pprof to dig into this now.  We are creeping up to 13gb of memory when doing a parallel race test.  Anything above 4gb will fail on circle.

File: cmd/influxd/run.go (hunk 3 above)
Comment (corylanou) [inline cmd/influxd/run.go]: We did introduce that in this PR, and yes, it should have a return.  Will fix.

File: cmd/influxd/run.go (hunk 4 above)
Comment (corylanou) [inline cmd/influxd/run.go]: Comment is incorrect, will fix.

File: cmd/influxd/run.go (hunk 5 above)
Comment (corylanou) [inline cmd/influxd/run.go]: From what I understand, after you open your own meta store, you will read your ID from that, if you're ID isn't 0, your index certainly shouldn't be either, as you have been part of a cluster from before.

File: cmd/influxd/server_integration_test.go (hunk 1 above)
Comment (otoolep) [inline cmd/influxd/server_integration_test.go]: Yes, a node size of 5 and a replication factor of 2 would be better. That should result in shard groups of 2 shards in size, which will then result in 4 actual shards on the cluster.

File: cmd/influxd/run.go (hunk 3 above)
Comment (otoolep) [inline cmd/influxd/run.go]: OK. Perhaps it's something about the race testing framework?

File: circle-test.sh (hunk 2 above)
Comment (jwilder) [inline circle-test.sh]: Have a lead on what's going on here.  Need to amend this PR w/ a fix.

File: cmd/influxd/run.go (hunk 3 above)
Comment (jwilder) [inline cmd/influxd/run.go]: No.  Should not return here because this is looping over each joinURL.  If one fails, it will try the next one.  If they all fail, L681 will run and fatal out.

File: cmd/influxd/server_integration_test.go [hunk 6]
```diff
@@ -1458,9 +1458,10 @@ func Test3NodeServerFailover(t *testing.T) {
 }
 
 // ensure that all queries work if there are more nodes in a cluster than the replication factor
-func Test3NodeClusterPartiallyReplicated(t *testing.T) {
+// and there is more than 1 shards
+func Test5NodeClusterPartiallyReplicated(t *testing.T) {
 	t.Parallel()
-	testName := "3-node server integration partial replication"
+	testName := "6-node server integration partial replication"
```
Comment (otoolep) [inline cmd/influxd/server_integration_test.go]: `testName` not quite right 6-> 3

File: messaging/client.go [hunk 7]
```diff
@@ -353,12 +354,32 @@ func (c *Client) Conn(topicID uint64) *Conn {
...
+func (c *Client) CloseConn(topicID uint64) error {
+	c.mu.Lock()
+	defer c.mu.Unlock()
+
+	if conn, ok := c.conns[topicID]; ok && conn != nil {
+		if err := conn.Close(); err != nil {
+			return err
+		}
+
+		// Add to list of client connections.
```
Comment (otoolep) [inline messaging/client.go]: Add? Should that be remove?

File: messaging/client.go [hunk 8]
```diff
@@ -439,6 +460,10 @@ type Conn struct {
 
 // NewConn returns a new connection to the broker for a topic.
 func NewConn(topicID uint64, dataURL *url.URL) *Conn {
+	warn("new connection", topicID, dataURL.String())
+	//if topicID == 4 {
```
Comment (otoolep) [inline messaging/client.go]: Can we remove this commented out code?

File: server.go [hunk 9]
```diff
@@ -1015,8 +1015,38 @@ func (s *Server) applyDropDatabase(m *messaging.Message) (err error) {
...
+	for _, rp := range db.policies {
+		for _, sg := range rp.shardGroups {
+			for _, sh := range sg.Shards {
+
+				// if we have this shard locally, close and remove it
+				if sh.store != nil {
+					// close topic readers/heartbeaters/etc. connections
+					err := s.client.CloseConn(sh.ID)
+					if err != nil {
+						panic(err)
```
Comment (otoolep) [inline server.go]: Would `log.Fatal` be better here? Not sure, just a suggestion.

File: cmd/influxd/run.go (hunk 5 above)
Comment (otoolep) [inline cmd/influxd/run.go]: If I understand this issue correctly, the bug was that sometimes `s.ID()` was 0 but `s.Index()` was not, hence the bug?

**Comment by otoolep** [comment]
Changes look good, I have some minor comments you might wish to address, but I don't need to re-review. As long as I understand why just using `s.ID()` is correct, great. @benbjohnson also took a quick look at this.

+1, nice work.

**Comment by otoolep** [comment]
Don't forget the changelog.

File: cmd/influxd/run.go (hunk 5 above)
Comment (jwilder) [inline cmd/influxd/run.go]: Yes.  Index was non-zero.

File: server.go (hunk 9 above)
Comment (jwilder) [inline server.go]: These shouldn't ever happen so I used panic so we can get get a line number and more context if they did.  Not sure how best to handle this though because we've dropped the database from the metastore but we're failing to cleanup resources.

Comment (otoolep) [inline server.go]: Cool. Panic works for me.

**Comment by otoolep** [comment]
Yeah, here's hoping! It is probable.
