### PR TITLE
Fix CLI panic on malformed INSERT

### LINKED ISSUE #3078: Entering `insert foo` crashes `influx` CLI
Entering `insert foo` crashes the `influx` CLI application;

    > insert foo
    panic: runtime error: slice bounds out of range
     
    goroutine 1 [running]:
    main.(*CommandLine).Insert(0xc20806c580, 0xc208114420, 0x3, 0x0, 0x0)
	    /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cmd/influx/main.go:429 +0x6ca
    main.(*CommandLine).ParseCommand(0xc20806c580, 0xc208114420, 0xa, 0xc208114420)
	    /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cmd/influx/main.go:216 +0x9f1
    main.main()
	    /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/cmd/influx/main.go:169 +0xc0e
    
    goroutine 5 [syscall, 77 minutes]:
    os/signal.loop()
    	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
    created by os/signal.init·1
    	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

    goroutine 17 [syscall, 3632 minutes, locked to thread]:
    runtime.goexit()
    	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

### PR DESCRIPTION
**Pull request by gunnaraasen**
Fixes #3078

### CODE REVIEW

File: cmd/influx/main.go [hunk 1]
```diff
@@ -425,12 +425,9 @@ func (c *CommandLine) parseInto(stmt string) string {
 }
 
 func (c *CommandLine) Insert(stmt string) error {
-	stmt = stmt[7:]
-	if strings.EqualFold(stmt[:4], "into") {
-		stmt = c.parseInto(stmt[5:])
-	}
-	if c.RetentionPolicy == "" {
-		c.RetentionPolicy = "default"
+	stmt = strings.TrimSpace(strings.TrimSpace(stmt)[6:])
```
Comment (otoolep) [inline cmd/influx/main.go]: I know there were magic numbers there before, any way we can avoid them now? What is at position 6?

Comment (gunnaraasen) [inline cmd/influx/main.go]: The `[6:]` is meant to remove the `insert` at the beginning of the line. The assumption being that it's already there. Fair point about the magic numbers. I'll take them out.

Comment (otoolep) [inline cmd/influx/main.go]: Even something as simple as `INSERT_TOKEN_POS` would be better. It might be overkill, but `6` is pretty random looking.

**Comment by gunnaraasen** [comment]
@otoolep made some changes.

File: cmd/influx/main.go [hunk 2]
```diff
@@ -425,16 +425,17 @@ func (c *CommandLine) parseInto(stmt string) string {
 }
 
 func (c *CommandLine) Insert(stmt string) error {
-	stmt = stmt[7:]
-	if strings.EqualFold(stmt[:4], "into") {
-		stmt = c.parseInto(stmt[5:])
+	i, point := parseNextIdentifier(stmt)
+	if !strings.EqualFold(i, "insert") {
+		fmt.Println("ERR: missing space after INSERT")
```
Comment (otoolep) [inline cmd/influx/main.go]: I don't understand this error message. Is it correct?

Comment (gunnaraasen) [inline cmd/influx/main.go]: The function `ParseCommand` that calls `Insert` has already determined that the line begins with "insert". `parseNextIdentifier` returns the first word in the string and the remainder. If the first word is not exactly "insert", a space is missing.

Comment (otoolep) [inline cmd/influx/main.go]: OK.

What will this code do if presented with the line `INSERTxyx`?

Comment (gunnaraasen) [inline cmd/influx/main.go]: For the line `INSERTxyx`, it prints out `ERR: missing space after INSERT`, tosses the line, and displays a new prompt. Would you expect the CLI to attempt to write point `xyx`?

Comment (otoolep) [inline cmd/influx/main.go]: I thought it would say something like "found INSERTxyx, expected INSERT".
That would be a more standard error message.

**Comment by gunnaraasen** [comment]
Updated the error message. Received verbal +1 from @otoolep. Going to merge if tests pass.
