### PR TITLE
TSM1 fixes

### LINKED ISSUE #4388: Compactions create files bigger than 4GB
Data files can't be bigger than 4GB because the index positions are kept in `uint32`s. There's a bug right now that if a shard gets bigger than 4GB it will get compacted into 1 file instead of being spread out over multiple files.

* Test that ensures compaction doesn't do this
* Test that a flush from the wal to an old area of time that would cause the file to go over the limit doesn't cause a problem (the file should be split in two)

### LINKED ISSUE #4401: Compaction on previously rewritten file panics server
When writing data, if we write data to a file and there are ids in the file getting rewritten that don't have new values, it will cause the new file to be corrupt.

The user won't see this as a problem until either that file then tries to get rewritten again through another flush or through a compaction.

### PR DESCRIPTION
**Pull request by pauldix**
This is still a WIP since there are some other ones I'll be adding in here.

- [x] Ensure rewritten files aren't corrupt if the original had an id not being passed in that was at the end of the file. Fixes #4401
- [ ] Ensure compactions don't create files larger than 4GB. Fixes #4388
- [ ] Ensure that writes to old data files that would cause them to be larger than 4GB cause it to be split into two files

### CODE REVIEW

File: tsdb/engine/tsm1/tsm1.go [hunk 1]
```diff
@@ -1069,7 +1069,7 @@ func (e *Engine) rewriteFile(oldDF *dataFile, valuesByID map[uint64]Values) erro
 				currentPosition += (12 + length)
 
 				// make sure we're not at the end of the file
-				if fpos >= oldDF.size {
+				if fpos >= oldDF.indexPosition() {
```
Comment (jwilder) [inline tsdb/engine/tsm1/tsm1.go]: Ouch.

**Comment by jwilder** [comment]
:+1: On green.

**Comment by jwilder** [comment]
Looks like tests are failing on:
```
# github.com/influxdb/influxdb/tsdb/engine/tsm1_test
tsdb/engine/tsm1/tsm1_test.go:1365: e.MaxFileSize undefined (type *Engine has no field or method MaxFileSize)
```

**Comment by syepes** [comment]
Just to note that I am still getting the panic mentioned in the #4444 with d9f0413
```
2015/10/17 20:05:13 InfluxDB starting, version 0.9, branch master, commit d9f0413, built 1445009272
2015/10/17 20:05:13 Go version go1.5.1, GOMAXPROCS set to 8
..
..
[tsm1wal] 2015/10/17 20:05:42 startup flush of /opt/graphite/storage/influxdb/data/ESXi/raw/6 with 9773 keys and 430012 total values of 6880192 bytes
[tsm1] 2015/10/17 20:05:43 rewriting index file /opt/graphite/storage/influxdb/data/ESXi/raw/6/0001420.tsm1 with /opt/graphite/storage/influxdb/data/ESXi/raw/6/0001429.tsm1 
[tsm1] 2015/10/17 20:05:43 rewriting index file /opt/graphite/storage/influxdb/data/ESXi/raw/6/0001427.tsm1 with /opt/graphite/storage/influxdb/data/ESXi/raw/6/0001430.tsm1
panic: runtime error: index out of range

goroutine 73 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.Values.MinTime(0xc822ee5e80, 0x0, 0x0, 0x140dacb2f0ce3800)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/encoding.go:65 +0x75
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).DecodeAndCombine(0xc833359560, 0xc822ee5e80, 0x0, 0x0, 0x84efe6602, 0x31, 0x8dd85fd, 0xc83afee000, 0x0, 0x4e20, ...)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1668 +0x6bd
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).rewriteFile(0xc833359560, 0xc823c52780, 0xc82ab0a150, 0x0, 0x0)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1111 +0x220b
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Write.func3(0xc833359560, 0xc822c43a00, 0xc838478b40, 0xc822c43a10, 0xc823c52780, 0xc82ab0a150)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:415 +0x3f
created by github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Write
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:421 +0x95c

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc822c43a1c)
        /usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc822c43a10)
        /usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Write(0xc833359560, 0xc8352189c0, 0xc834b1bb30, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:436 +0x731
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Log).flush(0xc82cc11000, 0x3, 0x0, 0x0)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:598 +0xa96
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Log).readAndFlushWAL(0xc82cc11000, 0x0, 0x0)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:324 +0x1e8
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Log).Open(0xc82cc11000, 0x0, 0x0)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:153 +0x409
```

**Comment by jwilder** [comment]
Did you wipe your DB beforehand? Old data may be corrupted and not fixed by this.

**Comment by syepes** [comment]
@jwilder I only removed some files, I have just restarted the process with a fresh InfluxDB. If the issue is still present In 24/48h I should see the panic again.

**Comment by syepes** [comment]
@jwilder The Values.MinTime issue is still present:

```
2015/10/17 22:31:45 InfluxDB starting, version 0.9, branch master, commit d9f0413, built 1445009272
2015/10/17 22:31:45 Go version go1.5.1, GOMAXPROCS set to 8
..
..
[tsm1] 2015/10/18 09:05:38 rewriting index file /opt/graphite/storage/influxdb/data/ESXi/raw/4/0001362.tsm1 with /opt/graphite/storage/influxdb/data/ESXi/raw/4/0001365.tsm1
panic: runtime error: index out of range

goroutine 127532 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.Values.MinTime(0xc8498cbe80, 0x0, 0x0, 0x140e34f5a0af9000) 
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/encoding.go:65 +0x75
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).DecodeAndCombine(0xc825772240, 0xc8498cbe80, 0x0, 0x0, 0x80616efcf, 0x30, 0x849453d, 0xc835926000, 0x0, 0x4e20, ...)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1668 +0x6bd
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).rewriteFile(0xc825772240, 0xc8690c1e60, 0xc85726c090, 0x0, 0x0)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:1111 +0x220b
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Write.func3(0xc825772240, 0xc85736aea0, 0xc8516c80c0, 0xc85736aeb0, 0xc8690c1e60, 0xc85726c090)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:415 +0x3f
created by github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Write
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/tsm1.go:421 +0x95c

goroutine 1 [chan receive, 632 minutes]:
main.(*Main).Run(0xc820181f10, 0xc82008a010, 0x1, 0x1, 0x0, 0x0)
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:96 +0xa39
main.main()
        /opt/gcollectors/src/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0x29b
```

**Comment by pauldix** [comment]
@syepes can you do `ls -lah /opt/graphite/storage/influxdb/data/ESXi/raw/4/`
