### PR TITLE
Fix panic when droppping measurement while writing to it concurrently

### LINKED ISSUE #2608: [0.9.0-rc30] drop measurement while writing points to that measurement has race condition that can panic
Below is the log:

```
[http] 2015/05/19 18:07:35 127.0.0.1 - - [19/May/2015:18:07:35 +0800] GET /query?db=collectd&q=drop+measurement+%22value%22 HTTP/1.1 200 40 - InfluxDBShell/0.9.0-rc30 df45ba25-fe0e-11e4-86b7-000000000000 163.657862ms
panic: field does not exist for value
```

after the panic, I can never find any measurements at all (while there should be many):

```
> show measurements;
ERR: database not found: collectd; (/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:2704)
```

### PR DESCRIPTION
**Pull request by jwilder**
There is a race when writing points and dropping measurements where the fields are removed from the index while points are attempting to use them for encoding.

Produces this panic in 0.9.1-rc1
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x19c625]

goroutine 2744 [running]:
github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints(0xc2081ac000, 0xc21b450000, 0x1388, 0x1800, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdb/influxdb/tsdb/shard.go:246 +0x415
github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard(0xc208034be0, 0x6, 0xc21b450000, 0x1388, 0x1800, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdb/influxdb/tsdb/store.go:278 +0xf7
github.com/influxdb/influxdb/cluster.func·002(0x6, 0x1, 0xc21b450000, 0x1388, 0x1800)
	/Users/jason/go/src/github.com/influxdb/influxdb/cluster/points_writer.go:241 +0xfc
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
	/Users/jason/go/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x30b
```

Fixes #2608

### CODE REVIEW

File: tsdb/shard.go [hunk 1]
```diff
@@ -243,6 +243,13 @@ func (s *Shard) WritePoints(points []Point) error {
 			s.mu.RLock()
 			mf := s.measurementFields[p.Name()]
 			s.mu.RUnlock()
+
+			// If a measurement is dropped while writes for it are in progress, this could be nil
+			// See #2608
```
Comment (otoolep) [inline tsdb/shard.go]: Minor: I haven't seen us do this before i.e. reference bug numbers. I think the comment is pretty good as it is.

**Comment by otoolep** [comment]
Seems reasonable.+1

File: tsdb/shard.go (hunk 1 above)
Comment (jwilder) [inline tsdb/shard.go]: Removed the bug number reference.
