### PR TITLE
Fix similar float values encoding overflow

### LINKED ISSUE #4357: tsm1 storage engine reports strange spikes in values
Using collectd to feed perpetually increasing, counter-type values (e.g. eth0 rx/tx packet counters) into InfluxDB with tsm1 results in strange outliers occasionally:

```
SELECT "value" FROM "iolatency_read" WHERE "host" = 'foo.example.com' AND "instance" = 'md400' AND "type" = 'req_latency' AND "type_instance" = 'lt_8' AND time > now() - 10m

1444231716020334000	3.73705375e+08
1444231736022761000	3.73705896e+08
1444231756020388000	3.73706677e+08
1444231776016345000	3.73707002e+08
1444231796016225000	3.73708699e+08
1444231816019400000	3.73708855e+08
1444231836020839000	-8.551788012208318e-238
1444231856020667000	3.73709352e+08
1444231876022680000	3.737098e+08
1444231896014367000	3.7371048e+08
1444231916020391000	3.73711277e+08
1444231936020522000	3.73711405e+08
```

This in turn causes `derivative(mean("value"), 1s)` to go bananas, and results in unusable Grafana graphs.

Nothing has changed on the sending (collectd) side - only the storage engine in InfluxDB.

### PR DESCRIPTION
**Pull request by jwilder**
If similar float values were encoded, the number of leading bits would
overflow the 5 available bits to store them (e.g. store 33 in 5 bits).  When
decoding, the values after the overflowed value would spike to very large and
small values.

To prevent the overflow, we clamp the value to 31 which is the maximum
number of leading zero bits we can encode.

Fixes #4357

Thanks @dgryski for help fixing this.

### CODE REVIEW

**Comment by otoolep** [comment]
What does it actually mean to clamp? Do we lose some information?

**Comment by otoolep** [comment]
Or is it purely cosmetic the way 00000000.0001 and 0.0001 are the same numbers?

File: tsdb/engine/tsm1/float.go [hunk 1]
```diff
@@ -92,6 +98,9 @@ func (s *FloatEncoder) Push(v float64) {
 			s.bw.WriteBit(bitstream.One)
 			s.bw.WriteBits(leading, 5)
 
+			// Note that if leading == trailing == 0, then sigbits == 64.  But that value doesn't actually fit into the 6 bits we have.
```
Comment (otoolep) [inline tsdb/engine/tsm1/float.go]: Minor, but might we wrap this comment? Kinda wide.

**Comment by jwilder** [comment]
@otoolep It means to restrict a value to a given range.  If a value is greater than the max value for the range, the value is set to the max value.  Similarly if it's below the minimum value for a range, it's set to the min.

**Comment by otoolep** [comment]
Got it. This is not introducing any new range restrictions in our system, just enforcing existing restrictions I presume.

**Comment by otoolep** [comment]
I understand there are some float differences so small that the tsm1 engine cannot encode them. But the test data uses a set of values I presume is to bring out the issue, yet the tests expect the same values back. So the system encoded them with perfect fidelity.

What am I missing here?

**Comment by jwilder** [comment]
Yes.  Just fixing an overflow case where the number of leading zero bits overflow the allotted number of bits we have to store them.

**Comment by otoolep** [comment]
OK, if it's leading bits, then makes sense, since the numbers are the same.

+1 in that case.
