### PR TITLE
SELECT solely on time should return error

### LINKED ISSUE #3010: Should not be able to panic the database by using particular field keys
Hi,
I was trying to include field named "time" which is similar to the predefined "time" field.
While doing so, it didn't gave any error. But while querying the "time" from the measurement, it gave error and after that no single query is executing, even "select" or "show measurements" not working. 
So, I need to go to the /etc/init.d/ and restart the service.
Can anyone explain this issue?

### PR DESCRIPTION
**Pull request by otoolep**
Fixes #3010.

Simply check for `time` in the `SELECT` clause, and kick it back if the query contains it. Should this be a case-insensitive check?

### CODE REVIEW

**Comment by otoolep** [comment]
@dgnorton

**Comment by otoolep** [comment]
@corylanou

**Comment by pauldix** [comment]
It should actually be valid to put `time` in the select. It's better to ignore it.

**Comment by otoolep** [comment]
@pauldix -- what if it's the only SELECT field? No results back?

**Comment by pauldix** [comment]
then it should throw an error. They need to actually select some real data.

**Comment by otoolep** [comment]
Right, makes sense. So if it's the only field throw back an error, if it's accompanied by other fields, ignore it.

**Comment by otoolep** [comment]
@pauldix -- policy updated, plus test added to show that `time, value` already works fine.

File: cmd/influxd/run/server_test.go [hunk 1]
```diff
@@ -1394,6 +1394,11 @@ func TestServer_Query_Common(t *testing.T) {
 			exp:     fmt.Sprintf(`{"results":[{"series":[{"name":"cpu","columns":["time","value"],"values":[["%s",1]]}]}]}`, now.Format(time.RFC3339Nano)),
 		},
 		&Query{
+			name:    "explicitly selecting time and a valid measurement and field should succeed",
+			command: `SELECT time,value FROM db0.rp0.cpu`,
```
Comment (corylanou) [inline cmd/influxd/run/server_test.go]: A test with `select value, time` would be nice as it would show that `time` will always be the first column, but all other columns still maintain their sort order (or should)

File: influxql/ast.go [hunk 2]
```diff
@@ -1008,6 +1012,14 @@ func (s *SelectStatement) validate(tr targetRequirement) error {
 	return nil
 }
 
+func (s *SelectStatement) validateFields() error {
+	ns := s.NamesInSelect()
+	if len(ns) == 1 && ns[0] == "time" {
```
Comment (corylanou) [inline influxql/ast.go]: case sensitive?

Comment (otoolep) [inline influxql/ast.go]: I don't know for use. I guess?

File: cmd/influxd/run/server_test.go (hunk 1 above)
Comment (otoolep) [inline cmd/influxd/run/server_test.go]: Will add.

Comment (otoolep) [inline cmd/influxd/run/server_test.go]: Well, well, that test case fails. The following data comes back:

```
actual: {"results":[{"series":[{"name":"cpu","columns":["value","time"],"values":[["2015-08-20T23:57:35.973310065Z",1]]}]}]}
```

I'd like to address this separately as it will require a somewhat wider set of changes. OK? https://github.com/influxdb/influxdb/issues/3779

I'd like to get this panic fixed before the 0.9.3 window closes.

Comment (corylanou) [inline cmd/influxd/run/server_test.go]: Sounds good

**Comment by corylanou** [comment]
+1

**Comment by dgnorton** [comment]
@pauldix are there event based use cases where the value isn't important...only the time it happened matters?

**Comment by pauldix** [comment]
@dgnorton maybe, but they still need to store at least one value. For those use cases I would recommend using a boolean. Guess it's a little wasteful to return that, but this is definitely the least of our concerns right now.

**Comment by pauldix** [comment]
+1

**Comment by otoolep** [comment]
Thanks for the reviews @pauldix and @corylanou -- merging on green and will cherry-pick to 0.9.3.

**Comment by nornagon** [comment]
FWIW, I'm building an alerting system on top of influxdb and it would be really useful to be able to get the _time of_ the last reported value for a particular series, without particular reference to the value itself. The goal is to write an alert that checks for "is still receiving data", in case the sensors in question die.

**Comment by gunnaraasen** [comment]
@nornagon that sounds like a valid use case that hasn't been fully discussed. Can you open a new issue with a feature request?

**Comment by nornagon** [comment]
Done: #4862
