### PR TITLE
Fix Order By Desc

### LINKED ISSUE #4235: [0.9.4.1] "ORDER BY DESC" doesn't properly order output
I'm trying to get the newest *n* points from a series

    >  select * from "76603ea0-f7ea-40ce-819a-df51f16cb379" where time > now() - 1m
    name: 76603ea0-f7ea-40ce-819a-df51f16cb379
    ------------------------------------------
    time				            value
    2015-09-25T21:54:51.074Z	    3.49632
    2015-09-25T21:55:21.084Z	    3.51199
    
    > select value from "76603ea0-f7ea-40ce-819a-df51f16cb379" order by desc limit 10
    name: 76603ea0-f7ea-40ce-819a-df51f16cb379
    ------------------------------------------
    time				            value
    2015-09-25T21:38:50.69Z	        3.34024
    2015-09-25T21:38:20.673Z        3.33428
    2015-09-25T21:37:50.663Z	    3.33001
    2015-09-25T21:37:20.653Z	    3.32566
    2015-09-25T21:36:50.636Z	    3.32132
    2015-09-25T21:36:20.626Z	    3.31698
    2015-09-25T21:35:50.615Z	    3.31252
    2015-09-25T21:35:20.605Z	    3.30831
    2015-09-25T21:34:50.595Z	    3.30364
    2015-09-25T21:34:20.585Z	    3.29886

The first query correctly shows the latest point:

    2015-09-25T21:55:21.084Z	    3.51199

But the second query is showing 10 points from an earlier time.
The data is coming in every 30 seconds, but I keep getting the exact same resultset from the second query until I restart influxdb, and then it stays at a newer resultset.

### PR DESCRIPTION
**Pull request by corylanou**
Used the `heap.Interface` to be able to support a `Reverse` interface on `TagSetCursor` when it is order by `DESC`

fixes #4235.

### CODE REVIEW

**Comment by corylanou** [comment]
Current test output (broken as expected based on issue):

```
query:  select value from "power" ORDER BY time DESC
exp:    {"results":[{"series":[{"name":"power","columns":["time","value"],"values":[["2000-01-01T00:00:04Z",4],["2000-01-01T00:00:03Z",3],["2000-01-01T00:00:02Z",2],["2000-01-01T00:00:01Z",1]]}]}]}
actual: {"results":[{"series":[{"name":"power","columns":["time","value"],"values":[["2000-01-01T00:00:03Z",3],["2000-01-01T00:00:02Z",2],["2000-01-01T00:00:04Z",4],["2000-01-01T00:00:01Z",1]]}]}]}
```

**Comment by otoolep** [comment]
Great change, a lovely example of interfaces. +1 on green.

File: tsdb/cursor.go [hunk 1]
```diff
@@ -297,13 +303,27 @@ type pointHeapItem struct {
 }
 
 type pointHeap []*pointHeapItem
+type pointHeapReverse struct {
+	pointHeap
+}
 
-func newPointHeap() *pointHeap {
+func newPointHeap() heap.Interface {
```
Comment (otoolep) [inline tsdb/cursor.go]: Only thing you might prefer is that the "constructor" could be of the form `newPointHeap(ascending bool)`.
